import { ballPath as B, player as P, type Drill } from '../types'

/**
 * Attacking Situation Drills — 15 drills from the attacking manual.
 *
 * Paths are approximations of the manual's written movements: the shape,
 * sequencing and timing are faithful, the exact metre-by-metre coordinates
 * are authored to read clearly in 3D rather than measured from a session.
 * All drills attack the goal at z = -52.5.
 */
export const ATTACKING: Drill[] = [
  {
    id: 'atk-1',
    category: 'Attacking',
    group: 'Tiki-taka and positional play',
    code: '1',
    title: 'Overload Build-up (3v2 in the Final Third)',
    style: 'Positional play, tiki-taka',
    area: '40m x 30m, full goal + GK',
    playerCount: '3 attackers, 2 defenders, 1 GK',
    durationLabel: '12 min · ~8s per rep · 40s recovery',
    description:
      'Three attackers in three separate vertical lanes attack two centre backs. The carrier commits a defender, releases at the moment their weight goes forward, then joins the box.',
    setup:
      'Starting line 40m from goal. Central midfielder middle, winger on the touchline, striker central and high. Two centre backs hold a line 25m from goal.',
    keyPoints: [
      'The overload only exists while all three attackers occupy different vertical lanes.',
      'Release the pass on the defender’s front foot, not at a fixed distance.',
      'After passing, the carrier must continue into the box — a 3-man attack that becomes a 2-man attack wastes the overload.',
      'Target 70% of reps ending with a shot inside 8 seconds.',
    ],
    simulationNote:
      'Real overloads come from a turnover, not a static start. Serve the ball at a random moment while attackers jog back from the previous rep.',
    view: 'half',
    duration: 8,
    zones: [{ x: 0, z: -26, w: 30, d: 40, label: 'Working area' }],
    players: [
      P('cm', 'CM', 'Central midfielder (ball carrier)', 'attack', [
        [0, 0, -12.5, 'idle'],
        [1, 0, -15, 'dribble'],
        [2.4, 0.5, -19.5, 'dribble'],
        [2.9, 1, -20.5, 'pass'],
        [5, 3, -30, 'sprint'],
        [7.2, 4.5, -38, 'run'],
        [8, 5, -40, 'jog'],
      ]),
      P('rw', 'RW', 'Winger', 'attack', [
        [0, 14, -14, 'idle'],
        [2.4, 14, -15.5, 'scan'],
        [4.2, 15.5, -24, 'sprint'],
        [5.3, 16, -31, 'receive'],
        [6.4, 10.5, -37.5, 'dribble'],
        [7, 9.5, -39, 'cross'],
        [8, 9, -41, 'jog'],
      ]),
      P('st', 'ST', 'Striker', 'attack', [
        [0, 3, -24, 'idle'],
        [2.6, 4.5, -26, 'jog'],
        [4.6, 8.5, -31, 'sprint'],
        [6.4, 6, -40, 'sprint'],
        [7.3, 3.5, -43, 'shoot'],
        [8, 2.5, -44.5, 'jog'],
      ]),
      P('cb1', 'CB', 'Pressing centre back', 'defense', [
        [0, -4, -27.5, 'idle'],
        [2.4, -1, -22.5, 'press'],
        [4.5, 2, -28, 'run'],
        [6.5, 4, -35, 'run'],
        [8, 5, -38, 'jog'],
      ]),
      P('cb2', 'CB', 'Covering centre back', 'defense', [
        [0, 5, -27.5, 'idle'],
        [2.6, 7, -30, 'jockey'],
        [4.8, 9.5, -35, 'run'],
        [6.6, 7, -41.5, 'run'],
        [8, 6, -43, 'jog'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50, 'idle'],
        [4, 0.5, -49, 'jog'],
        [6.6, 1.5, -48, 'jog'],
        [8, 2.5, -48.5, 'block'],
      ]),
    ],
    ball: B([
      [0, 0, -12.5],
      [1, 0, -15],
      [2.6, 1, -20],
      [3.6, 15.5, -25],
      [5.3, 16, -31],
      [6.4, 10.5, -37.5],
      [7.2, 3.5, -42.5],
      [8, 0.5, -52, 0.6],
    ]),
  },

  {
    id: 'atk-2',
    category: 'Attacking',
    group: 'Total football and rotation',
    code: '2',
    title: 'Third-man Run',
    style: 'Total football, tiki-taka',
    area: '30m x 25m into a full goal',
    playerCount: '1 deep passer, 1 striker, 1 attacking midfielder, 1 defender, 1 GK',
    durationLabel: '10 min · 6s per rep',
    description:
      'Deep pass into the striker’s back foot, one-touch lay-off, third man arrives already facing goal. The run starts while the first pass is still travelling.',
    setup:
      'Deep passer with a supply of balls. Striker 20m from goal, defender marking from behind. Attacking midfielder 10m behind and to the side.',
    keyPoints: [
      'The runner must start while the ball is still travelling to the striker.',
      'Lay-off is one touch, always — two touches gives the defence a full second.',
      'The striker never turns; the drill fails the moment they try to beat the defender.',
      'Run in a curve so you receive already facing goal.',
    ],
    simulationNote:
      'Add a decoy running the opposite way. In matches the third-man run works because the defence follows the wrong runner.',
    view: 'half',
    duration: 6,
    zones: [{ x: 0, z: -30, w: 25, d: 30, label: 'Working area' }],
    players: [
      P('dp', 'DM', 'Deep passer (CB or DM)', 'defense', [
        [0, 0, -18, 'scan'],
        [0.9, 0, -18.5, 'pass'],
        [3, 0, -20, 'jog'],
        [6, 0, -22, 'idle'],
      ]),
      P('st', 'ST', 'Striker (wall)', 'attack', [
        [0, 0.5, -31, 'idle'],
        [1.2, 0, -30, 'hold'],
        [2.2, 0, -30.5, 'hold'],
        [3.1, -0.5, -31, 'layoff'],
        [4.5, 2.5, -36, 'jog'],
        [6, 3.5, -39, 'jog'],
      ]),
      P('am', 'AM', 'Attacking midfielder (third man)', 'attack', [
        [0, -6.5, -23, 'idle'],
        [1.2, -6, -25, 'run'],
        [2.4, -5, -30, 'sprint'],
        [3.4, -2, -34, 'receive'],
        [4.3, -0.5, -37.5, 'dribble'],
        [5, 0, -39, 'shoot'],
        [6, 0.5, -41, 'jog'],
      ]),
      P('d1', 'CB', 'Marking defender', 'defense', [
        [0, 0.5, -33, 'idle'],
        [1.6, 0.3, -31.8, 'press'],
        [3.1, -0.4, -32.4, 'tackle'],
        [4.6, -1.5, -35, 'sprint'],
        [6, -1, -38, 'run'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [3.5, 0, -49.5, 'jog'],
        [5, 0.5, -48.5, 'block'],
        [6, 0.5, -48.5, 'idle'],
      ]),
    ],
    ball: B([
      [0, 0, -18.5],
      [1.9, 0, -30.6],
      [2.6, 0, -30.6],
      [3.4, -2, -34],
      [4.3, -0.5, -37.5],
      [5.1, 0, -39],
      [6, 0.6, -52, 0.9],
    ]),
  },

  {
    id: 'atk-3',
    category: 'Attacking',
    group: 'Wing play and direct crossing',
    code: '3',
    title: 'Wide Combination and Cutback',
    style: 'Wing play',
    area: 'Half pitch, full goal, GK',
    playerCount: 'Fullback, winger, striker, far winger, 2 defenders, 1 GK',
    durationLabel: '15 min · alternate left and right',
    description:
      'Winger drags the fullback infield, releases the overlap on the defender’s hips, and the fullback drives to the byline for a low cutback to the penalty spot.',
    setup:
      'Attackers start 35m from goal on one flank. A defending fullback covers the flank, a centre back defends the box.',
    keyPoints: [
      'The trigger for the overlap is the defender’s hips turning inside, not the fullback’s shout.',
      'Target the byline, not the corner flag — the target line is the 6-yard box extended.',
      'Cut back low and firm with the inside of the foot. Never chip.',
      'Three arrivals in the box: near post, penalty spot, back post.',
    ],
    simulationNote:
      'Have the coach call "early" or "byline" at random as the fullback receives, forcing the decision to be read rather than rehearsed.',
    view: 'half',
    duration: 9,
    players: [
      P('rb', 'RB', 'Attacking fullback', 'attack', [
        [0, 20, -13, 'idle'],
        [2.2, 21, -18, 'jog'],
        [4, 24, -27, 'sprint'],
        [6.2, 22, -44, 'dribble'],
        [7, 21, -46, 'cross'],
        [9, 21.5, -47, 'jog'],
      ]),
      P('rw', 'RW', 'Winger', 'attack', [
        [0, 18, -17, 'receive'],
        [1.3, 16, -20, 'dribble'],
        [2.5, 13, -22, 'pass'],
        [5, 9, -33, 'sprint'],
        [7, 4.5, -41, 'run'],
        [8.2, 2, -43, 'shoot'],
        [9, 1, -45, 'jog'],
      ]),
      P('st', 'ST', 'Striker', 'attack', [
        [0, 2, -29, 'idle'],
        [2.6, 4, -33, 'jog'],
        [5.8, 11, -45, 'sprint'],
        [7.2, 5, -42.5, 'run'],
        [9, 4, -44, 'jog'],
      ]),
      P('lw', 'LW', 'Far-side winger', 'attack', [
        [0, -19, -22, 'idle'],
        [3, -17, -26, 'jog'],
        [6.2, -8, -38, 'sprint'],
        [7.8, -3, -44.5, 'run'],
        [9, -2, -46, 'jog'],
      ]),
      P('dfb', 'LB', 'Defending fullback', 'defense', [
        [0, 20, -21, 'jockey'],
        [1.3, 18, -22, 'jockey'],
        [2.6, 15, -24, 'press'],
        [4.4, 20, -30, 'sprint'],
        [6.4, 21, -42, 'run'],
        [9, 20, -45, 'jog'],
      ]),
      P('dcb', 'CB', 'Defending centre back', 'defense', [
        [0, 4, -40, 'idle'],
        [4, 6, -42, 'jockey'],
        [6, 9.5, -45, 'run'],
        [7.4, 5, -43.5, 'run'],
        [9, 3.5, -45.5, 'block'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [4, 2, -50, 'jog'],
        [6.6, 5, -49, 'jog'],
        [8.2, 2, -49.5, 'block'],
        [9, 1, -49.5, 'idle'],
      ]),
    ],
    ball: B([
      [0, 18, -17],
      [1.3, 16, -20],
      [2.5, 13.5, -22],
      [3.5, 23, -26.5],
      [6.2, 22, -44],
      [7.2, 3, -42.5],
      [8.3, 2, -43],
      [9, 0.5, -52, 0.5],
    ]),
  },

  {
    id: 'atk-4',
    category: 'Attacking',
    group: 'Gegenpress and vertical transition',
    code: '4',
    title: 'Counter-attack Transition (5v3 Breaking)',
    style: 'Gegenpress, vertical transition',
    area: 'Full pitch length, 50m wide, two goals',
    playerCount: '5 attackers, 3 defenders, GKs',
    durationLabel: '14 min · 10s sequences · generous rest',
    description:
      'The instant possession is won the first pass goes forward, the striker sprints in behind, both wings stretch the pitch and a trailing midfielder covers the cutback and the second ball.',
    setup:
      'Attackers start in their own half in a defensive shape. Coach plays a ball to a neutral defender. The counter starts the moment the ball is won.',
    keyPoints: [
      'Never pass square or backwards in the first 3 seconds.',
      'The far winger must run as hard as the ball-side winger — the far post is the highest value arrival.',
      'Trailing midfielder stays 10 to 15m behind the ball for the cutback and the rebound.',
      'Elite counters reach the final third within 6 to 8 seconds.',
    ],
    simulationNote:
      'Vary where the turnover happens — own third, midfield, just outside the opponent box. Each produces a different counter shape.',
    view: 'full',
    duration: 10,
    players: [
      P('fr', 'CM', 'First receiver', 'attack', [
        [0, 0, 15, 'receive'],
        [1.4, 0, 12, 'pass'],
        [4, -1, 2, 'run'],
        [7, -2, -12, 'run'],
        [10, -2, -22, 'jog'],
      ]),
      P('st', 'ST', 'Striker', 'attack', [
        [0, -1, -4, 'idle'],
        [1, -1.5, -9, 'sprint'],
        [3.2, -2, -16, 'receive'],
        [6.5, -4, -33, 'dribble'],
        [8.4, -4, -40, 'shoot'],
        [10, -4, -42, 'jog'],
      ]),
      P('lw', 'LW', 'Left winger', 'attack', [
        [0, -22, 6, 'idle'],
        [1, -23, 0, 'sprint'],
        [4.5, -24, -18, 'sprint'],
        [7.5, -16, -34, 'sprint'],
        [10, -10, -42, 'run'],
      ]),
      P('rw', 'RW', 'Right winger', 'attack', [
        [0, 22, 6, 'idle'],
        [1, 23, 0, 'sprint'],
        [4.5, 24, -18, 'sprint'],
        [8, 13, -38, 'sprint'],
        [10, 8, -44, 'run'],
      ]),
      P('cm2', 'CM', 'Trailing midfielder', 'attack', [
        [0, 4, 20, 'idle'],
        [2, 3, 12, 'run'],
        [6, 2, -8, 'run'],
        [9, 1, -24, 'run'],
        [10, 1, -28, 'jog'],
      ]),
      P('d1', 'CB', 'Delaying defender', 'defense', [
        [0, -4, -8, 'jockey'],
        [3.5, -4, -20, 'run'],
        [6.5, -4, -32, 'jockey'],
        [8.6, -3.5, -39, 'block'],
        [10, -3, -41, 'jog'],
      ]),
      P('d2', 'CB', 'Covering defender', 'defense', [
        [0, 7, -10, 'idle'],
        [4, 6, -24, 'run'],
        [7.5, 4, -36, 'run'],
        [10, 3, -41, 'jog'],
      ]),
      P('d3', 'FB', 'Recovering fullback', 'defense', [
        [0, -14, -12, 'idle'],
        [4, -14, -24, 'run'],
        [8, -12, -36, 'run'],
        [10, -9, -41, 'jog'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [6, -1, -49.5, 'jog'],
        [8.6, -2.5, -48, 'block'],
        [10, -2.5, -48.5, 'idle'],
      ]),
    ],
    ball: B([
      [0, 0, 15],
      [1.4, 0, 12],
      [3.1, -2, -16],
      [6.5, -4, -33],
      [8.5, -4, -40],
      [10, -1, -52, 1],
    ]),
  },

  {
    id: 'atk-5',
    category: 'Attacking',
    group: 'Tiki-taka and positional play',
    code: '5',
    title: 'Half-space Pattern Play',
    style: 'Tiki-taka, positional play',
    area: 'Full width, halfway to goal, five vertical lanes',
    playerCount: '8 attackers vs 5 defenders and a GK',
    durationLabel: '20 min',
    description:
      'Centre backs draw the block, the DM switches in one pass, the inside forward receives on the half turn in the half-space and the striker spins in behind the instant their body opens.',
    setup:
      'Five vertical lanes marked: two wide, two half-spaces, one central. Attackers obey lane occupation rules. Defenders in a 4-1 block.',
    keyPoints: [
      'Maximum two players per vertical lane; minimum one player in each wide lane at all times.',
      'The half-space player can see and pass to both the wide lane and the central lane — defenders must choose.',
      'If the winger drifts inside, the half-space closes. Single most common breakdown.',
      'Striker spins the instant the inside forward’s body opens toward goal.',
    ],
    simulationNote:
      'Change the defensive block between sets: 4-4-2 mid block, 5-3-2 low block, high pressing 4-3-3. The half-space entry looks different against each.',
    view: 'half',
    duration: 11,
    zones: [
      { x: -27, z: -26, w: 14, d: 52, label: 'Wide lane', color: '#7fd1ff' },
      { x: -13.5, z: -26, w: 13, d: 52, label: 'Half-space', color: '#ffd84d', fill: true },
      { x: 0, z: -26, w: 14, d: 52, label: 'Central lane', color: '#7fd1ff' },
      { x: 13.5, z: -26, w: 13, d: 52, label: 'Half-space', color: '#ffd84d', fill: true },
      { x: 27, z: -26, w: 14, d: 52, label: 'Wide lane', color: '#7fd1ff' },
    ],
    players: [
      P('cb1', 'CB', 'Left centre back', 'attack', [
        [0, -13, -2, 'receive'],
        [1.2, -13, -3, 'pass'],
        [11, -12, -6, 'jog'],
      ]),
      P('cb2', 'CB', 'Right centre back', 'attack', [
        [0, 13, -2, 'idle'],
        [4, 13, -5, 'jog'],
        [11, 12, -8, 'idle'],
      ]),
      P('dm', 'DM', 'Defensive midfielder', 'attack', [
        [0, -1, -9, 'scan'],
        [2, -0.5, -10.5, 'receive'],
        [3.2, 1, -11, 'pass'],
        [7, 2, -16, 'jog'],
        [11, 2, -20, 'jog'],
      ]),
      P('ifr', 'IF', 'Right inside forward', 'attack', [
        [0, 13, -22, 'scan'],
        [3.4, 13.5, -23, 'receive'],
        [4.6, 12, -26, 'dribble'],
        [5.6, 11, -28, 'pass'],
        [8, 8, -36, 'run'],
        [11, 6, -42, 'jog'],
      ]),
      P('ifl', 'IF', 'Left inside forward', 'attack', [
        [0, -13, -20, 'idle'],
        [4, -13, -24, 'jog'],
        [8, -10, -34, 'run'],
        [11, -6, -42, 'run'],
      ]),
      P('rw', 'RW', 'Right winger', 'attack', [
        [0, 28, -24, 'idle'],
        [4.6, 28, -27, 'idle'],
        [7, 27, -33, 'run'],
        [11, 25, -40, 'jog'],
      ]),
      P('lw', 'LW', 'Left winger', 'attack', [
        [0, -28, -24, 'idle'],
        [6, -28, -28, 'idle'],
        [9, -26, -37, 'run'],
        [11, -24, -42, 'jog'],
      ]),
      P('st', 'ST', 'Striker', 'attack', [
        [0, 1, -33, 'idle'],
        [4.4, 2, -34, 'hold'],
        [5.6, 5, -35, 'sprint'],
        [7.4, 7, -41, 'receive'],
        [8.8, 4, -44, 'shoot'],
        [11, 3, -46, 'jog'],
      ]),
      P('dm1', 'DM', 'Screening midfielder', 'defense', [
        [0, 0, -18, 'press'],
        [3, 6, -20, 'press'],
        [6, 9, -24, 'run'],
        [11, 8, -32, 'jog'],
      ]),
      P('dcb1', 'CB', 'Centre back', 'defense', [
        [0, -4, -35, 'idle'],
        [5, -2, -35, 'jockey'],
        [7.6, 3, -38, 'run'],
        [9, 4, -42, 'block'],
        [11, 4, -44, 'jog'],
      ]),
      P('dcb2', 'CB', 'Centre back', 'defense', [
        [0, 5, -35, 'idle'],
        [5.4, 7, -34, 'jockey'],
        [8, 10, -38, 'run'],
        [11, 9, -43, 'jog'],
      ]),
      P('dfb', 'FB', 'Fullback', 'defense', [
        [0, 17, -30, 'idle'],
        [4, 16, -30, 'jockey'],
        [7, 19, -34, 'run'],
        [11, 21, -38, 'jog'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [7, 1, -49.5, 'jog'],
        [8.9, 3, -48, 'block'],
        [11, 3, -48.5, 'idle'],
      ]),
    ],
    ball: B([
      [0, -13, -2],
      [1.9, -0.5, -10.5],
      [3.4, 13.5, -23],
      [4.6, 12, -26],
      [6.4, 7.5, -40],
      [7.6, 7, -41],
      [9, 4, -44],
      [11, 0.8, -52, 0.7],
    ]),
  },

  {
    id: 'atk-6',
    category: 'Attacking',
    group: 'Wing play and direct crossing',
    code: '6',
    title: 'Three-zone Box Attack (Crossing and Finishing)',
    style: 'Wing play, direct crossing',
    area: 'Penalty area plus 20m wide channels',
    playerCount: '2 crossers, 4-6 attackers rotating, 2 defenders, 1 GK',
    durationLabel: '18 min · alternating sides',
    description:
      'Three runners attack three separate zones — near post, penalty spot, back post — at three separate times, against a crosser limited to two touches.',
    setup:
      'Six-yard box and penalty area divided into three target zones. Crossers work from wide channels on both sides. Attackers enter in threes.',
    keyPoints: [
      'Three different arrival points and three different arrival times.',
      'Penalty-spot runner delays half a second and approaches on a curve.',
      'Never cross into the goalkeeper’s zone — the arc within ~5m of the goal line.',
      'Runs into the box change pace: slow, then explosive.',
    ],
    simulationNote:
      'Fatigue changes crossing quality dramatically. Run this at the end of a session at least once a week.',
    view: 'box',
    duration: 6,
    zones: [
      { x: 8, z: -46, w: 10, d: 12, label: 'Near post', color: '#ff9f5a' },
      { x: 0, z: -42, w: 12, d: 10, label: 'Penalty spot', color: '#ffd84d' },
      { x: -9, z: -46, w: 10, d: 12, label: 'Back post', color: '#7fd1ff' },
    ],
    equipment: [
      { kind: 'cone', x: 20, z: -32 },
      { kind: 'cone', x: 20, z: -44 },
      { kind: 'cone', x: -20, z: -32 },
      { kind: 'cone', x: -20, z: -44 },
    ],
    players: [
      P('cr', 'CR', 'Crosser', 'attack', [
        [0, 26, -33, 'receive'],
        [1.4, 25, -38, 'dribble'],
        [2.4, 24, -40, 'cross'],
        [6, 24, -42, 'jog'],
      ]),
      P('np', 'NP', 'Near post runner', 'attack', [
        [0, 1, -32, 'idle'],
        [1.4, 3, -36, 'jog'],
        [3.4, 8, -45.5, 'sprint'],
        [4.2, 8.5, -47, 'header'],
        [6, 7, -47.5, 'jog'],
      ]),
      P('ps', 'PS', 'Penalty spot runner', 'attack', [
        [0, -7, -31, 'idle'],
        [1.8, -6, -34, 'jog'],
        [3.9, 0, -41.5, 'sprint'],
        [4.6, 0.5, -43, 'shoot'],
        [6, 0.5, -44, 'jog'],
      ]),
      P('bp', 'BP', 'Back post runner', 'attack', [
        [0, -17, -34, 'idle'],
        [2, -15, -37, 'jog'],
        [4.2, -6, -45, 'sprint'],
        [6, -4, -46.5, 'jog'],
      ]),
      P('ed', 'ED', 'Edge of box player', 'attack', [
        [0, 0, -29, 'idle'],
        [2.6, 0, -34, 'jog'],
        [6, 0, -35.5, 'shoot'],
      ]),
      P('d1', 'CB', 'Near post marker', 'defense', [
        [0, 6, -44, 'idle'],
        [2.6, 7, -45, 'jockey'],
        [4.2, 9.5, -46.5, 'block'],
        [6, 8, -47, 'jog'],
      ]),
      P('d2', 'CB', 'Penalty spot marker', 'defense', [
        [0, -2, -41, 'idle'],
        [3, -1.5, -42, 'jockey'],
        [4.6, 1.5, -43, 'block'],
        [6, 1, -44, 'jog'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [2.6, 2, -49.5, 'jog'],
        [4.6, 0.5, -49, 'block'],
        [6, 0, -49.5, 'idle'],
      ]),
    ],
    ball: B([
      [0, 26, -33],
      [1.4, 25, -38],
      [2.5, 24, -40],
      [3.6, 0, -41.5, 2.1],
      [4.7, 0.5, -43, 0.4],
      [6, 0, -52, 0.5],
    ]),
  },

  {
    id: 'atk-7',
    category: 'Attacking',
    group: 'Gegenpress and vertical transition',
    code: '7',
    title: 'Rondo to Attack (6v3 into Finishing)',
    style: 'Gegenpress, transition',
    area: '15m x 15m rondo 40m from goal, plus the attacking third',
    playerCount: '6 possession players, 3 defenders, 2 forwards, 1 GK',
    durationLabel: '12 min',
    description:
      'Circulate under pressure, then on the trigger switch mode instantly: forward within one touch, three players join the attack, three hold as rest defence.',
    setup:
      'Standard 6v3 rondo in the grid. Two forwards wait higher up the pitch. Goal and goalkeeper at the end.',
    keyPoints: [
      'The skill is the mental switch from circulating to penetrating.',
      'The trigger should come very early sometimes and very late others.',
      'One forward goes in behind, one comes short — never both in the same lane.',
      'Attack must finish within 8 seconds of the trigger.',
    ],
    simulationNote:
      'Mirrors the moment a team draws the press in then breaks through it. Vary the rondo size to change the urgency of the release.',
    view: 'half',
    duration: 12,
    zones: [{ x: 0, z: -12.5, w: 15, d: 15, label: 'Rondo grid' }],
    equipment: [
      { kind: 'disc', x: -7.5, z: -5 },
      { kind: 'disc', x: 7.5, z: -5 },
      { kind: 'disc', x: -7.5, z: -20 },
      { kind: 'disc', x: 7.5, z: -20 },
    ],
    players: [
      P('p1', 'P1', 'Possession player', 'attack', [
        [0, -7.5, -5, 'pass'],
        [6, -7.5, -6, 'idle'],
        [12, -7.5, -8, 'jog'],
      ]),
      P('p2', 'P2', 'Possession player', 'attack', [
        [0, 0, -4, 'receive'],
        [2, 0.5, -4.5, 'pass'],
        [7, 1, -8, 'jog'],
        [12, 2, -14, 'jog'],
      ]),
      P('p3', 'P3', 'Possession player', 'attack', [
        [0, 7.5, -5, 'idle'],
        [3, 7.5, -6, 'receive'],
        [4, 7, -7, 'pass'],
        [8, 9, -18, 'sprint'],
        [12, 12, -32, 'run'],
      ]),
      P('p4', 'P4', 'Possession player', 'attack', [
        [0, 7.5, -20, 'idle'],
        [4.6, 7, -20, 'receive'],
        [5.6, 6, -20.5, 'pass'],
        [12, 6, -22, 'idle'],
      ]),
      P('p5', 'P5', 'Possession player (trigger)', 'attack', [
        [0, 0, -21, 'scan'],
        [5.8, 0, -21, 'receive'],
        [6.6, 0, -21.5, 'pass'],
        [9, -2, -28, 'sprint'],
        [12, -5, -40, 'run'],
      ]),
      P('p6', 'P6', 'Rest defence', 'attack', [
        [0, -7.5, -20, 'idle'],
        [6, -7, -19, 'jog'],
        [12, -6, -17, 'idle'],
      ]),
      P('f1', 'F1', 'Forward (comes short)', 'attack', [
        [0, -3, -30, 'idle'],
        [6.4, -3, -30.5, 'jog'],
        [7.6, -2, -29, 'receive'],
        [8.4, -1.5, -29.5, 'layoff'],
        [12, 0, -36, 'jog'],
      ]),
      P('f2', 'F2', 'Forward (in behind)', 'attack', [
        [0, 4, -30, 'idle'],
        [6.6, 5, -31, 'sprint'],
        [8.8, 4, -38, 'receive'],
        [10.4, 2, -43, 'shoot'],
        [12, 1, -45, 'jog'],
      ]),
      P('r1', 'R1', 'Rondo defender', 'defense', [
        [0, -2, -9, 'press'],
        [2.5, 2, -8, 'press'],
        [5, -1, -16, 'press'],
        [8, 0, -26, 'sprint'],
        [12, 2, -38, 'run'],
      ]),
      P('r2', 'R2', 'Rondo defender', 'defense', [
        [0, 3, -14, 'press'],
        [3, -3, -13, 'press'],
        [6, 3, -18, 'press'],
        [9, 4, -30, 'sprint'],
        [12, 4, -41, 'block'],
      ]),
      P('r3', 'R3', 'Rondo defender', 'defense', [
        [0, -3, -17, 'press'],
        [3.5, 4, -11, 'press'],
        [7, 0, -19, 'press'],
        [10, -2, -33, 'sprint'],
        [12, -3, -40, 'run'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [9, 0.5, -49.5, 'jog'],
        [10.6, 2, -48.5, 'block'],
        [12, 2, -49, 'idle'],
      ]),
    ],
    ball: B([
      [0, -7.5, -5],
      [1.2, 0, -4.5],
      [2.6, 7.5, -5.5],
      [4.4, 7, -20],
      [5.6, 0, -21],
      [7.4, -2.2, -29],
      [8.6, 4, -38],
      [10.5, 2, -43],
      [12, 0.5, -52, 0.6],
    ]),
  },

  {
    id: 'atk-8',
    category: 'Attacking',
    group: 'Tiki-taka and positional play',
    code: '8',
    title: 'Breaking a Low Block (8v8 with Attacking Bias)',
    style: 'Positional play, tiki-taka',
    area: 'Halfway to goal, full width, plus 2 counter goals',
    playerCount: '8 attackers vs 8 defenders in a compact 5-3 shape',
    durationLabel: '20 min in blocks of 5',
    description:
      'Two switches of play before penetration: the first switch moves the block, the second creates the gap, then the fullback underlaps into the half-space and cuts back.',
    setup:
      'Defenders compact, roughly 25m between highest and deepest player. Attackers keep the ball permanently. Small counter goals on the halfway line.',
    keyPoints: [
      'Against a low block, width is the only thing that stretches the line horizontally.',
      'Fullbacks underlap into the half-space — the outside space is already covered.',
      'Aim for two switches before attempting penetration.',
      'Goals from a cutback, or within 5 seconds of a switch, are worth double.',
    ],
    simulationNote:
      'Have the defending team occasionally jump into a mid block or press for 10 seconds. Real low blocks are not passive for 90 minutes.',
    view: 'half',
    duration: 12,
    equipment: [
      { kind: 'mini-goal', x: -18, z: 0, rot: 180 },
      { kind: 'mini-goal', x: 18, z: 0, rot: 180 },
    ],
    players: [
      P('dm', 'DM', 'Deep midfielder', 'attack', [
        [0, 0, -14, 'receive'],
        [1.2, -1, -15, 'pass'],
        [4, 0, -16, 'scan'],
        [5.2, 0, -16.5, 'receive'],
        [6.2, 1, -17, 'pass'],
        [12, 2, -20, 'jog'],
      ]),
      P('lw', 'LW', 'Left winger', 'attack', [
        [0, -29, -22, 'idle'],
        [2.4, -29, -24, 'receive'],
        [3.6, -28, -26, 'dribble'],
        [4.6, -27, -27, 'pass'],
        [8, -26, -32, 'jog'],
        [12, -22, -40, 'run'],
      ]),
      P('cm', 'CM', 'Central midfielder', 'attack', [
        [0, -6, -24, 'idle'],
        [4.6, -4, -22, 'receive'],
        [5.4, -2, -21, 'pass'],
        [8, 2, -28, 'run'],
        [12, 4, -38, 'run'],
      ]),
      P('rw', 'RW', 'Right winger', 'attack', [
        [0, 29, -22, 'idle'],
        [6.8, 29, -25, 'receive'],
        [7.8, 28, -30, 'dribble'],
        [8.8, 27, -33, 'pass'],
        [12, 24, -40, 'run'],
      ]),
      P('rb', 'RB', 'Underlapping fullback', 'attack', [
        [0, 26, -12, 'idle'],
        [6.8, 24, -20, 'jog'],
        [9.4, 17, -34, 'sprint'],
        [10.6, 15, -42, 'receive'],
        [11.3, 14, -44, 'cross'],
        [12, 13, -45, 'jog'],
      ]),
      P('st', 'ST', 'Striker', 'attack', [
        [0, 0, -34, 'idle'],
        [6, 1, -35, 'hold'],
        [10, 3, -38, 'run'],
        [11.5, 1, -42, 'shoot'],
        [12, 0.5, -43.5, 'jog'],
      ]),
      P('rd1', 'RD', 'Rest defence', 'attack', [
        [0, -8, -6, 'idle'],
        [6, -6, -8, 'jog'],
        [12, -4, -10, 'idle'],
      ]),
      P('rd2', 'RD', 'Rest defence', 'attack', [
        [0, 8, -6, 'idle'],
        [6, 6, -8, 'jog'],
        [12, 5, -10, 'idle'],
      ]),
      P('b1', 'CB', 'Block — centre back', 'defense', [
        [0, -6, -40, 'idle'],
        [4, -9, -40, 'jog'],
        [8, -3, -40, 'jog'],
        [11, 3, -41, 'block'],
        [12, 3, -42, 'jog'],
      ]),
      P('b2', 'CB', 'Block — centre back', 'defense', [
        [0, 4, -41, 'idle'],
        [4, 0, -41, 'jog'],
        [8, 7, -41, 'jog'],
        [11.4, 9, -42, 'run'],
        [12, 8, -43, 'jog'],
      ]),
      P('b3', 'FB', 'Block — left back', 'defense', [
        [0, -16, -36, 'idle'],
        [3.6, -21, -33, 'press'],
        [7, -12, -36, 'run'],
        [12, -6, -38, 'jog'],
      ]),
      P('b4', 'FB', 'Block — right back', 'defense', [
        [0, 16, -36, 'idle'],
        [5, 12, -36, 'jog'],
        [8.4, 21, -33, 'press'],
        [11, 17, -39, 'run'],
        [12, 16, -41, 'jog'],
      ]),
      P('b5', 'MF', 'Block — midfield screen', 'defense', [
        [0, 0, -28, 'idle'],
        [3.4, -8, -27, 'press'],
        [6.4, 2, -27, 'run'],
        [9, 10, -28, 'press'],
        [12, 8, -33, 'jog'],
      ]),
      P('b6', 'MF', 'Block — midfield screen', 'defense', [
        [0, 8, -30, 'idle'],
        [4, 0, -30, 'jog'],
        [8, 6, -30, 'jog'],
        [11, 6, -36, 'run'],
        [12, 5, -38, 'jog'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [9, 2, -49.5, 'jog'],
        [11.6, 0.5, -49, 'block'],
        [12, 0.5, -49, 'idle'],
      ]),
    ],
    ball: B([
      [0, 0, -14],
      [1.2, -1, -15],
      [2.4, -29, -24],
      [3.6, -28, -26],
      [4.6, -4.5, -22],
      [5.3, 0, -16.5],
      [6.8, 29, -25],
      [7.8, 28, -30],
      [9.6, 16.5, -40],
      [10.7, 15, -42],
      [11.5, 1.5, -42],
      [12, 0, -52, 0.5],
    ]),
  },

  {
    id: 'atk-9',
    category: 'Attacking',
    group: 'Set pieces',
    code: '9',
    title: 'Attacking Corner Rehearsal',
    style: 'Set piece',
    area: 'Penalty area',
    playerCount: 'Full attacking unit, 6-8 defenders, 1 GK',
    durationLabel: '12 min · ~20 repetitions',
    description:
      'Inswinger to a curved run from deep, a blocker moving at the moment of delivery, a second wave on knockdowns and counter cover holding the halfway line.',
    setup:
      'Rehearse each routine at least 5 times consecutively so timing becomes automatic, then randomise.',
    keyPoints: [
      'Consistency of delivery zone matters more than variety.',
      'The blocker moves at the moment of delivery, not before.',
      'Around a third of set-piece goals come from second contact — the second wave is not a secondary role.',
      'Track first contact rate before goal conversion.',
    ],
    simulationNote:
      'Practise defending your own attacking corner immediately after — the counter from a cleared corner is one of the most dangerous transition moments in football.',
    view: 'box',
    duration: 6,
    players: [
      P('tk', 'TK', 'Taker', 'attack', [
        [0, 32, -50, 'idle'],
        [1.2, 33.4, -51.8, 'run'],
        [1.8, 33.8, -52.3, 'cross'],
        [6, 32, -50, 'jog'],
      ]),
      P('bl', 'BL', 'Blocker', 'attack', [
        [0, 3, -44, 'idle'],
        [1.8, 3, -44.5, 'hold'],
        [3, 0, -46, 'block'],
        [6, -1, -46.5, 'jog'],
      ]),
      P('mt', 'MT', 'Main target', 'attack', [
        [0, -1, -39, 'idle'],
        [1.8, 0, -40, 'jog'],
        [3.2, 3, -45.5, 'sprint'],
        [3.9, 2.5, -46.5, 'header'],
        [6, 1, -47, 'jog'],
      ]),
      P('sw1', 'SW', 'Second wave', 'attack', [
        [0, -6, -43, 'idle'],
        [2.4, -4, -44, 'jog'],
        [4.2, -2, -46.5, 'run'],
        [6, -1.5, -47.5, 'jog'],
      ]),
      P('sw2', 'SW', 'Second wave', 'attack', [
        [0, 8, -44, 'idle'],
        [2.6, 7, -46, 'jog'],
        [4.4, 5, -47.5, 'run'],
        [6, 5, -48, 'jog'],
      ]),
      P('ed', 'ED', 'Edge of box', 'attack', [
        [0, -1, -35, 'idle'],
        [3, -1, -36, 'idle'],
        [6, -1, -36.5, 'shoot'],
      ]),
      P('sc', 'SC', 'Short corner option', 'attack', [
        [0, 28, -48, 'idle'],
        [2, 27, -47, 'jog'],
        [6, 26, -46, 'idle'],
      ]),
      P('cc', 'CC', 'Counter cover', 'attack', [
        [0, -4, -2, 'idle'],
        [6, -3, -3, 'jog'],
      ]),
      P('d1', 'CB', 'Zonal defender', 'defense', [
        [0, 1, -46.5, 'idle'],
        [3, 2, -47, 'jockey'],
        [4, 4, -47.5, 'header'],
        [6, 3, -47.5, 'jog'],
      ]),
      P('d2', 'CB', 'Man marker', 'defense', [
        [0, -1, -40.5, 'idle'],
        [2, -0.5, -41, 'jockey'],
        [3.4, 2, -45, 'run'],
        [6, 2, -46, 'jog'],
      ]),
      P('d3', 'FB', 'Post defender', 'defense', [
        [0, -3.5, -51.5, 'idle'],
        [6, -3.5, -51.5, 'idle'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -51, 'idle'],
        [2.6, 1, -50, 'jog'],
        [4, 2, -49.5, 'block'],
        [6, 1, -50.5, 'idle'],
      ]),
    ],
    ball: B([
      [0, 33.8, -52.3],
      [1.9, 33.8, -52.3],
      [3.3, 2.5, -46, 3.3],
      [4.1, 2, -47, 1],
      [6, 0.5, -52, 0.8],
    ]),
  },

  {
    id: 'atk-10',
    category: 'Attacking',
    group: 'Wing play and direct crossing',
    code: '10',
    title: 'Wide Isolation 1v1 and 2v1',
    style: 'Wing play',
    area: '25m x 20m channel down one flank, plus the penalty area',
    playerCount: 'Winger, defender, supporting fullback, striker, 1 GK',
    durationLabel: '15 min · high recovery ratio',
    description:
      'Winger receives square to the defender, approaches at pace, slows at 3m to plant their feet, uses one feint and attacks the outside shoulder while the overlap occupies peripheral vision.',
    setup:
      'Winger receives on the touchline facing the defender with 20m of space ahead. Supporting fullback starts 10m behind.',
    keyPoints: [
      'The moment of decision is when the defender plants their weight — watch the feet, not the ball.',
      'One feint only, then commit. Multiple feints let cover arrive.',
      'Run the overlap on every repetition, even when the ball is not coming.',
      'Alternate outcomes: beat outside and cross, cut inside and shoot, use the overlap.',
    ],
    simulationNote:
      'Run some repetitions immediately after a 30m sprint to replicate late-game 1v1s.',
    view: 'half',
    duration: 8,
    zones: [{ x: 22, z: -30, w: 20, d: 25, label: 'Isolation channel' }],
    equipment: [
      { kind: 'pole', x: 12, z: -18 },
      { kind: 'pole', x: 32, z: -18 },
      { kind: 'pole', x: 12, z: -43 },
      { kind: 'pole', x: 32, z: -43 },
    ],
    players: [
      P('rw', 'RW', 'Winger', 'attack', [
        [0, 28, -20, 'receive'],
        [1.4, 27, -25, 'dribble'],
        [2.6, 26.5, -29, 'dribble'],
        [3.4, 25, -30, 'idle'],
        [4.6, 29, -35, 'sprint'],
        [6.4, 27, -44, 'dribble'],
        [7.1, 25, -45.5, 'cross'],
        [8, 24, -46.5, 'jog'],
      ]),
      P('d1', 'LB', 'Defender', 'defense', [
        [0, 28, -27, 'jockey'],
        [2.6, 27, -31, 'jockey'],
        [3.6, 26, -32, 'tackle'],
        [5.2, 25, -36, 'sprint'],
        [7, 24, -44, 'run'],
        [8, 23, -46, 'jog'],
      ]),
      P('rb', 'RB', 'Supporting fullback (overlap)', 'attack', [
        [0, 30, -12, 'idle'],
        [2, 31, -20, 'run'],
        [4.4, 32, -30, 'sprint'],
        [6.6, 31, -40, 'sprint'],
        [8, 29, -45, 'run'],
      ]),
      P('st', 'ST', 'Striker', 'attack', [
        [0, 4, -30, 'idle'],
        [3, 6, -34, 'jog'],
        [6, 9, -44, 'sprint'],
        [7.4, 3, -43, 'run'],
        [8, 1.5, -43.5, 'shoot'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [5, 3, -50, 'jog'],
        [7.2, 5, -49, 'jog'],
        [8, 2, -49.5, 'block'],
      ]),
    ],
    ball: B([
      [0, 28, -20],
      [1.4, 27, -25],
      [3.4, 25.5, -30],
      [4.8, 29, -35.5],
      [6.4, 27, -44],
      [7.3, 3.5, -43],
      [8, 0.5, -52, 0.6],
    ]),
  },

  {
    id: 'atk-11',
    category: 'Attacking',
    group: 'Direct play and target play',
    code: '11',
    title: 'Long Diagonal Switch',
    style: 'Direct play, wide progression',
    area: 'Full width, defensive third to attacking third',
    playerCount: 'Playmaker, both wingers, striker, 2 midfielders, 4 defenders, 1 GK',
    durationLabel: '12 min',
    description:
      'Deliberately overload one flank to pull the block across, then hit one flat diagonal into the space ahead of the hidden far winger, who starts their run on the playmaker’s second touch.',
    setup:
      'Four attacking players crowd one flank. The defending team is instructed to shift toward the ball — correct behaviour that creates the space to be exploited.',
    keyPoints: [
      'The switch must be one pass. No relaying through a third player.',
      'Aim into the space ahead of the far winger, roughly 10m in front, not at their feet.',
      'A driven ball at head height on a flat trajectory beats a high floated one — height gives the defence 2 seconds.',
      'Freeze the drill if the far winger has drifted inside.',
    ],
    simulationNote:
      'Add a pressing forward who chases the playmaker. Under pressure the switch becomes a technical test rather than a free pass.',
    view: 'full',
    duration: 10,
    players: [
      P('pm', 'PM', 'Deep playmaker', 'attack', [
        [0, 8, -6, 'receive'],
        [1.4, 6, -8, 'scan'],
        [2.2, 5, -9, 'pass'],
        [6, 2, -14, 'jog'],
        [10, 0, -20, 'jog'],
      ]),
      P('rw', 'RW', 'Ball-side winger (decoy)', 'attack', [
        [0, 27, -14, 'idle'],
        [2.4, 26, -16, 'idle'],
        [4.5, 20, -24, 'sprint'],
        [7.5, 10, -36, 'sprint'],
        [10, 4, -44, 'run'],
      ]),
      P('cm1', 'CM', 'Ball-side midfielder', 'attack', [
        [0, 18, -10, 'idle'],
        [2.4, 17, -13, 'jog'],
        [6, 12, -24, 'run'],
        [10, 6, -36, 'run'],
      ]),
      P('cm2', 'CM', 'Ball-side midfielder', 'attack', [
        [0, 14, -18, 'idle'],
        [3, 15, -20, 'jog'],
        [7, 9, -30, 'run'],
        [10, 5, -40, 'run'],
      ]),
      P('lw', 'LW', 'Far winger', 'attack', [
        [0, -29, -18, 'idle'],
        [2.2, -29, -19, 'scan'],
        [3.2, -28, -24, 'sprint'],
        [4.6, -27, -29, 'receive'],
        [6.4, -26, -37, 'dribble'],
        [7.6, -24, -43, 'cross'],
        [10, -23, -45, 'jog'],
      ]),
      P('st', 'ST', 'Striker', 'attack', [
        [0, 2, -26, 'idle'],
        [3.5, 0, -30, 'jog'],
        [6.5, -4, -38, 'run'],
        [8.4, -2, -43, 'shoot'],
        [10, -2, -45, 'jog'],
      ]),
      P('d1', 'FB', 'Ball-side fullback', 'defense', [
        [0, 22, -16, 'press'],
        [3, 20, -20, 'run'],
        [6, 12, -28, 'sprint'],
        [10, 4, -40, 'run'],
      ]),
      P('d2', 'CB', 'Shifted centre back', 'defense', [
        [0, 10, -22, 'idle'],
        [2.4, 12, -24, 'jog'],
        [5, 2, -30, 'sprint'],
        [8.6, -1, -41, 'block'],
        [10, -1, -43, 'jog'],
      ]),
      P('d3', 'CB', 'Shifted centre back', 'defense', [
        [0, 2, -26, 'idle'],
        [2.4, 5, -27, 'jog'],
        [5.4, -6, -32, 'sprint'],
        [9, -5, -42, 'run'],
        [10, -5, -44, 'jog'],
      ]),
      P('d4', 'FB', 'Far fullback', 'defense', [
        [0, -12, -24, 'idle'],
        [2.4, -8, -26, 'jog'],
        [4.6, -20, -30, 'sprint'],
        [7.6, -22, -41, 'press'],
        [10, -20, -44, 'jog'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [6, -1, -49.5, 'jog'],
        [8.6, -2, -48.5, 'block'],
        [10, -2, -49, 'idle'],
      ]),
    ],
    ball: B([
      [0, 8, -6],
      [1.4, 6, -8],
      [2.3, 5, -9],
      [4.4, -27, -28.5, 1.9],
      [6.4, -26, -37],
      [7.7, -24, -43],
      [8.5, -2, -43],
      [10, 0, -52, 0.7],
    ]),
  },

  {
    id: 'atk-12',
    category: 'Attacking',
    group: 'Direct play and target play',
    code: '12',
    title: 'Target Man Hold-up and Lay-off',
    style: 'Direct play, target play',
    area: '30m x 25m into a full goal',
    playerCount: 'Server, target striker, 2 midfield runners, 1-2 defenders, 1 GK',
    durationLabel: '12 min · rotate the striker every 4 reps',
    description:
      'Establish contact before the ball arrives, hold for a minimum of two seconds with a wide base, then lay off along the ground into the near runner’s path while the far runner attacks in behind.',
    setup:
      'Server on the halfway line. Striker 25 to 30m from goal with a defender behind. Two midfielders 15m behind the striker.',
    keyPoints: [
      'Hold the ball for a minimum of 2 seconds — that is what buys the team time to advance.',
      'Wide base, knees bent, arm across for separation without pushing.',
      'Lay off with the outside or sole, along the ground, into the path — not to the feet.',
      'Do not turn. Beating the defender is a bonus, not the objective.',
    ],
    simulationNote:
      'Have the striker sprint 20m before each repetition. Hold-up play in a match usually happens when the striker has already been running.',
    view: 'half',
    duration: 8,
    players: [
      P('sv', 'SV', 'Server', 'attack', [
        [0, 0, -8, 'scan'],
        [1, 0, -9, 'pass'],
        [8, 0, -11, 'idle'],
      ]),
      P('ts', 'ST', 'Target striker', 'attack', [
        [0, 0, -26, 'idle'],
        [1.4, 0, -27, 'hold'],
        [3, 0.3, -27.5, 'hold'],
        [4.2, -0.5, -28, 'layoff'],
        [6, 2, -33, 'jog'],
        [8, 3, -37, 'jog'],
      ]),
      P('nr', 'CM', 'Near runner', 'attack', [
        [0, -6, -14, 'idle'],
        [2, -5, -20, 'run'],
        [4, -3, -27, 'sprint'],
        [4.9, -2, -30, 'receive'],
        [6, -1, -34, 'dribble'],
        [6.9, -0.5, -37, 'shoot'],
        [8, 0, -39, 'jog'],
      ]),
      P('fr', 'CM', 'Far runner', 'attack', [
        [0, 6, -14, 'idle'],
        [2.4, 6, -22, 'run'],
        [5, 6, -33, 'sprint'],
        [7.4, 4, -42, 'run'],
        [8, 3, -44, 'jog'],
      ]),
      P('d1', 'CB', 'Marking defender', 'defense', [
        [0, 0.5, -29, 'idle'],
        [1.8, 0.4, -28.5, 'press'],
        [4.2, -0.3, -29, 'tackle'],
        [6, -1, -32, 'sprint'],
        [8, -1, -37, 'run'],
      ]),
      P('d2', 'CB', 'Second defender', 'defense', [
        [0, 4, -32, 'idle'],
        [3, 3, -31, 'jockey'],
        [5.4, 1, -33, 'run'],
        [7, 0, -37, 'block'],
        [8, 0, -39, 'jog'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [5, 0, -49.5, 'jog'],
        [7, 0, -48.5, 'block'],
        [8, 0, -49, 'idle'],
      ]),
    ],
    ball: B([
      [0, 0, -9],
      [1.9, 0, -26.6],
      [3.6, 0.3, -27.4],
      [4.4, -2, -30],
      [6, -1, -34],
      [7, -0.5, -37],
      [8, 0.5, -52, 0.9],
    ]),
  },

  {
    id: 'atk-13',
    category: 'Attacking',
    group: 'Gegenpress and vertical transition',
    code: '13',
    title: 'Counter-press After Loss',
    style: 'Gegenpress',
    area: '40m x 40m in the attacking third, full goal + 2 small goals',
    playerCount: '6 attackers, 6 defenders, 1 GK',
    durationLabel: '15 min in 90 second blocks',
    description:
      'The nearest player closes within two seconds and shows inside, the next two block the first and second forward lanes, the line pushes up 10m and the keeper sweeps.',
    setup:
      'The attacking team is in possession in the final third. The coach calls a trigger, or the ball is deliberately turned over, and the counter-press begins immediately.',
    keyPoints: [
      'Close within 2 seconds — sprint, do not jog. Force a rushed decision before tackling.',
      'Second and third pressers mark passing lanes, not opponents.',
      'Push the line up 10m immediately; compressing space is what makes the press work.',
      'If recovery does not happen within ~6 seconds, drop into shape. Practise the decision explicitly.',
    ],
    simulationNote:
      'Alternate blocks between "always press" and "press for 6 seconds then drop", so players learn the decision rather than a single behaviour.',
    view: 'attacking-third',
    duration: 8,
    zones: [{ x: 0, z: -32, w: 40, d: 40, label: 'Counter-press zone' }],
    equipment: [
      { kind: 'mini-goal', x: -16, z: -12, rot: 180 },
      { kind: 'mini-goal', x: 16, z: -12, rot: 180 },
    ],
    players: [
      P('a1', 'P1', 'Nearest presser', 'attack', [
        [0, 4, -32, 'idle'],
        [0.6, 4, -32.5, 'press'],
        [2, 0.5, -30, 'press'],
        [3.4, -1, -28.5, 'tackle'],
        [5, 1, -32, 'run'],
        [8, 3, -38, 'run'],
      ]),
      P('a2', 'P2', 'Second presser (lane)', 'attack', [
        [0, -6, -34, 'idle'],
        [1.6, -6, -30, 'sprint'],
        [3.4, -5, -26, 'block'],
        [5.4, -4, -31, 'run'],
        [8, -3, -40, 'run'],
      ]),
      P('a3', 'P3', 'Third presser (lane)', 'attack', [
        [0, 10, -34, 'idle'],
        [1.8, 8, -29, 'sprint'],
        [3.6, 6, -26, 'block'],
        [8, 7, -34, 'run'],
      ]),
      P('a4', 'P4', 'Line pushes up', 'attack', [
        [0, -12, -24, 'idle'],
        [2.4, -12, -18, 'run'],
        [5, -10, -20, 'jog'],
        [8, -8, -26, 'jog'],
      ]),
      P('a5', 'P5', 'Line pushes up', 'attack', [
        [0, 12, -22, 'idle'],
        [2.4, 12, -16, 'run'],
        [8, 10, -24, 'jog'],
      ]),
      P('a6', 'P6', 'Spare defender', 'attack', [
        [0, 0, -18, 'idle'],
        [3, 0, -14, 'jog'],
        [8, 0, -18, 'jog'],
      ]),
      P('b1', 'B1', 'New ball carrier', 'defense', [
        [0, 2, -30, 'receive'],
        [1.6, 0, -28, 'dribble'],
        [3.2, -1.5, -27.5, 'pass'],
        [6, -3, -24, 'jog'],
        [8, -4, -22, 'jog'],
      ]),
      P('b2', 'B2', 'Outlet', 'defense', [
        [0, -10, -26, 'idle'],
        [3.4, -9, -24, 'receive'],
        [4.6, -8, -22, 'pass'],
        [8, -8, -20, 'jog'],
      ]),
      P('b3', 'B3', 'Long option', 'defense', [
        [0, 6, -18, 'idle'],
        [4, 4, -16, 'jog'],
        [6, 2, -14, 'receive'],
        [8, 0, -12, 'run'],
      ]),
      P('b4', 'B4', 'Support', 'defense', [
        [0, 14, -28, 'idle'],
        [4, 12, -22, 'run'],
        [8, 10, -18, 'jog'],
      ]),
      P('gk', 'GK', 'Sweeper keeper', 'gk', [
        [0, 0, -44, 'idle'],
        [3, 0, -41, 'jog'],
        [6, 0, -43, 'jog'],
        [8, 0, -45, 'idle'],
      ]),
    ],
    ball: B([
      [0, 2, -30],
      [1.6, 0, -28],
      [3.3, -9, -24],
      [4.7, -8, -22],
      [5.9, 2, -14],
      [8, 0, -12],
    ]),
  },

  {
    id: 'atk-14',
    category: 'Attacking',
    group: 'Total football and rotation',
    code: '14',
    title: 'Rotational Overload in the Half-space',
    style: 'Total football, fluid rotation',
    area: 'One flank plus the half-space, 30m x 30m, full goal',
    playerCount: 'Fullback, winger, inside midfielder, 2-3 defenders, 1 GK',
    durationLabel: '15 min',
    description:
      'Whoever has the ball stays; the other two rotate zones. Winger tucks into the half-space, fullback overlaps into the wide lane, inside midfielder takes whichever zone is empty.',
    setup:
      'Three zones marked on one side: wide lane, half-space, central lane. Three attackers, three defenders.',
    keyPoints: [
      'No two attackers may occupy the same zone at any time.',
      'The overlap must be at full speed — a slow rotation is just a positional swap.',
      'Every rotation should create either a free receiver or a mismatch.',
      'Watch defenders’ heads: if a defender turns between two attackers, the rotation is working.',
    ],
    simulationNote:
      'Rotate personnel so every player learns all three roles. In fluid systems the role belongs to the space, not the shirt number.',
    view: 'half',
    duration: 10,
    zones: [
      { x: 26, z: -30, w: 14, d: 30, label: 'Wide lane', color: '#7fd1ff' },
      { x: 13, z: -30, w: 12, d: 30, label: 'Half-space', color: '#ffd84d', fill: true },
      { x: 2, z: -30, w: 10, d: 30, label: 'Central lane', color: '#7fd1ff' },
    ],
    players: [
      P('rw', 'RW', 'Winger', 'attack', [
        [0, 27, -22, 'receive'],
        [1.4, 26, -25, 'dribble'],
        [2.4, 25, -26, 'pass'],
        [4.4, 16, -30, 'sprint'],
        [6, 13, -33, 'receive'],
        [7.2, 11, -36, 'pass'],
        [10, 8, -42, 'run'],
      ]),
      P('rb', 'RB', 'Fullback', 'attack', [
        [0, 20, -14, 'idle'],
        [2.4, 22, -20, 'run'],
        [4, 27, -30, 'sprint'],
        [5.6, 28, -38, 'receive'],
        [7.6, 26, -44, 'dribble'],
        [8.4, 24, -45.5, 'cross'],
        [10, 23, -46, 'jog'],
      ]),
      P('im', 'IM', 'Inside midfielder', 'attack', [
        [0, 13, -18, 'idle'],
        [2.6, 14, -22, 'jog'],
        [5, 20, -18, 'run'],
        [7.4, 14, -30, 'sprint'],
        [9, 6, -41, 'sprint'],
        [10, 3, -43.5, 'shoot'],
      ]),
      P('d1', 'LB', 'Marking fullback', 'defense', [
        [0, 27, -27, 'jockey'],
        [2.6, 25, -29, 'press'],
        [4.6, 20, -32, 'run'],
        [6.4, 26, -36, 'sprint'],
        [8.4, 26, -43, 'press'],
        [10, 24, -46, 'jog'],
      ]),
      P('d2', 'CB', 'Covering defender', 'defense', [
        [0, 15, -32, 'idle'],
        [3, 16, -31, 'jockey'],
        [6, 12, -35, 'press'],
        [8, 8, -40, 'run'],
        [10, 4, -44, 'block'],
      ]),
      P('d3', 'CB', 'Spare defender', 'defense', [
        [0, 5, -36, 'idle'],
        [4, 7, -37, 'jog'],
        [8, 3, -42, 'run'],
        [10, 1, -45, 'jog'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [6, 2, -50, 'jog'],
        [8.6, 4, -49, 'jog'],
        [10, 1.5, -49.5, 'block'],
      ]),
    ],
    ball: B([
      [0, 27, -22],
      [1.4, 26, -25],
      [2.5, 25, -26],
      [4.2, 27.5, -34],
      [5.7, 28, -38],
      [7.6, 26, -44],
      [8.6, 4, -43],
      [10, 0.5, -52, 0.6],
    ]),
  },

  {
    id: 'atk-15',
    category: 'Attacking',
    group: 'Tiki-taka and positional play',
    code: '15',
    title: 'False Nine Drop and Vacated Space',
    style: 'Tiki-taka, positional play',
    area: 'Halfway line to goal, full width',
    playerCount: 'False nine, 2 wide forwards, CM, 2 CBs, 2 FBs, 1 DM, 1 GK',
    durationLabel: '18 min',
    description:
      'The false nine establishes as a striker, drops between the lines, and the ball-side wide forward attacks the space the following centre back left — starting the run as the nine receives, not after.',
    setup:
      'Attackers set up with a false nine and two wide forwards. Two centre backs must decide whether to follow the dropping forward.',
    keyPoints: [
      'The drop only works if the defence first believes the nine will stay on the shoulder.',
      'The wide forward’s run is inside-diagonal, into the gap between centre back and fullback.',
      'Far-side wide forward holds the back post — two runners into the same gap cancel each other.',
      'The false nine creates a dilemma, not a solution. Read which dilemma the defence chose.',
    ],
    simulationNote:
      'Play a full 11v11 phase after this drill with the false nine instruction in place, so the mechanism is tested under real midfield pressure.',
    view: 'half',
    duration: 10,
    players: [
      P('f9', 'F9', 'False nine', 'attack', [
        [0, 0, -34, 'idle'],
        [1.4, 0, -32, 'jog'],
        [2.8, -1, -27, 'scan'],
        [4, -1, -26, 'receive'],
        [5, 0, -27, 'pass'],
        [7.5, 1, -33, 'run'],
        [10, 2, -40, 'jog'],
      ]),
      P('rwf', 'RWF', 'Ball-side wide forward', 'attack', [
        [0, 24, -30, 'idle'],
        [3.8, 22, -31, 'jog'],
        [5.2, 14, -36, 'sprint'],
        [6.6, 7, -41, 'receive'],
        [7.8, 4, -44, 'shoot'],
        [10, 3, -46, 'jog'],
      ]),
      P('lwf', 'LWF', 'Far-side wide forward', 'attack', [
        [0, -24, -30, 'idle'],
        [4, -24, -33, 'jog'],
        [7, -14, -44, 'sprint'],
        [10, -8, -47, 'run'],
      ]),
      P('cm', 'CM', 'Central midfielder', 'attack', [
        [0, -7, -20, 'idle'],
        [2.8, -7, -22, 'jog'],
        [5, -6, -24, 'scan'],
        [8, -4, -30, 'jog'],
        [10, -3, -34, 'jog'],
      ]),
      P('dp', 'DM', 'Feeding midfielder', 'attack', [
        [0, 4, -16, 'receive'],
        [3, 3, -19, 'scan'],
        [3.8, 2, -20, 'pass'],
        [7, 3, -24, 'jog'],
        [10, 3, -28, 'jog'],
      ]),
      P('cb1', 'CB', 'Following centre back', 'defense', [
        [0, 1, -37, 'idle'],
        [2.6, 0.5, -34, 'jockey'],
        [4, -0.5, -29, 'press'],
        [6, 0, -31, 'sprint'],
        [8, 3, -38, 'run'],
        [10, 4, -42, 'jog'],
      ]),
      P('cb2', 'CB', 'Holding centre back', 'defense', [
        [0, -6, -38, 'idle'],
        [4, -5, -38, 'jog'],
        [6.4, 0, -40, 'sprint'],
        [8, 5, -43, 'block'],
        [10, 5, -45, 'jog'],
      ]),
      P('fb1', 'FB', 'Right back', 'defense', [
        [0, 18, -35, 'idle'],
        [3.8, 17, -35, 'jockey'],
        [5.6, 13, -38, 'run'],
        [8, 8, -43, 'run'],
        [10, 7, -45, 'jog'],
      ]),
      P('fb2', 'FB', 'Left back', 'defense', [
        [0, -18, -35, 'idle'],
        [4, -14, -37, 'jog'],
        [7.4, -12, -43, 'run'],
        [10, -9, -46, 'jog'],
      ]),
      P('dmd', 'DM', 'Covering DM', 'defense', [
        [0, -2, -24, 'idle'],
        [3.4, -1, -25, 'press'],
        [5.4, 0, -28, 'run'],
        [10, 1, -34, 'jog'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [6, 1, -49.5, 'jog'],
        [7.9, 3, -48.5, 'block'],
        [10, 2, -49, 'idle'],
      ]),
    ],
    ball: B([
      [0, 4, -16],
      [3.8, -1, -26],
      [4.6, -1, -26.5],
      [5.2, 0, -27],
      [6.5, 7, -41],
      [7.9, 4, -44],
      [10, 0.5, -52, 0.7],
    ]),
  },
]
