import { ballPath as B, player as P, type Drill } from '../types'

/**
 * Defending Situation Drills — 7 drills from the defending manual.
 * Attacking direction is toward the goal at z = -52.5, so the defending
 * team is protecting that goal in every drill.
 */
export const DEFENDING: Drill[] = [
  {
    id: 'def-1',
    category: 'Defending',
    group: 'Individual and 1v1 defending',
    code: '1',
    title: '1v1 Isolation Defending',
    style: 'Individual containment, delay-and-jockey defending',
    area: '10m x 10m grid',
    playerCount: '1 attacker, 1 defender',
    durationLabel: '10 min · 6s per rep · 30s recovery',
    description:
      'Show stance, jockey backward at matching speed at roughly one arm’s length, and commit only when the attacker’s touch is heavy.',
    setup:
      'Attacker starts with the ball at one end of the grid. A mini-goal or the opposite endline is the target. Defender starts central, facing the attacker.',
    keyPoints: [
      'The defender’s first job is to slow the attacker down, not win the ball immediately.',
      'Crossing the feet while jockeying is the most common cause of being beaten.',
      'Keep the hips square to the attacker’s body, not to the ball.',
      'Reward delays that let a covering defender arrive, even if the ball is not won.',
    ],
    simulationNote:
      'Real 1v1s rarely start with the defender set. Serve the ball while the defender is jogging back into position, so they must get into shape under time pressure.',
    view: 'grid',
    duration: 6,
    zones: [{ x: 0, z: -25, w: 10, d: 10, label: '10m x 10m' }],
    equipment: [
      { kind: 'cone', x: -5, z: -20 },
      { kind: 'cone', x: 5, z: -20 },
      { kind: 'cone', x: -5, z: -30 },
      { kind: 'cone', x: 5, z: -30 },
      { kind: 'mini-goal', x: 0, z: -30.5 },
    ],
    players: [
      P('atk', 'ATT', 'Attacker', 'attack', [
        [0, 0, -20, 'receive'],
        [1.2, -1, -22, 'dribble'],
        [2.4, -2.5, -23.5, 'dribble'],
        [3.2, -1, -24, 'dribble'],
        [4.2, 2, -26, 'dribble'],
        [5.2, 3, -29, 'shoot'],
        [6, 3, -30, 'jog'],
      ]),
      P('def', 'DEF', 'Defender', 'defense', [
        [0, 0, -25, 'jockey'],
        [1.2, -0.6, -24.2, 'jockey'],
        [2.4, -2, -25.4, 'jockey'],
        [3.2, -1, -26, 'jockey'],
        [4.4, 1.6, -27.6, 'jockey'],
        [5.3, 2.6, -29.4, 'tackle'],
        [6, 2.8, -30, 'idle'],
      ]),
    ],
    ball: B([
      [0, 0, -20],
      [1.2, -1, -22],
      [2.4, -2.5, -23.5],
      [3.2, -1, -24],
      [4.2, 2, -26],
      [5.3, 3, -29],
      [6, 2, -31, 0.3],
    ]),
  },

  {
    id: 'def-2',
    category: 'Defending',
    group: 'Pressure and cover',
    code: '2',
    title: '2v1 Defending with Cover',
    style: 'Pressure-cover relationship, delay-and-support defending',
    area: '15m x 20m grid',
    playerCount: '2 attackers, 1 first defender, 1 cover defender',
    durationLabel: '12 min · 8s per rep · 40s recovery',
    description:
      'The first defender shows the carrier toward the cover defender’s zone; the cover defender recovers onto a diagonal angle behind and slightly inside, reading the pass lane rather than the ball.',
    setup:
      'Two attackers start at one end with the ball. First defender central. Cover defender starts 5m behind, recovering into shape as the rep begins.',
    keyPoints: [
      'Force play to one side — the touchline or the weaker foot — rather than winning the ball outright.',
      'The cover defender arriving square instead of diagonal allows a simple pass through the middle.',
      'Constant communication: "show left", "show right".',
      'Reward interceptions and blocks equally with winning the ball.',
    ],
    simulationNote:
      'Vary the cover defender’s starting position between reps — sometimes level, sometimes deep. In matches the cover angle is rarely the same twice.',
    view: 'grid',
    duration: 8,
    zones: [{ x: 0, z: -25, w: 15, d: 20, label: '15m x 20m' }],
    equipment: [
      { kind: 'cone', x: -7.5, z: -15 },
      { kind: 'cone', x: 7.5, z: -15 },
      { kind: 'cone', x: -7.5, z: -35 },
      { kind: 'cone', x: 7.5, z: -35 },
      { kind: 'mini-goal', x: 0, z: -35.5 },
    ],
    players: [
      P('a1', 'A1', 'Ball carrier', 'attack', [
        [0, -3, -16, 'dribble'],
        [2, -4.5, -21, 'dribble'],
        [3.6, -5.5, -25, 'dribble'],
        [4.6, -5, -27, 'pass'],
        [7, -2, -31, 'run'],
        [8, -1, -33, 'jog'],
      ]),
      P('a2', 'A2', 'Second attacker', 'attack', [
        [0, 5, -17, 'idle'],
        [2.4, 5.5, -22, 'run'],
        [4.6, 5, -27, 'jog'],
        [5.6, 4, -29, 'receive'],
        [6.6, 3, -31, 'block'],
        [8, 3, -32, 'idle'],
      ]),
      P('d1', 'D1', 'First defender', 'defense', [
        [0, -1, -22, 'jockey'],
        [2, -2.5, -24, 'jockey'],
        [3.6, -3.6, -27, 'jockey'],
        [4.8, -3.4, -28.5, 'press'],
        [6.6, -0.5, -30.5, 'run'],
        [8, 0, -32, 'jog'],
      ]),
      P('d2', 'D2', 'Cover defender', 'defense', [
        [0, 2, -28, 'sprint'],
        [2.2, 1, -26.5, 'jockey'],
        [4, 0.5, -27.5, 'jockey'],
        [5.4, 2.5, -28.8, 'press'],
        [6.4, 3.4, -30.2, 'block'],
        [8, 3, -31.5, 'idle'],
      ]),
    ],
    ball: B([
      [0, -3, -16],
      [2, -4.5, -21],
      [3.6, -5.5, -25],
      [4.7, -5, -27],
      [5.6, 4, -29],
      [6.6, 3.2, -30.4],
      [8, 1, -27],
    ]),
  },

  {
    id: 'def-3',
    category: 'Defending',
    group: 'Zonal and block defending',
    code: '3',
    title: 'Zonal Defending Shape (4-4-2 Block Drill)',
    style: 'Zonal marking, unit compactness, coordinated shifting',
    area: 'Half pitch',
    playerCount: '8 defenders in a 4-4-2, 6-8 attackers circulating',
    durationLabel: '20 min in blocks of 5',
    description:
      'The four lines shift together as the ball is switched. The weak-side fullback tucks in, the midfield line stays within 10m of each other, and the front two curve their press to cut the pass back inside.',
    setup:
      'Defenders organise in a 4-4-2 without goalkeepers initially. Attackers circulate the ball across the width from outside the block.',
    keyPoints: [
      'Maintain roughly 25 to 30m of vertical distance between backline and front two.',
      'Own a zone, not a player. Track the ball’s position, not an individual.',
      'No midfielder more than 10m from the teammate beside them.',
      'Watch for one line arriving late to a shift — that is where the gap appears.',
    ],
    simulationNote:
      'Rotate which side the ball starts on and vary the switch tempo. Occasionally play a fast diagonal to test whether the block can stay connected.',
    view: 'half',
    duration: 12,
    players: [
      // back four — shift right, then back left on the switch
      P('lb', 'LB', 'Left back', 'defense', [
        [0, -14, -40, 'idle'],
        [3, -6, -39, 'jog'],
        [6, -2, -38, 'jog'],
        [9, -12, -39, 'run'],
        [12, -18, -40, 'jog'],
      ]),
      P('lcb', 'LCB', 'Left centre back', 'defense', [
        [0, -5, -41, 'idle'],
        [3, 3, -40, 'jog'],
        [6, 7, -39, 'jog'],
        [9, -3, -40, 'run'],
        [12, -8, -41, 'jog'],
      ]),
      P('rcb', 'RCB', 'Right centre back', 'defense', [
        [0, 5, -41, 'idle'],
        [3, 13, -40, 'jog'],
        [6, 17, -39, 'jog'],
        [9, 7, -40, 'run'],
        [12, 2, -41, 'jog'],
      ]),
      P('rb', 'RB', 'Right back', 'defense', [
        [0, 15, -40, 'idle'],
        [3, 23, -39, 'jog'],
        [6, 26, -38, 'jog'],
        [9, 17, -39, 'run'],
        [12, 12, -40, 'jog'],
      ]),
      // midfield four
      P('lm', 'LM', 'Left midfielder', 'defense', [
        [0, -18, -28, 'idle'],
        [3, -10, -27, 'jog'],
        [6, -6, -26, 'jog'],
        [9, -16, -27, 'sprint'],
        [12, -23, -28, 'run'],
      ]),
      P('lcm', 'LCM', 'Left central midfielder', 'defense', [
        [0, -7, -28, 'idle'],
        [3, 1, -27, 'jog'],
        [6, 5, -26, 'jog'],
        [9, -5, -27, 'run'],
        [12, -11, -28, 'run'],
      ]),
      P('rcm', 'RCM', 'Right central midfielder', 'defense', [
        [0, 4, -28, 'idle'],
        [3, 12, -27, 'jog'],
        [6, 16, -26, 'press'],
        [9, 6, -27, 'run'],
        [12, 0, -28, 'run'],
      ]),
      P('rm', 'RM', 'Right midfielder', 'defense', [
        [0, 15, -28, 'idle'],
        [3, 23, -27, 'press'],
        [6, 27, -26, 'press'],
        [9, 17, -27, 'run'],
        [12, 11, -28, 'run'],
      ]),
      // front two
      P('st1', 'ST', 'Striker (curved press)', 'defense', [
        [0, -4, -14, 'idle'],
        [3, 4, -13, 'press'],
        [6, 9, -12, 'press'],
        [9, -2, -13, 'run'],
        [12, -8, -14, 'run'],
      ]),
      P('st2', 'ST', 'Striker (screen)', 'defense', [
        [0, 6, -14, 'idle'],
        [3, 14, -13, 'jog'],
        [6, 18, -12, 'jog'],
        [9, 8, -13, 'run'],
        [12, 2, -14, 'run'],
      ]),
      // attackers circulating outside the block
      P('c1', 'C1', 'Circulating attacker', 'attack', [
        [0, -26, -8, 'pass'],
        [4, -25, -9, 'idle'],
        [8, -26, -9, 'receive'],
        [12, -27, -10, 'idle'],
      ]),
      P('c2', 'C2', 'Circulating attacker', 'attack', [
        [0, -6, -6, 'idle'],
        [1.6, -5, -7, 'receive'],
        [2.6, -3, -7, 'pass'],
        [8, -4, -8, 'jog'],
        [12, -6, -8, 'idle'],
      ]),
      P('c3', 'C3', 'Circulating attacker', 'attack', [
        [0, 20, -8, 'idle'],
        [4.2, 22, -9, 'receive'],
        [5.4, 24, -10, 'dribble'],
        [7, 25, -12, 'pass'],
        [12, 24, -12, 'idle'],
      ]),
      P('c4', 'C4', 'Circulating attacker', 'attack', [
        [0, 8, -4, 'idle'],
        [3, 10, -5, 'jog'],
        [7, 8, -5, 'jog'],
        [12, 6, -6, 'idle'],
      ]),
    ],
    ball: B([
      [0, -26, -8],
      [1.5, -5, -7],
      [2.6, -3, -7],
      [4.2, 22, -9],
      [5.4, 24, -10],
      [7.1, 25, -12],
      [8.4, -26, -9, 2.4],
      [12, -27, -10],
    ]),
  },

  {
    id: 'def-4',
    category: 'Defending',
    group: 'High press and trigger defending',
    code: '4',
    title: 'Pressing Trap (Trigger-to-Press)',
    style: 'Coordinated high press, trap-and-trigger defending',
    area: 'Half pitch, full width, with a marked trap zone near one touchline',
    playerCount: '6 defenders, 5 attackers',
    durationLabel: '15 min in blocks of 5',
    description:
      'The front line blocks the switch and shows build-up into the wide trap zone. The moment the trigger appears — a pass into the trap — the nearest three press simultaneously and the midfielders close the out-ball behind.',
    setup:
      'Attacking team builds from the back across full width. Defending team leaves the touchline area open as the trap zone while blocking the switch of play.',
    keyPoints: [
      'Cutting the switching lane is the most important individual job in the drill.',
      'A press started by only one player is easily played through — 2 to 3 press together.',
      'Patience before the trigger matters as much as speed after it.',
      'If the ball escapes before the press connects, reset into base shape rather than chase.',
    ],
    simulationNote:
      'Vary which trigger appears most often so players cannot wait for the same cue. Occasionally have the attackers bypass the trap with a long ball.',
    view: 'half',
    duration: 10,
    zones: [
      { x: 25, z: -14, w: 18, d: 24, label: 'Trap zone', color: '#ff6b5a', fill: true },
    ],
    players: [
      P('f1', 'F1', 'Front line (blocks switch)', 'defense', [
        [0, -4, -14, 'jockey'],
        [2.4, 2, -13, 'jockey'],
        [4.2, 8, -13, 'press'],
        [6, 16, -14, 'sprint'],
        [7.4, 21, -15, 'press'],
        [10, 22, -17, 'jog'],
      ]),
      P('f2', 'F2', 'Front line', 'defense', [
        [0, 6, -14, 'jockey'],
        [3, 10, -13, 'jockey'],
        [6, 14, -12, 'jog'],
        [8, 20, -10, 'press'],
        [10, 21, -12, 'jog'],
      ]),
      P('m1', 'M1', 'Pressing midfielder', 'defense', [
        [0, 12, -24, 'idle'],
        [4, 16, -22, 'jog'],
        [6.2, 22, -20, 'sprint'],
        [7.6, 26, -17, 'press'],
        [10, 25, -19, 'jog'],
      ]),
      P('m2', 'M2', 'Lane-closing midfielder', 'defense', [
        [0, 0, -24, 'idle'],
        [4, 6, -23, 'jog'],
        [6.4, 14, -21, 'sprint'],
        [8, 18, -21, 'block'],
        [10, 17, -22, 'jog'],
      ]),
      P('m3', 'M3', 'Balancing midfielder', 'defense', [
        [0, -12, -24, 'idle'],
        [4, -6, -23, 'jog'],
        [7, 2, -22, 'run'],
        [10, 5, -23, 'jog'],
      ]),
      P('d1', 'D1', 'Backline cover', 'defense', [
        [0, 4, -34, 'idle'],
        [4, 9, -33, 'jog'],
        [7, 16, -31, 'run'],
        [10, 18, -32, 'jog'],
      ]),
      P('a1', 'A1', 'Building centre back', 'attack', [
        [0, -8, -6, 'receive'],
        [1.6, -5, -6, 'dribble'],
        [2.6, -3, -6, 'pass'],
        [6, -4, -7, 'jog'],
        [10, -6, -8, 'idle'],
      ]),
      P('a2', 'A2', 'Building centre back', 'attack', [
        [0, 6, -5, 'idle'],
        [3, 7, -6, 'receive'],
        [4.2, 9, -7, 'scan'],
        [5.2, 11, -8, 'pass'],
        [10, 10, -9, 'idle'],
      ]),
      P('a3', 'A3', 'Fullback (trap zone)', 'attack', [
        [0, 26, -10, 'idle'],
        [4, 26, -12, 'jog'],
        [6.4, 26, -14, 'receive'],
        [7.8, 27, -16, 'hold'],
        [8.8, 28, -18, 'pass'],
        [10, 28, -20, 'jog'],
      ]),
      P('a4', 'A4', 'Winger (trapped)', 'attack', [
        [0, 30, -20, 'idle'],
        [6, 30, -22, 'jog'],
        [9, 30, -24, 'receive'],
        [10, 30, -26, 'block'],
      ]),
      P('a5', 'A5', 'Far-side switch option (blocked)', 'attack', [
        [0, -26, -16, 'idle'],
        [5, -27, -18, 'jog'],
        [10, -27, -20, 'idle'],
      ]),
    ],
    ball: B([
      [0, -8, -6],
      [1.6, -5, -6],
      [2.8, 7, -6],
      [4.2, 9, -7],
      [6.2, 26, -14],
      [8, 27, -16],
      [9, 30, -24],
      [10, 28, -26],
    ]),
  },

  {
    id: 'def-5',
    category: 'Defending',
    group: 'Counter-press and transition defending',
    code: '5',
    title: 'Defensive Transition (Counter-Press / Gegenpressing)',
    style: 'Counter-pressing, immediate reaction defending',
    area: '30m x 30m grid',
    playerCount: '5v5 possession game',
    durationLabel: '12 min · 5s press window per turnover',
    description:
      'On loss of possession the three nearest players swarm the new carrier within 2 to 3 seconds, cutting forward passes first; the rest drop into cover; the whole team resets if the ball is not won inside 5 seconds.',
    setup:
      'Standard possession game inside the grid. The moment either team loses the ball, the rules for that team switch immediately from possession to counter-press.',
    keyPoints: [
      'React within 2 to 3 seconds — reaction speed is the entire point.',
      'Angle the press to force the carrier backward or sideways, away from goal.',
      'Never commit everyone: keep one or two in a covering position.',
      'If not regained in 5 seconds, stop the chase and reset. Communicate with a single shout.',
    ],
    simulationNote:
      'Vary the grid size across sets. Smaller means more turnovers and sharper reactions; larger better represents real counter-press distances.',
    view: 'grid',
    duration: 8,
    zones: [{ x: 0, z: -22, w: 30, d: 30, label: '30m x 30m' }],
    equipment: [
      { kind: 'cone', x: -15, z: -7 },
      { kind: 'cone', x: 15, z: -7 },
      { kind: 'cone', x: -15, z: -37 },
      { kind: 'cone', x: 15, z: -37 },
    ],
    players: [
      P('p1', 'P1', 'Nearest presser', 'defense', [
        [0, 2, -18, 'idle'],
        [0.8, 2, -19, 'sprint'],
        [2.2, -1, -21, 'press'],
        [3.6, -3, -22.5, 'tackle'],
        [6, -2, -20, 'jog'],
        [8, 0, -18, 'jog'],
      ]),
      P('p2', 'P2', 'Second presser', 'defense', [
        [0, -8, -14, 'idle'],
        [1.4, -7, -18, 'sprint'],
        [3, -5, -21, 'block'],
        [5, -6, -19, 'jog'],
        [8, -8, -16, 'jog'],
      ]),
      P('p3', 'P3', 'Third presser', 'defense', [
        [0, 8, -26, 'idle'],
        [1.6, 5, -25, 'sprint'],
        [3.4, 1, -25, 'block'],
        [6, 3, -24, 'jog'],
        [8, 6, -24, 'jog'],
      ]),
      P('p4', 'P4', 'Cover (drops)', 'defense', [
        [0, -4, -30, 'idle'],
        [2, -4, -33, 'run'],
        [5, -3, -31, 'jog'],
        [8, -2, -29, 'jog'],
      ]),
      P('p5', 'P5', 'Cover (drops)', 'defense', [
        [0, 10, -32, 'idle'],
        [2, 9, -35, 'run'],
        [8, 8, -32, 'jog'],
      ]),
      P('o1', 'O1', 'New ball carrier', 'attack', [
        [0, 0, -20, 'receive'],
        [1.6, -2, -21, 'dribble'],
        [3, -4, -22, 'hold'],
        [3.8, -5, -23, 'pass'],
        [6, -6, -24, 'jog'],
        [8, -6, -25, 'idle'],
      ]),
      P('o2', 'O2', 'Backward option', 'attack', [
        [0, -10, -28, 'idle'],
        [3, -11, -27, 'jog'],
        [4.4, -11, -26, 'receive'],
        [5.4, -12, -25, 'pass'],
        [8, -13, -24, 'jog'],
      ]),
      P('o3', 'O3', 'Long option', 'attack', [
        [0, 6, -12, 'idle'],
        [4, 4, -11, 'jog'],
        [6.4, 2, -10, 'receive'],
        [8, 0, -9, 'run'],
      ]),
      P('o4', 'O4', 'Support', 'attack', [
        [0, -14, -18, 'idle'],
        [4, -13, -16, 'jog'],
        [8, -12, -14, 'jog'],
      ]),
      P('o5', 'O5', 'Support', 'attack', [
        [0, 12, -20, 'idle'],
        [4, 12, -18, 'jog'],
        [8, 11, -16, 'jog'],
      ]),
    ],
    ball: B([
      [0, 0, -20],
      [1.6, -2, -21],
      [3, -4, -22],
      [4.3, -11, -26],
      [5.5, -12, -25],
      [6.3, 2, -10, 1.6],
      [8, 0, -9],
    ]),
  },

  {
    id: 'def-6',
    category: 'Defending',
    group: 'Set pieces',
    code: '6',
    title: 'Defending the Back Post / Crossing Situations',
    style: 'Set-piece and crossing defending, zonal and man-marking hybrid',
    area: 'Penalty area plus a wide channel for the crosser',
    playerCount: '4 defenders, 1 GK, 3 attackers, 1 crosser',
    durationLabel: '15 min · alternating sides',
    description:
      'Pressure the delivery without diving in, track near and far post runners goal side, and hold one defender on the edge of the box for cutbacks and second balls.',
    setup:
      'A wide attacker delivers crosses from the flank. Three attackers occupy near post, penalty spot and far post. Four defenders plus a goalkeeper organise the box.',
    keyPoints: [
      'The aim out wide is to affect the cross, not to win the ball.',
      'Read the far-post flight from the moment the crosser’s head goes down.',
      'The edge-of-box defender never follows the ball into the six-yard box.',
      'Two defenders arriving in the same zone leaves another zone unmarked.',
    ],
    simulationNote:
      'Vary the delivery type across reps — low driven, cutback, floated far post. Zone discipline adjusts differently for each.',
    view: 'box',
    duration: 6,
    zones: [
      { x: 0, z: -41.5, w: 40.3, d: 16.5, label: 'Penalty area', color: '#7fd1ff' },
      { x: 26, z: -38, w: 14, d: 22, label: 'Crossing channel', color: '#ffd84d' },
    ],
    players: [
      P('cr', 'CR', 'Crosser', 'attack', [
        [0, 27, -32, 'dribble'],
        [1.6, 26, -38, 'dribble'],
        [2.4, 25, -40, 'cross'],
        [6, 25, -42, 'jog'],
      ]),
      P('an', 'AN', 'Near post runner', 'attack', [
        [0, 2, -34, 'idle'],
        [1.6, 5, -39, 'run'],
        [3.2, 9, -46, 'sprint'],
        [6, 8, -48, 'jog'],
      ]),
      P('ap', 'AP', 'Penalty spot runner', 'attack', [
        [0, -4, -33, 'idle'],
        [2, -2, -37, 'jog'],
        [3.6, 0, -41.5, 'sprint'],
        [6, 0, -44, 'jog'],
      ]),
      P('af', 'AF', 'Far post runner', 'attack', [
        [0, -14, -35, 'idle'],
        [2.2, -12, -39, 'jog'],
        [3.9, -7, -46, 'sprint'],
        [4.6, -6.5, -47, 'header'],
        [6, -6, -48, 'jog'],
      ]),
      P('dp', 'DP', 'Pressuring defender', 'defense', [
        [0, 24, -30, 'jockey'],
        [1.6, 24, -36, 'press'],
        [2.5, 23.5, -39, 'block'],
        [6, 22, -41, 'jog'],
      ]),
      P('dn', 'CB', 'Near post centre back', 'defense', [
        [0, 3, -38, 'idle'],
        [1.8, 5, -41, 'jockey'],
        [3.3, 8, -46.5, 'run'],
        [6, 7, -48, 'jog'],
      ]),
      P('df', 'CB', 'Far post centre back', 'defense', [
        [0, -8, -39, 'idle'],
        [2.4, -9, -42, 'jockey'],
        [4, -6, -46.5, 'sprint'],
        [4.7, -5.5, -47.5, 'header'],
        [6, -5, -48, 'jog'],
      ]),
      P('de', 'FB', 'Edge of box defender', 'defense', [
        [0, 0, -35, 'idle'],
        [2.6, 0, -36.5, 'jockey'],
        [6, 0, -37, 'idle'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -51, 'idle'],
        [2.4, 1, -50, 'jog'],
        [4, -1, -49.5, 'block'],
        [6, 0, -50.5, 'idle'],
      ]),
    ],
    ball: B([
      [0, 27, -32],
      [1.6, 26, -38],
      [2.5, 25, -40],
      [4.1, -6.5, -46.5, 2.6],
      [5, -4, -42, 1.4],
      [6, 0, -34],
    ]),
  },

  {
    id: 'def-7',
    category: 'Defending',
    group: 'Pressure and cover',
    code: '7',
    title: 'Defending Against Overloads (Rest Defense)',
    style: 'Numbers-down defending, rest defense, communication-based cover',
    area: 'Full width, attacking third',
    playerCount: '8v8 with attackers overloading one flank',
    durationLabel: '18 min in blocks of 6',
    description:
      'Ball-near defenders delay and cut angles in a 2v3, weak-side defenders shift centrally rather than holding width, and the rest-defence player stays behind the ball throughout.',
    setup:
      'Attacking team overloads one flank with four players wide. Defending team organises its back line plus one holding midfielder to cope with the disadvantage.',
    keyPoints: [
      'Communicate numbers constantly: "we have 2 v 3, show inside".',
      'Weak-side space is the lowest priority until the ball is actually switched.',
      'The rest-defence player joins the press only once someone has replaced them centrally.',
      'A defender abandoning the rest-defence position is the biggest cause of conceding on the counter.',
    ],
    simulationNote:
      'Have the coach call the overload late, after build-up has started elsewhere, so defenders must organise under real time pressure.',
    view: 'half',
    duration: 10,
    players: [
      P('o1', 'O1', 'Wide overload — carrier', 'attack', [
        [0, 24, -22, 'receive'],
        [2, 25, -27, 'dribble'],
        [3.4, 25, -30, 'pass'],
        [6, 23, -35, 'run'],
        [10, 20, -42, 'run'],
      ]),
      P('o2', 'O2', 'Wide overload', 'attack', [
        [0, 17, -26, 'idle'],
        [3.4, 18, -30, 'jog'],
        [4.4, 18, -32, 'receive'],
        [5.6, 17, -34, 'pass'],
        [10, 14, -42, 'run'],
      ]),
      P('o3', 'O3', 'Wide overload', 'attack', [
        [0, 29, -30, 'idle'],
        [4, 29, -34, 'jog'],
        [6.2, 28, -38, 'receive'],
        [7.6, 26, -43, 'cross'],
        [10, 25, -45, 'jog'],
      ]),
      P('o4', 'O4', 'Wide overload', 'attack', [
        [0, 21, -18, 'idle'],
        [4, 22, -24, 'run'],
        [8, 12, -40, 'sprint'],
        [10, 8, -45, 'run'],
      ]),
      P('o5', 'O5', 'Far-side attacker', 'attack', [
        [0, -22, -28, 'idle'],
        [5, -20, -32, 'jog'],
        [8.4, -10, -42, 'sprint'],
        [10, -5, -46, 'run'],
      ]),
      P('d1', 'D1', 'Ball-near defender', 'defense', [
        [0, 24, -27, 'jockey'],
        [2.4, 24, -30, 'jockey'],
        [4.4, 21, -32, 'press'],
        [6.4, 26, -37, 'sprint'],
        [8, 26, -42, 'block'],
        [10, 24, -45, 'jog'],
      ]),
      P('d2', 'D2', 'Ball-near defender', 'defense', [
        [0, 17, -31, 'jockey'],
        [3.4, 17, -33, 'jockey'],
        [5.6, 15, -35, 'press'],
        [8, 12, -42, 'run'],
        [10, 9, -46, 'block'],
      ]),
      P('d3', 'D3', 'Weak-side defender (tucks in)', 'defense', [
        [0, -16, -34, 'idle'],
        [3, -8, -36, 'run'],
        [6, -2, -39, 'run'],
        [9, -3, -44, 'run'],
        [10, -4, -46, 'jog'],
      ]),
      P('d4', 'D4', 'Weak-side defender (tucks in)', 'defense', [
        [0, -6, -37, 'idle'],
        [3, 0, -38, 'jog'],
        [6, 5, -41, 'run'],
        [10, 3, -46, 'run'],
      ]),
      P('d5', 'RD', 'Rest defence (holding midfielder)', 'defense', [
        [0, 10, -20, 'idle'],
        [3, 12, -24, 'jog'],
        [6, 14, -28, 'jog'],
        [8.5, 14, -32, 'jog'],
        [10, 13, -34, 'idle'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [6, 2, -50, 'jog'],
        [8.4, 4, -49, 'jog'],
        [10, 1, -49.5, 'block'],
      ]),
    ],
    ball: B([
      [0, 24, -22],
      [2, 25, -27],
      [3.5, 18, -32],
      [5.6, 17, -34],
      [6.2, 28, -38],
      [7.7, 26, -43],
      [9, 4, -44],
      [10, 1, -48, 0.5],
    ]),
  },
]
