import { ballPath as B, player as P, type Drill } from '../types'

/**
 * Passing Drills Manual — 21 drills across foundation work and six play
 * styles. Grids are placed inside one half of the pitch so the camera
 * presets frame them without extra configuration.
 */
export const PASSING: Drill[] = [
  /* ---------------- Section A: Foundation ---------------- */
  {
    id: 'pas-a1',
    category: 'Passing',
    group: 'A — Foundation drills',
    code: 'A1',
    title: 'Y-Drill with Scan Trigger',
    style: 'Foundation — first touch, half turn, scanning',
    area: '25m x 20m',
    playerCount: 'Groups of 5',
    durationLabel: '10 min',
    description:
      'Firm pass into the middle player’s back foot. They scan over both shoulders before it arrives, read the coach’s colour trigger, and open out to the opposite arm of the Y.',
    setup:
      'Cones in a Y shape. Player A at the base with the ball, B in the middle stem, C and D at the arms, E serving the colour trigger behind B.',
    keyPoints: [
      'Scan before receiving — minimum two head turns while the ball travels.',
      'First touch out of the feet at an angle, never straight ahead.',
      'Two touches maximum for the middle player: one to open, one to pass.',
      'Pass to the back foot, not the front foot.',
    ],
    simulationNote:
      'The colour trigger replicates the picture changing while the ball travels. Players who scan once and act on old information lose the ball between the lines.',
    view: 'grid',
    duration: 7,
    zones: [{ x: 0, z: -22, w: 25, d: 20, label: '25m x 20m' }],
    equipment: [
      { kind: 'cone', x: 0, z: -12 },
      { kind: 'cone', x: 0, z: -22 },
      { kind: 'cone', x: -9, z: -30 },
      { kind: 'cone', x: 9, z: -30 },
    ],
    players: [
      P('a', 'A', 'Base player', 'attack', [
        [0, 0, -12, 'pass'],
        [1.4, 0, -14, 'jog'],
        [4, 0, -19, 'jog'],
        [7, 0, -21, 'idle'],
      ]),
      P('b', 'B', 'Middle player', 'attack', [
        [0, 0, -22, 'scan'],
        [1.2, 0.5, -22, 'scan'],
        [2, 0.5, -22.5, 'receive'],
        [2.8, -1.5, -23.5, 'pass'],
        [5, -1.5, -24, 'jog'],
        [7, -1, -25, 'idle'],
      ]),
      P('c', 'C', 'Left arm', 'attack', [
        [0, -9, -30, 'idle'],
        [2.6, -8, -29, 'jog'],
        [3.8, -7.5, -28.5, 'receive'],
        [4.6, -7, -28, 'pass'],
        [7, -8, -29, 'jog'],
      ]),
      P('d', 'D', 'Right arm', 'attack', [
        [0, 9, -30, 'idle'],
        [3, 9, -29, 'jog'],
        [7, 9, -29.5, 'idle'],
      ]),
      P('e', 'E', 'Trigger server', 'neutral', [
        [0, 4, -26, 'idle'],
        [1.2, 4, -26, 'scan'],
        [7, 4.5, -26, 'idle'],
      ]),
    ],
    ball: B([
      [0, 0, -12],
      [1.9, 0.5, -22.4],
      [2.5, 0.5, -22.6],
      [3.7, -7.5, -28.5],
      [4.7, -7, -28],
      [5.9, 0, -20],
      [7, 0, -19],
    ]),
  },

  {
    id: 'pas-a2',
    category: 'Passing',
    group: 'A — Foundation drills',
    code: 'A2',
    title: 'Four Goal Passing Grid',
    style: 'Foundation — passing range, disguise, weight',
    area: '20m x 20m with a small goal on each side',
    playerCount: '6 to 8',
    durationLabel: '10 min',
    description:
      'Score by passing through any goal to a teammate on the other side, then score through a different goal next. Two touches maximum throughout.',
    setup:
      'Four small goals, one on each side of a square. Two teams. A goal only counts if the pass is received cleanly.',
    keyPoints: [
      'Scan for which goal is unguarded before receiving.',
      'Off-ball players position on the far side of goals, not next to the ball.',
      'Always offer a backward option so the point of attack can switch.',
      'Trains finding the free space rather than the free player.',
    ],
    simulationNote:
      'The underlying skill in almost every possession system: find the space, not the name.',
    view: 'grid',
    duration: 8,
    zones: [{ x: 0, z: -22, w: 20, d: 20, label: '20m x 20m' }],
    equipment: [
      { kind: 'mini-goal', x: 0, z: -12, rot: 180 },
      { kind: 'mini-goal', x: 0, z: -32 },
      { kind: 'mini-goal', x: -10, z: -22, rot: 90 },
      { kind: 'mini-goal', x: 10, z: -22, rot: -90 },
    ],
    players: [
      P('t1a', 'A1', 'Team A', 'attack', [
        [0, -6, -17, 'receive'],
        [1.2, -5, -18, 'pass'],
        [4, -3, -16, 'jog'],
        [8, -2, -15, 'idle'],
      ]),
      P('t1b', 'A2', 'Team A', 'attack', [
        [0, 5, -20, 'idle'],
        [1.8, 6, -20, 'receive'],
        [2.8, 7, -21, 'pass'],
        [5, 8, -24, 'jog'],
        [8, 8, -26, 'idle'],
      ]),
      P('t1c', 'A3', 'Team A (far side of goal)', 'attack', [
        [0, 14, -22, 'idle'],
        [3.4, 13, -22, 'receive'],
        [4.4, 12, -23, 'pass'],
        [8, 12, -25, 'jog'],
      ]),
      P('t1d', 'A4', 'Team A (backward option)', 'attack', [
        [0, -2, -28, 'idle'],
        [4.6, -2, -27, 'receive'],
        [5.6, -1, -27, 'pass'],
        [8, 0, -29, 'jog'],
      ]),
      P('t2a', 'B1', 'Team B', 'defense', [
        [0, -1, -19, 'press'],
        [2, 4, -20, 'press'],
        [4, 9, -22, 'sprint'],
        [6, 2, -26, 'press'],
        [8, 0, -30, 'run'],
      ]),
      P('t2b', 'B2', 'Team B', 'defense', [
        [0, 3, -25, 'idle'],
        [2.4, -1, -24, 'press'],
        [5, -3, -26, 'press'],
        [8, -4, -31, 'run'],
      ]),
      P('t2c', 'B3', 'Team B', 'defense', [
        [0, -7, -24, 'idle'],
        [3, -6, -21, 'jog'],
        [6, -4, -19, 'press'],
        [8, -3, -18, 'jog'],
      ]),
    ],
    ball: B([
      [0, -6, -17],
      [1.3, -5, -18],
      [1.9, 6, -20],
      [2.9, 7, -21],
      [3.4, 13, -22],
      [4.5, 12, -23],
      [5.6, -1, -27],
      [6.6, 0, -32.5],
      [8, 0, -34],
    ]),
  },

  {
    id: 'pas-a3',
    category: 'Passing',
    group: 'A — Foundation drills',
    code: 'A3',
    title: 'Progressive Passing Ladder',
    style: 'Foundation — passing over three distances',
    area: '60m x 15m channel',
    playerCount: 'Pairs or groups of 4',
    durationLabel: '10 min',
    description:
      'Three stations, three techniques: 10m inside of the foot along the ground, 25m driven below head height, 45m lofted into the space ahead of the receiver.',
    setup: 'Mark three distances — 10m, 25m, 45m. Players work through each in sequence.',
    keyPoints: [
      '10m: non-kicking foot at the target, ankle locked, follow through low.',
      '25m: strike slightly above centre with the laces, body over the ball.',
      '45m: strike beneath centre, approach at 30 to 45 degrees, land it into space.',
      'Using the same technique for all three distances is the core error.',
    ],
    simulationNote:
      'Have the receiver start their run at random so the passer judges both distance and timing. Long passing is a timing skill as much as a striking one.',
    view: 'full',
    duration: 10,
    zones: [
      { x: 0, z: -20, w: 15, d: 60, label: '60m x 15m channel' },
      { x: 0, z: -5, w: 15, d: 10, label: '10m', color: '#7fd1ff' },
      { x: 0, z: -22.5, w: 15, d: 25, label: '25m', color: '#ffd84d' },
    ],
    equipment: [
      { kind: 'pole', x: -7, z: 10 },
      { kind: 'pole', x: 7, z: 10 },
      { kind: 'pole', x: -7, z: -50 },
      { kind: 'pole', x: 7, z: -50 },
      { kind: 'disc', x: 0, z: 0 },
      { kind: 'disc', x: 0, z: -10 },
      { kind: 'disc', x: 0, z: -35 },
    ],
    players: [
      P('ps', 'PS', 'Passer', 'attack', [
        [0, 0, 8, 'pass'],
        [2.4, 0, 6, 'jog'],
        [3.4, 0, 5, 'pass'],
        [6, 0, 4, 'jog'],
        [7, 0, 3, 'pass'],
        [10, 0, 2, 'idle'],
      ]),
      P('r1', 'R1', 'Receiver — 10m', 'attack', [
        [0, 0, -2, 'idle'],
        [1.2, 0, -2, 'receive'],
        [2, 0, -3, 'pass'],
        [10, 0, -4, 'jog'],
      ]),
      P('r2', 'R2', 'Receiver — 25m', 'attack', [
        [0, 0, -17, 'idle'],
        [4.4, 0, -18, 'receive'],
        [5.4, 0, -19, 'pass'],
        [10, 0, -20, 'jog'],
      ]),
      P('r3', 'R3', 'Receiver — 45m', 'attack', [
        [0, 4, -34, 'idle'],
        [6.8, 2, -38, 'run'],
        [8.6, 0, -42, 'receive'],
        [10, 0, -45, 'jog'],
      ]),
    ],
    ball: B([
      [0, 0, 8],
      [1.2, 0, -2, 0.15],
      [2.1, 0, -3],
      [3, 0, 5],
      [4.4, 0, -18, 0.9],
      [5.5, 0, -19],
      [6.6, 0, 3],
      [8.6, 0, -42, 0.4],
      [10, 0, -45],
    ]),
  },

  /* ---------------- Section B: Tiki-taka ---------------- */
  {
    id: 'pas-b1',
    category: 'Passing',
    group: 'B — Tiki-taka and positional play',
    code: 'B1',
    title: 'Positional Rondo 4v4 plus 3 Neutrals',
    style: 'Tiki-taka, positional play',
    area: '25m x 20m in three horizontal zones',
    playerCount: '4v4 plus 3 neutrals',
    durationLabel: '15 min in 3 minute blocks',
    description:
      'One neutral locked into each horizontal zone. A pass from bottom zone to top scores; skipping the middle zone entirely scores triple.',
    setup:
      'Three horizontal zones with one locked neutral each. Two teams of four move freely.',
    keyPoints: [
      'Neutrals position on the far edge of their zone, body open, never facing the ball with their back to the zone ahead.',
      'Find who is free before receiving, not while holding the ball.',
      'The pass that breaks a line beats the pass that keeps possession — score accordingly.',
      'Neutrals standing close to the ball is the standard breakdown.',
    ],
    simulationNote:
      'Drop the pressing team to three for a block, then raise to five. The decision changes with the pressure level; players must learn both.',
    view: 'grid',
    duration: 9,
    zones: [
      { x: 0, z: -12, w: 25, d: 7, label: 'Top zone', color: '#7fd1ff' },
      { x: 0, z: -19, w: 25, d: 7, label: 'Middle zone', color: '#ffd84d' },
      { x: 0, z: -26, w: 25, d: 7, label: 'Bottom zone', color: '#7fd1ff' },
    ],
    players: [
      P('n1', 'N1', 'Neutral — bottom zone', 'neutral', [
        [0, -10, -26, 'receive'],
        [1, -9, -26, 'pass'],
        [5, -11, -26, 'jog'],
        [9, -10, -26, 'idle'],
      ]),
      P('n2', 'N2', 'Neutral — middle zone', 'neutral', [
        [0, 10, -19, 'idle'],
        [2.4, 9, -19, 'receive'],
        [3.4, 8, -19, 'pass'],
        [9, 10, -19, 'jog'],
      ]),
      P('n3', 'N3', 'Neutral — top zone', 'neutral', [
        [0, -9, -12, 'idle'],
        [5.8, -8, -12, 'receive'],
        [6.8, -7, -12, 'pass'],
        [9, -9, -12, 'jog'],
      ]),
      P('p1', 'P1', 'Possession', 'attack', [
        [0, -3, -25, 'idle'],
        [1.4, -2, -25, 'receive'],
        [2.4, -1, -24, 'pass'],
        [5, 0, -22, 'jog'],
        [9, 1, -20, 'jog'],
      ]),
      P('p2', 'P2', 'Possession', 'attack', [
        [0, 4, -21, 'idle'],
        [3.4, 5, -20, 'receive'],
        [4.4, 4, -19, 'pass'],
        [7, 2, -16, 'run'],
        [9, 2, -14, 'jog'],
      ]),
      P('p3', 'P3', 'Possession', 'attack', [
        [0, -6, -18, 'idle'],
        [4.6, -6, -17, 'receive'],
        [5.4, -6.5, -16, 'pass'],
        [9, -6, -15, 'jog'],
      ]),
      P('p4', 'P4', 'Possession — top zone target', 'attack', [
        [0, 3, -12, 'idle'],
        [6, 2, -12, 'jog'],
        [7, 1, -12, 'receive'],
        [9, 0, -11, 'jog'],
      ]),
      P('d1', 'D1', 'Pressing leader', 'defense', [
        [0, -1, -24, 'press'],
        [2.4, 2, -23, 'press'],
        [5, 4, -20, 'press'],
        [7.4, 0, -16, 'sprint'],
        [9, -1, -13, 'run'],
      ]),
      P('d2', 'D2', 'Pressing team', 'defense', [
        [0, 6, -24, 'idle'],
        [2.6, -2, -22, 'press'],
        [5.6, -4, -18, 'press'],
        [9, -3, -15, 'run'],
      ]),
      P('d3', 'D3', 'Pressing team', 'defense', [
        [0, -6, -22, 'idle'],
        [3, 0, -20, 'press'],
        [6, 3, -17, 'press'],
        [9, 3, -14, 'run'],
      ]),
      P('d4', 'D4', 'Pressing team', 'defense', [
        [0, 2, -15, 'idle'],
        [4, 4, -16, 'jog'],
        [7, -1, -14, 'press'],
        [9, 0, -12, 'press'],
      ]),
    ],
    ball: B([
      [0, -10, -26],
      [1.1, -2, -25],
      [2.4, 9, -19],
      [3.5, 5, -20],
      [4.5, -6, -17],
      [5.6, -8, -12],
      [6.9, 1, -12],
      [9, 0, -11],
    ]),
  },

  {
    id: 'pas-b2',
    category: 'Passing',
    group: 'B — Tiki-taka and positional play',
    code: 'B2',
    title: 'Third Line Passing (Building Through Three Zones)',
    style: 'Tiki-taka, positional play',
    area: '50m x 40m divided into three zones',
    playerCount: '8v6 attacking bias plus goalkeepers',
    durationLabel: '18 min',
    description:
      'Split the centre backs, wait for the presser to commit, break the first line into the midfielder’s back foot, then the forward drops to lay off or spins in behind.',
    setup:
      'Zone 1 is build-up with 3 defenders and a GK, zone 2 midfield, zone 3 attacking with two forwards. Defenders press 2 / 3 / 1 across the zones.',
    keyPoints: [
      'A pass played before the presser moves does not break anything.',
      'Position in the gaps between pressers, never in their cover shadow.',
      'One player must always sit behind the ball for the safe backward pass.',
      'Count line-breaking passes: 20 passes with no line broken has no value.',
    ],
    simulationNote:
      'Change the pressing structure between blocks. Against a high press the answer is the direct ball; against a mid block, patient circulation.',
    view: 'half',
    duration: 11,
    zones: [
      { x: 0, z: -8, w: 40, d: 16, label: 'Zone 1 — build-up', color: '#7fd1ff' },
      { x: 0, z: -25, w: 40, d: 17, label: 'Zone 2 — midfield', color: '#ffd84d' },
      { x: 0, z: -42, w: 40, d: 17, label: 'Zone 3 — attacking', color: '#8affa0' },
    ],
    players: [
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -2, 'idle'],
        [3, 0, -3, 'receive'],
        [4, 0, -3.5, 'pass'],
        [11, 0, -4, 'idle'],
      ]),
      P('cb1', 'CB', 'Left centre back', 'attack', [
        [0, -13, -6, 'receive'],
        [1.2, -14, -7, 'pass'],
        [4, -14, -8, 'jog'],
        [11, -13, -9, 'idle'],
      ]),
      P('cb2', 'CB', 'Right centre back', 'attack', [
        [0, 13, -6, 'idle'],
        [4.2, 13, -7, 'receive'],
        [5.2, 12, -8, 'pass'],
        [11, 12, -9, 'idle'],
      ]),
      P('m1', 'M1', 'Midfielder (half turn)', 'attack', [
        [0, 4, -22, 'scan'],
        [5.2, 5, -23, 'scan'],
        [6, 5, -23.5, 'receive'],
        [7, 4, -25, 'pass'],
        [9, 3, -30, 'run'],
        [11, 3, -34, 'jog'],
      ]),
      P('m2', 'M2', 'Midfielder (behind the ball)', 'attack', [
        [0, -6, -20, 'idle'],
        [4, -6, -21, 'jog'],
        [8, -5, -22, 'idle'],
        [11, -5, -24, 'jog'],
      ]),
      P('f1', 'F1', 'Forward (drops)', 'attack', [
        [0, -3, -40, 'idle'],
        [6.4, -3, -36, 'jog'],
        [7.8, -2, -34, 'receive'],
        [8.8, -1, -35, 'layoff'],
        [11, 0, -38, 'jog'],
      ]),
      P('f2', 'F2', 'Forward (spins in behind)', 'attack', [
        [0, 6, -40, 'idle'],
        [7, 7, -41, 'jog'],
        [8.6, 8, -45, 'sprint'],
        [10, 6, -48, 'receive'],
        [11, 5, -49, 'jog'],
      ]),
      P('pr1', 'PR', 'Presser — zone 1', 'defense', [
        [0, -8, -10, 'press'],
        [1.4, -11, -8, 'press'],
        [4.6, -2, -10, 'run'],
        [7, 2, -14, 'run'],
        [11, 3, -18, 'jog'],
      ]),
      P('pr2', 'PR', 'Presser — zone 1', 'defense', [
        [0, 6, -12, 'idle'],
        [4.4, 10, -9, 'press'],
        [7, 8, -14, 'run'],
        [11, 7, -18, 'jog'],
      ]),
      P('pr3', 'PR', 'Presser — zone 2', 'defense', [
        [0, 2, -26, 'idle'],
        [5.6, 4, -25, 'press'],
        [7.2, 3, -26, 'tackle'],
        [9, 0, -31, 'run'],
        [11, 0, -35, 'run'],
      ]),
      P('pr4', 'PR', 'Presser — zone 2', 'defense', [
        [0, -8, -26, 'idle'],
        [6, -6, -25, 'press'],
        [9, -3, -32, 'run'],
        [11, -2, -36, 'run'],
      ]),
      P('pr5', 'PR', 'Presser — zone 3', 'defense', [
        [0, 4, -42, 'idle'],
        [7.4, 2, -40, 'jockey'],
        [9.4, 7, -44, 'sprint'],
        [11, 7, -48, 'run'],
      ]),
    ],
    ball: B([
      [0, -13, -6],
      [1.3, -14, -7],
      [2.8, 0, -3],
      [4.2, 13, -7],
      [5.3, 12, -8],
      [6, 5, -23.5],
      [7.1, -2, -34],
      [8.9, -1.2, -35],
      [10, 6, -48],
      [11, 5, -49],
    ]),
  },

  {
    id: 'pas-b3',
    category: 'Passing',
    group: 'B — Tiki-taka and positional play',
    code: 'B3',
    title: 'Switch and Penetrate',
    style: 'Tiki-taka, positional play',
    area: 'Full width, 40m deep, four small goals on the far line',
    playerCount: '8v6',
    durationLabel: '15 min',
    description:
      'Overload one flank until more than half the defence is on that side, switch in one pass, and penetrate within 6 seconds while a support runner sprints across as the ball travels.',
    setup:
      'Five vertical lanes. Four small goals on the attacking line — one in each wide lane and each half-space. No central goal, which forces the play wide.',
    keyPoints: [
      'The switch trigger is the defence having more than half its players on one side.',
      'Must be facing across the pitch before receiving — receiving square makes the switch impossible.',
      'The far receiver stays wide and still; movement attracts a marker.',
      'Two switches without penetration loses a point — no sterile side-to-side passing.',
    ],
    view: 'half',
    duration: 10,
    zones: [
      { x: -27, z: -25, w: 14, d: 40, color: '#7fd1ff' },
      { x: -13.5, z: -25, w: 13, d: 40, color: '#ffd84d' },
      { x: 0, z: -25, w: 14, d: 40, color: '#7fd1ff' },
      { x: 13.5, z: -25, w: 13, d: 40, color: '#ffd84d' },
      { x: 27, z: -25, w: 14, d: 40, color: '#7fd1ff' },
    ],
    equipment: [
      { kind: 'mini-goal', x: -27, z: -45 },
      { kind: 'mini-goal', x: -13.5, z: -45 },
      { kind: 'mini-goal', x: 13.5, z: -45 },
      { kind: 'mini-goal', x: 27, z: -45 },
    ],
    players: [
      P('o1', 'O1', 'Overload — carrier', 'attack', [
        [0, 20, -14, 'receive'],
        [1.2, 19, -16, 'pass'],
        [4, 17, -20, 'jog'],
        [10, 12, -28, 'run'],
      ]),
      P('o2', 'O2', 'Overload', 'attack', [
        [0, 27, -18, 'idle'],
        [1.4, 26, -18, 'receive'],
        [2.4, 25, -19, 'pass'],
        [10, 22, -26, 'run'],
      ]),
      P('o3', 'O3', 'Overload', 'attack', [
        [0, 14, -22, 'idle'],
        [2.6, 14, -21, 'receive'],
        [10, 10, -30, 'run'],
      ]),
      P('sw', 'SW', 'Switching player', 'attack', [
        [0, 4, -18, 'scan'],
        [3.4, 5, -19, 'receive'],
        [4.4, 4, -20, 'pass'],
        [7, 0, -26, 'run'],
        [10, -4, -34, 'run'],
      ]),
      P('fr', 'FR', 'Far-side receiver', 'attack', [
        [0, -28, -22, 'idle'],
        [4.4, -28, -23, 'idle'],
        [5.8, -27, -26, 'receive'],
        [7.2, -26, -33, 'dribble'],
        [8.4, -27, -40, 'shoot'],
        [10, -27, -43, 'jog'],
      ]),
      P('sr', 'SR', 'Support runner', 'attack', [
        [0, 6, -26, 'idle'],
        [4.4, 2, -26, 'sprint'],
        [7, -12, -30, 'sprint'],
        [9, -14, -38, 'run'],
        [10, -14, -42, 'jog'],
      ]),
      P('d1', 'D1', 'Shifted defender', 'defense', [
        [0, 22, -18, 'press'],
        [3, 18, -20, 'press'],
        [6, 8, -24, 'sprint'],
        [10, -6, -32, 'run'],
      ]),
      P('d2', 'D2', 'Shifted defender', 'defense', [
        [0, 15, -24, 'idle'],
        [3, 12, -22, 'jog'],
        [6.4, 0, -26, 'sprint'],
        [10, -14, -34, 'run'],
      ]),
      P('d3', 'D3', 'Shifted defender', 'defense', [
        [0, 8, -28, 'idle'],
        [3.4, 6, -24, 'jog'],
        [7, -8, -28, 'sprint'],
        [10, -20, -36, 'run'],
      ]),
      P('d4', 'D4', 'Far-side defender', 'defense', [
        [0, -10, -26, 'idle'],
        [4, -6, -24, 'jog'],
        [6.6, -20, -28, 'sprint'],
        [8.6, -25, -37, 'press'],
        [10, -25, -41, 'run'],
      ]),
    ],
    ball: B([
      [0, 20, -14],
      [1.3, 26, -18],
      [2.5, 14, -21],
      [3.4, 5, -19],
      [4.5, 4, -20],
      [5.8, -27, -25.5, 1.7],
      [7.2, -26, -33],
      [8.5, -27, -40],
      [10, -27, -46, 0.4],
    ]),
  },

  /* ---------------- Section C: Gegenpress ---------------- */
  {
    id: 'pas-c1',
    category: 'Passing',
    group: 'C — Gegenpress and vertical transition',
    code: 'C1',
    title: 'Vertical Passing Gate Game',
    style: 'Gegenpress, vertical transition',
    area: '40m x 30m with vertically oriented gates',
    playerCount: '6v6',
    durationLabel: '12 min in 3 minute blocks',
    description:
      'One point per completed pass forward through a gate. Maximum 3 seconds on the ball, no two backward passes in a row.',
    setup:
      'Six 2m gates scattered across the pitch, all oriented so that passing through them means passing forward.',
    keyPoints: [
      'Look forward first, always — this is a habit drill as much as a technical one.',
      'Position beyond gates, not beside them. You must be findable through a gate.',
      'Make the run before the passer looks up, not after.',
      'Reward the attempted forward pass even when it fails, at least in early blocks.',
    ],
    simulationNote:
      'Run immediately after a physically demanding activity — tired players default to the safe sideways ball.',
    view: 'grid',
    duration: 9,
    zones: [{ x: 0, z: -25, w: 30, d: 40, label: '40m x 30m' }],
    equipment: [
      { kind: 'gate', x: -8, z: -14, color: '#4ad1c6' },
      { kind: 'gate', x: 8, z: -18, color: '#4ad1c6' },
      { kind: 'gate', x: -2, z: -24, color: '#4ad1c6' },
      { kind: 'gate', x: 11, z: -30, color: '#4ad1c6' },
      { kind: 'gate', x: -11, z: -33, color: '#4ad1c6' },
      { kind: 'gate', x: 2, z: -38, color: '#4ad1c6' },
    ],
    players: [
      P('a1', 'A1', 'On the ball', 'attack', [
        [0, -8, -9, 'receive'],
        [1.2, -8, -11, 'pass'],
        [4, -6, -16, 'run'],
        [9, -4, -24, 'run'],
      ]),
      P('a2', 'A2', 'Beyond the gate', 'attack', [
        [0, -8, -18, 'jog'],
        [1.6, -8, -18, 'receive'],
        [2.6, -6, -19, 'pass'],
        [6, -3, -26, 'run'],
        [9, -2, -32, 'run'],
      ]),
      P('a3', 'A3', 'Beyond the gate', 'attack', [
        [0, -2, -22, 'idle'],
        [1.9, -2, -27, 'run'],
        [3.6, -2, -28, 'receive'],
        [4.6, 0, -29, 'pass'],
        [9, 2, -34, 'run'],
      ]),
      P('a4', 'A4', 'Beyond the gate', 'attack', [
        [0, 10, -26, 'idle'],
        [4, 11, -32, 'run'],
        [5.4, 11, -34, 'receive'],
        [6.4, 9, -35, 'pass'],
        [9, 7, -38, 'jog'],
      ]),
      P('a5', 'A5', 'Beyond the gate', 'attack', [
        [0, 2, -34, 'idle'],
        [6, 2, -40, 'run'],
        [7.4, 2, -42, 'receive'],
        [9, 1, -44, 'jog'],
      ]),
      P('b1', 'B1', 'Presser', 'defense', [
        [0, -6, -12, 'press'],
        [2.4, -7, -19, 'press'],
        [5, -3, -27, 'sprint'],
        [9, 0, -36, 'run'],
      ]),
      P('b2', 'B2', 'Presser', 'defense', [
        [0, 4, -20, 'idle'],
        [3, -1, -25, 'press'],
        [6, 8, -32, 'sprint'],
        [9, 5, -40, 'run'],
      ]),
      P('b3', 'B3', 'Presser', 'defense', [
        [0, -10, -28, 'idle'],
        [4, -4, -30, 'jog'],
        [7, 3, -38, 'press'],
        [9, 2, -43, 'press'],
      ]),
    ],
    ball: B([
      [0, -8, -9],
      [1.5, -8, -18],
      [2.6, -6, -19],
      [3.6, -2, -28],
      [4.7, 0, -29],
      [5.4, 11, -34],
      [6.5, 9, -35],
      [7.4, 2, -42],
      [9, 1, -44],
    ]),
  },

  {
    id: 'pas-c2',
    category: 'Passing',
    group: 'C — Gegenpress and vertical transition',
    code: 'C2',
    title: 'Transition Passing: 6 Second Rule',
    style: 'Gegenpress, vertical transition',
    area: '60m x 45m, two full goals',
    playerCount: '7v7',
    durationLabel: '15 min',
    description:
      'Coach plays a new ball in; the team winning it must shoot within 6 seconds, first pass forward, maximum four passes.',
    setup:
      'Both teams play normally. The coach randomly plays a new ball into a team, which starts the transition.',
    keyPoints: [
      'Scan while the ball is travelling — in transition there is no time to look after receiving.',
      'The furthest forward player sprints regardless of expecting the ball.',
      'Wide players run forward and outward at once; checking back shortens the pitch.',
      'Passing weight in transition is harder, flatter, into space rather than to feet.',
    ],
    simulationNote:
      'Freeze the drill on every sideways first pass. Measure time from turnover to the ball entering the final third — target under 6 seconds.',
    view: 'full',
    duration: 8,
    players: [
      P('fr', 'FR', 'First receiver', 'attack', [
        [0, 0, 4, 'receive'],
        [1, 0, 1, 'dribble'],
        [1.8, -1, -1, 'pass'],
        [5, -2, -12, 'run'],
        [8, -3, -22, 'run'],
      ]),
      P('ff', 'FF', 'Furthest forward', 'attack', [
        [0, -2, -14, 'sprint'],
        [2.2, -4, -22, 'receive'],
        [3.2, -3, -25, 'pass'],
        [6, -2, -34, 'run'],
        [8, -2, -40, 'run'],
      ]),
      P('lw', 'LW', 'Wide player', 'attack', [
        [0, -20, -6, 'sprint'],
        [3, -24, -20, 'sprint'],
        [4.4, -23, -28, 'receive'],
        [5.4, -21, -32, 'pass'],
        [8, -16, -40, 'run'],
      ]),
      P('rw', 'RW', 'Far-side wide player', 'attack', [
        [0, 20, -6, 'sprint'],
        [3, 24, -20, 'sprint'],
        [6, 16, -36, 'sprint'],
        [6.9, 10, -41, 'shoot'],
        [8, 8, -44, 'jog'],
      ]),
      P('tm', 'TM', 'Trailing midfielder', 'attack', [
        [0, 3, 10, 'idle'],
        [3, 2, -2, 'run'],
        [6, 1, -18, 'run'],
        [8, 0, -28, 'run'],
      ]),
      P('d1', 'D1', 'Recovering defender', 'defense', [
        [0, -4, -18, 'jockey'],
        [3, -5, -26, 'run'],
        [6, -6, -36, 'run'],
        [8, -4, -42, 'run'],
      ]),
      P('d2', 'D2', 'Recovering defender', 'defense', [
        [0, 6, -20, 'idle'],
        [3, 4, -28, 'run'],
        [6.4, 12, -38, 'sprint'],
        [8, 11, -43, 'block'],
      ]),
      P('d3', 'D3', 'Recovering defender', 'defense', [
        [0, -14, -22, 'idle'],
        [3.4, -18, -28, 'run'],
        [6, -18, -38, 'run'],
        [8, -14, -44, 'jog'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [5, 2, -49.5, 'jog'],
        [7, 5, -48.5, 'block'],
        [8, 4, -49, 'idle'],
      ]),
    ],
    ball: B([
      [0, 0, 4],
      [1, 0, 1],
      [2.2, -4, -22],
      [3.3, -3, -25],
      [4.4, -23, -28],
      [5.5, -21, -32],
      [6.6, 11, -40],
      [8, -3.0, -52.7, 1],
    ]),
  },

  {
    id: 'pas-c3',
    category: 'Passing',
    group: 'C — Gegenpress and vertical transition',
    code: 'C3',
    title: 'Press Escape Passing',
    style: 'Gegenpress, playing out under pressure',
    area: '30m x 25m plus a target zone 25m beyond',
    playerCount: '5 in possession, 4 pressing, 2 targets',
    durationLabel: '12 min',
    description:
      'Escape a full press to reach a target player — through the press for 2 points, over it for 1. One touch whenever a presser is within 2m.',
    setup:
      'Possession team in the tight grid under a full press. Two target players wait in the far zone.',
    keyPoints: [
      'The deepest player is the free player — position centrally, body angled across, never back to the press.',
      'Show for the ball only when you can receive facing forward or play one touch.',
      'Playing over the press is not failure; it is correct when the press is well organised.',
      'Under pressure the pass must be firm — soft passes are intercepted.',
    ],
    view: 'grid',
    duration: 9,
    zones: [
      { x: 0, z: -18, w: 25, d: 30, label: 'Press grid', color: '#ff6b5a' },
      { x: 0, z: -45, w: 25, d: 16, label: 'Target zone', color: '#8affa0', fill: true },
    ],
    players: [
      P('deep', 'FP', 'Deepest player (free man)', 'attack', [
        [0, 0, -6, 'receive'],
        [1.4, -2, -7, 'scan'],
        [2.2, -3, -8, 'pass'],
        [6, -2, -12, 'jog'],
        [9, -1, -16, 'jog'],
      ]),
      P('p2', 'P2', 'Possession', 'attack', [
        [0, -9, -14, 'idle'],
        [2.4, -8, -14, 'receive'],
        [3.2, -7, -15, 'pass'],
        [6, -6, -20, 'run'],
        [9, -5, -26, 'run'],
      ]),
      P('p3', 'P3', 'Possession', 'attack', [
        [0, 8, -18, 'idle'],
        [3.4, 7, -18, 'receive'],
        [4.4, 6, -19, 'pass'],
        [9, 5, -24, 'run'],
      ]),
      P('p4', 'P4', 'Possession', 'attack', [
        [0, -2, -24, 'idle'],
        [4.6, -1, -24, 'receive'],
        [5.6, 0, -25, 'pass'],
        [9, 1, -30, 'run'],
      ]),
      P('p5', 'P5', 'Possession', 'attack', [
        [0, 4, -10, 'idle'],
        [4, 3, -14, 'jog'],
        [9, 2, -20, 'run'],
      ]),
      P('t1', 'T1', 'Target — comes short', 'attack', [
        [0, -4, -40, 'idle'],
        [4, -4, -38, 'jog'],
        [6.4, -3, -36, 'receive'],
        [7.4, -3, -37, 'layoff'],
        [9, -3, -40, 'jog'],
      ]),
      P('t2', 'T2', 'Target — stays long', 'attack', [
        [0, 5, -46, 'idle'],
        [5, 5, -45, 'jog'],
        [8, 4, -44, 'receive'],
        [9, 4, -45, 'idle'],
      ]),
      P('x1', 'X1', 'Presser', 'defense', [
        [0, -2, -9, 'press'],
        [2.4, -6, -13, 'press'],
        [5, -2, -20, 'sprint'],
        [9, 0, -28, 'run'],
      ]),
      P('x2', 'X2', 'Presser', 'defense', [
        [0, 5, -14, 'idle'],
        [3, 8, -17, 'press'],
        [6, 2, -23, 'press'],
        [9, 2, -30, 'run'],
      ]),
      P('x3', 'X3', 'Presser', 'defense', [
        [0, -7, -20, 'idle'],
        [3.4, -3, -22, 'press'],
        [6.4, 0, -28, 'sprint'],
        [9, -1, -34, 'run'],
      ]),
      P('x4', 'X4', 'Presser', 'defense', [
        [0, 2, -28, 'idle'],
        [4, 0, -26, 'press'],
        [7, -3, -32, 'sprint'],
        [9, -3, -38, 'run'],
      ]),
    ],
    ball: B([
      [0, 0, -6],
      [2.3, -8, -14],
      [3.3, -7, -15],
      [3.4, 7, -18],
      [4.5, 6, -19],
      [4.6, -1, -24],
      [5.7, 0, -25],
      [6.4, -3, -36],
      [7.5, -3, -37],
      [8, 4, -44],
      [9, 4, -45],
    ]),
  },

  /* ---------------- Section D: Wing play ---------------- */
  {
    id: 'pas-d1',
    category: 'Passing',
    group: 'D — Wing play',
    code: 'D1',
    title: 'Switch to Wing Combination',
    style: 'Wing play',
    area: 'Full width, 40m deep, 8m channels on both touchlines',
    playerCount: '8v6 plus a goalkeeper',
    durationLabel: '15 min',
    description:
      'Circulate to shift the defence, switch in one pass once the far channel is genuinely 1v1, then three players attack near post, penalty spot and back post.',
    setup:
      'Mark 8m channels on both touchlines. Only one attacker and one defender may be in each channel at any time.',
    keyPoints: [
      'The trigger is the far channel being 1v1 with the defender tight to the touchline.',
      'Pass slightly infield of the wide player’s body so they can control forward.',
      'Passing to the winger’s feet on the touchline traps them.',
      'Three arrivals in the box on every wide entry.',
    ],
    view: 'half',
    duration: 10,
    zones: [
      { x: -30, z: -26, w: 8, d: 40, label: 'Channel', color: '#7fd1ff' },
      { x: 30, z: -26, w: 8, d: 40, label: 'Channel', color: '#7fd1ff' },
    ],
    players: [
      P('c1', 'C1', 'Central circulator', 'attack', [
        [0, 8, -16, 'receive'],
        [1.2, 6, -17, 'pass'],
        [5, 2, -22, 'jog'],
        [10, -2, -32, 'run'],
      ]),
      P('c2', 'C2', 'Switching player', 'attack', [
        [0, -2, -20, 'scan'],
        [1.6, -2, -20, 'receive'],
        [2.6, -3, -21, 'pass'],
        [6, -4, -28, 'run'],
        [10, -6, -38, 'run'],
      ]),
      P('lw', 'LW', 'Wide receiver', 'attack', [
        [0, -30, -22, 'idle'],
        [2.6, -30, -23, 'idle'],
        [4, -30, -26, 'receive'],
        [5.4, -29, -33, 'dribble'],
        [6.6, -28, -40, 'dribble'],
        [7.6, -27, -44, 'cross'],
        [10, -26, -46, 'jog'],
      ]),
      P('lb', 'LB', 'Supporting fullback', 'attack', [
        [0, -22, -14, 'idle'],
        [4, -24, -22, 'jog'],
        [6, -31, -30, 'sprint'],
        [10, -30, -42, 'run'],
      ]),
      P('np', 'NP', 'Near post arrival', 'attack', [
        [0, -6, -32, 'idle'],
        [4.6, -5, -35, 'jog'],
        [7.8, -10, -46, 'sprint'],
        [8.6, -9, -47, 'header'],
        [10, -8, -47.5, 'jog'],
      ]),
      P('ps', 'PS', 'Penalty spot arrival', 'attack', [
        [0, 2, -30, 'idle'],
        [5, 3, -34, 'jog'],
        [8.2, 0, -41.5, 'sprint'],
        [9.2, -1, -43, 'shoot'],
        [10, -1, -44, 'jog'],
      ]),
      P('bp', 'BP', 'Back post arrival', 'attack', [
        [0, 14, -32, 'idle'],
        [5.4, 12, -36, 'jog'],
        [8.6, 6, -46, 'sprint'],
        [10, 5, -47, 'jog'],
      ]),
      P('d1', 'D1', 'Shifted defender', 'defense', [
        [0, 10, -20, 'press'],
        [3, 4, -22, 'sprint'],
        [6, -10, -28, 'sprint'],
        [10, -18, -40, 'run'],
      ]),
      P('d2', 'D2', 'Channel defender', 'defense', [
        [0, -24, -26, 'idle'],
        [3.6, -28, -26, 'jockey'],
        [5.6, -28, -34, 'jockey'],
        [7.6, -27, -43, 'press'],
        [10, -26, -46, 'jog'],
      ]),
      P('d3', 'D3', 'Box defender', 'defense', [
        [0, -2, -38, 'idle'],
        [5, -3, -40, 'jockey'],
        [8.4, -8, -46, 'run'],
        [10, -7, -47, 'jog'],
      ]),
      P('d4', 'D4', 'Box defender', 'defense', [
        [0, 4, -40, 'idle'],
        [5.4, 3, -41, 'jockey'],
        [9, 1, -43, 'block'],
        [10, 1, -44, 'jog'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [6, -3, -50, 'jog'],
        [9.2, -1, -49, 'block'],
        [10, -1, -49.5, 'idle'],
      ]),
    ],
    ball: B([
      [0, 8, -16],
      [1.3, 6, -17],
      [1.7, -2, -20],
      [2.7, -3, -21],
      [4, -30, -25.5, 1.5],
      [5.4, -29, -33],
      [6.6, -28, -40],
      [7.7, -27, -44],
      [9, -1, -43],
      [10, 3.0, -52.7, 0.6],
    ]),
  },

  {
    id: 'pas-d2',
    category: 'Passing',
    group: 'D — Wing play',
    code: 'D2',
    title: 'Wide Triangle Combination',
    style: 'Wing play',
    area: '30m x 25m channel plus the box',
    playerCount: 'Winger, fullback, central midfielder, 2 defenders, 1 GK',
    durationLabel: '15 min',
    description:
      'Three rehearsed combinations from one triangle — overlap, underlap, third man — chosen by reading the defender’s body position, with the winger’s shape disguising the outcome.',
    setup:
      'Three attackers form a triangle on one flank: fullback deep and wide, winger high and wide, midfielder inside.',
    keyPoints: [
      'If the defender shows you outside, the underlap is on. If they press tight inside, the overlap is on.',
      'The disguise is the technical skill — a pass the defender saw coming has failed even if completed.',
      'Fullback makes one run per repetition and commits fully. Call it before it starts.',
      'Third man: the fullback’s run starts before the midfielder receives.',
    ],
    view: 'half',
    duration: 9,
    zones: [{ x: 22, z: -28, w: 25, d: 30, label: 'Working channel' }],
    equipment: [
      { kind: 'mannequin', x: 24, z: -30 },
      { kind: 'mannequin', x: 16, z: -36 },
    ],
    players: [
      P('rw', 'RW', 'Winger', 'attack', [
        [0, 29, -22, 'receive'],
        [1.4, 27, -25, 'dribble'],
        [2.4, 26, -26, 'pass'],
        [5, 24, -32, 'run'],
        [9, 18, -42, 'run'],
      ]),
      P('cm', 'CM', 'Central midfielder', 'attack', [
        [0, 16, -24, 'idle'],
        [2.4, 17, -25, 'jog'],
        [3.2, 17, -26, 'receive'],
        [4, 16, -27, 'pass'],
        [7, 14, -34, 'run'],
        [9, 10, -42, 'run'],
      ]),
      P('rb', 'RB', 'Fullback (third-man overlap)', 'attack', [
        [0, 26, -14, 'idle'],
        [2.6, 27, -20, 'sprint'],
        [4.6, 30, -30, 'receive'],
        [6.4, 29, -40, 'dribble'],
        [7.4, 27, -44, 'cross'],
        [9, 26, -46, 'jog'],
      ]),
      P('st', 'ST', 'Box arrival', 'attack', [
        [0, 8, -32, 'idle'],
        [4, 9, -36, 'jog'],
        [7.4, 6, -45, 'sprint'],
        [8.4, 2, -43, 'shoot'],
        [9, 1, -44, 'jog'],
      ]),
      P('d1', 'D1', 'Marking defender', 'defense', [
        [0, 28, -27, 'jockey'],
        [2.4, 26, -28, 'press'],
        [4.6, 27, -33, 'sprint'],
        [7, 28, -42, 'run'],
        [9, 27, -46, 'jog'],
      ]),
      P('d2', 'D2', 'Covering defender', 'defense', [
        [0, 18, -30, 'idle'],
        [3.4, 17, -29, 'press'],
        [6, 12, -38, 'run'],
        [8.4, 3, -44, 'block'],
        [9, 3, -45, 'jog'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [6, 3, -50, 'jog'],
        [8.4, 1, -49, 'block'],
        [9, 1, -49.5, 'idle'],
      ]),
    ],
    ball: B([
      [0, 29, -22],
      [1.4, 27, -25],
      [2.5, 26, -26],
      [3.2, 17, -26],
      [4.1, 16, -27],
      [4.7, 30, -30],
      [6.4, 29, -40],
      [7.5, 27, -44],
      [8.5, 2.5, -43],
      [9, -3.0, -52.7, 0.6],
    ]),
  },

  {
    id: 'pas-d3',
    category: 'Passing',
    group: 'D — Wing play',
    code: 'D3',
    title: 'Early Cross Passing Sequence',
    style: 'Wing play, direct crossing',
    area: 'Half pitch',
    playerCount: '6 attackers, 4 defenders, 1 GK',
    durationLabel: '12 min',
    description:
      'Driven diagonal to a wide player 30m from goal who scans the box on receiving: two or more runners already moving means cross early, into the space between keeper and defensive line.',
    setup: 'Attackers build from the halfway line. Defenders start deep and compact.',
    keyPoints: [
      'Aim slightly ahead so the wide player arrives facing goal.',
      'Early cross with the laces, driven, roughly 10m from goal between six-yard line and penalty spot.',
      'Two runners must already be moving before the wide player receives.',
      'Cross early when runners are ahead of the ball; carry to the byline when they are not.',
    ],
    simulationNote:
      'Have the coach call the number of runners available at random, so the wide player must genuinely look rather than execute a plan.',
    view: 'half',
    duration: 8,
    players: [
      P('dp', 'DP', 'Deep passer', 'attack', [
        [0, -6, -12, 'receive'],
        [1.2, -4, -13, 'pass'],
        [5, -2, -20, 'jog'],
        [8, 0, -28, 'run'],
      ]),
      P('rw', 'RW', 'Wide player', 'attack', [
        [0, 24, -20, 'idle'],
        [2.2, 26, -26, 'sprint'],
        [3.2, 26, -30, 'receive'],
        [4.2, 25, -33, 'scan'],
        [4.9, 24, -35, 'cross'],
        [8, 22, -40, 'jog'],
      ]),
      P('np', 'NP', 'Near post runner', 'attack', [
        [0, 4, -28, 'run'],
        [3.2, 7, -36, 'sprint'],
        [5.6, 9, -44, 'sprint'],
        [6.2, 8, -45, 'header'],
        [8, 7, -46, 'jog'],
      ]),
      P('bp', 'BP', 'Back post runner', 'attack', [
        [0, -14, -28, 'run'],
        [3.2, -12, -34, 'sprint'],
        [6, -5, -45, 'sprint'],
        [8, -4, -47, 'jog'],
      ]),
      P('ps', 'PS', 'Penalty spot runner', 'attack', [
        [0, -2, -24, 'idle'],
        [3.4, 0, -32, 'jog'],
        [6.4, 0, -41.5, 'sprint'],
        [7.2, -0.5, -43, 'shoot'],
        [8, -0.5, -44, 'jog'],
      ]),
      P('cm', 'CM', 'Support', 'attack', [
        [0, 10, -18, 'idle'],
        [4, 12, -26, 'run'],
        [8, 8, -36, 'run'],
      ]),
      P('d1', 'D1', 'Compact defender', 'defense', [
        [0, 5, -40, 'idle'],
        [3.4, 6, -41, 'jockey'],
        [6, 8, -44, 'run'],
        [8, 7, -46, 'jog'],
      ]),
      P('d2', 'D2', 'Compact defender', 'defense', [
        [0, -4, -41, 'idle'],
        [4, -3, -42, 'jockey'],
        [6.6, -1, -43, 'block'],
        [8, -1, -45, 'jog'],
      ]),
      P('d3', 'D3', 'Tracking fullback', 'defense', [
        [0, 20, -30, 'idle'],
        [3.2, 24, -31, 'press'],
        [5, 22, -36, 'run'],
        [8, 18, -42, 'run'],
      ]),
      P('d4', 'D4', 'Far fullback', 'defense', [
        [0, -16, -34, 'idle'],
        [4, -12, -38, 'run'],
        [8, -6, -45, 'run'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [4.4, 2, -49.5, 'jog'],
        [6.6, -1.5, -48.5, 'block'],
        [8, -1.9, -49, 'idle'],
      ]),
    ],
    ball: B([
      [0, -6, -12],
      [1.3, -4, -13],
      [3.1, 26, -29.5, 1.6],
      [4.2, 25, -33],
      [5, 24, -35],
      [6.4, 0, -41.5, 1.1],
      [7.3, -0.5, -43, 0.3],
      [8, 3.0, -52.7, 0.5],
    ]),
  },

  /* ---------------- Section E: Direct play ---------------- */
  {
    id: 'pas-e1',
    category: 'Passing',
    group: 'E — Direct play and target play',
    code: 'E1',
    title: 'Long Pass Accuracy Under Pressure',
    style: 'Direct play, target play',
    area: '60m x 40m',
    playerCount: '4 passers, 4 receivers, 4 pressers',
    durationLabel: '12 min',
    description:
      'A presser closes within two seconds. Choose the in-behind lofted ball if the runner has started and the space exists, or the driven feet ball if the target is marked but strong.',
    setup:
      'Passers work from a deep zone. Two target zones: one behind the defensive line, one at the feet of a target player.',
    keyPoints: [
      'In-behind: lofted, landing in the space, weighted so the receiver never breaks stride.',
      'Feet ball: driven, flat, firm enough to arrive before the marker reacts.',
      'The runner starts only when the passer’s head comes up.',
      'Leaning back is the most common failure on the lofted ball — high and slow gives defenders time.',
    ],
    view: 'full',
    duration: 9,
    zones: [
      { x: 0, z: 6, w: 40, d: 16, label: 'Passing zone', color: '#ffd84d' },
      { x: -12, z: -38, w: 16, d: 16, label: 'In-behind zone', color: '#8affa0' },
      { x: 12, z: -26, w: 16, d: 14, label: 'Feet zone', color: '#7fd1ff' },
    ],
    players: [
      P('ps', 'PS', 'Passer', 'attack', [
        [0, 0, 8, 'receive'],
        [1, -1, 6, 'scan'],
        [1.8, -2, 5, 'pass'],
        [5, -2, 2, 'jog'],
        [6, -2, 1, 'pass'],
        [9, -2, 0, 'idle'],
      ]),
      P('rn', 'RN', 'Runner — in behind', 'attack', [
        [0, -14, -20, 'idle'],
        [1.2, -14, -24, 'sprint'],
        [3.4, -12, -36, 'receive'],
        [5, -11, -42, 'run'],
        [9, -10, -46, 'jog'],
      ]),
      P('tg', 'TG', 'Target — feet', 'attack', [
        [0, 12, -24, 'idle'],
        [4, 12, -25, 'hold'],
        [6.8, 12, -26, 'receive'],
        [7.8, 11, -27, 'layoff'],
        [9, 10, -29, 'jog'],
      ]),
      P('sp', 'SP', 'Support', 'attack', [
        [0, 4, -18, 'idle'],
        [5, 6, -22, 'jog'],
        [8, 8, -28, 'run'],
        [9, 8, -31, 'receive'],
      ]),
      P('x1', 'X1', 'Presser', 'defense', [
        [0, 0, -6, 'sprint'],
        [1.8, -2, 2, 'press'],
        [4, 0, -2, 'jog'],
        [6, -2, 0, 'press'],
        [9, -2, -4, 'jog'],
      ]),
      P('x2', 'X2', 'In-behind defender', 'defense', [
        [0, -10, -28, 'idle'],
        [2.4, -11, -33, 'sprint'],
        [4, -12, -38, 'run'],
        [9, -11, -45, 'run'],
      ]),
      P('x3', 'X3', 'Marker on the target', 'defense', [
        [0, 13, -27, 'idle'],
        [4, 12.6, -26.5, 'press'],
        [7.4, 12, -27.5, 'tackle'],
        [9, 11, -30, 'run'],
      ]),
    ],
    ball: B([
      [0, 0, 8],
      [1, -1, 6],
      [3.4, -12, -36, 0.5],
      [4.6, -11, -40],
      [5.6, -2, 2],
      [6.8, 12, -26, 0.9],
      [7.9, 11, -27],
      [9, 8, -31],
    ]),
  },

  {
    id: 'pas-e2',
    category: 'Passing',
    group: 'E — Direct play and target play',
    code: 'E2',
    title: 'Second Ball Passing',
    style: 'Direct play, target play',
    area: '40m x 35m',
    playerCount: '8v8 with a goalkeeper serving long',
    durationLabel: '12 min',
    description:
      'A long serve creates a contested aerial duel; three players per team form a triangle around it and the first touch after winning goes forward or wide, never square.',
    setup:
      'The goalkeeper or a coach plays a long ball to a contested aerial duel. Both teams compete for the second ball.',
    keyPoints: [
      'Attack the ball — a jump from a run beats a jump from standing.',
      'Head or chest into a planned area; nominate the direction before the serve.',
      'Triangle around the duel: one behind, one either side. Move as the ball travels.',
      'One touch where possible — second balls are chaotic and the extra touch is punished.',
    ],
    simulationNote:
      'Vary the serve: flat and driven, high and hanging, to the near or far shoulder. Each produces a different second-ball area.',
    view: 'grid',
    duration: 8,
    zones: [{ x: 0, z: -26, w: 35, d: 40, label: '40m x 35m' }],
    players: [
      P('sv', 'SV', 'Server', 'gk', [
        [0, 0, -4, 'idle'],
        [0.9, 0, -5, 'pass'],
        [8, 0, -6, 'idle'],
      ]),
      P('a1', 'A1', 'Aerial contester', 'attack', [
        [0, 0, -26, 'idle'],
        [1.6, -1, -24, 'run'],
        [2.6, -1.5, -23, 'header'],
        [5, -3, -26, 'jog'],
        [8, -4, -30, 'jog'],
      ]),
      P('a2', 'A2', 'Triangle — behind', 'attack', [
        [0, -1, -32, 'idle'],
        [2.2, -3, -30, 'run'],
        [3.4, -5, -28, 'receive'],
        [4.2, -6, -29, 'pass'],
        [8, -8, -34, 'run'],
      ]),
      P('a3', 'A3', 'Triangle — side', 'attack', [
        [0, -10, -25, 'idle'],
        [2.4, -9, -27, 'run'],
        [4.4, -11, -30, 'receive'],
        [5.4, -12, -32, 'pass'],
        [8, -13, -38, 'run'],
      ]),
      P('a4', 'A4', 'Forward outlet', 'attack', [
        [0, -14, -36, 'idle'],
        [4, -15, -38, 'jog'],
        [5.8, -15, -40, 'receive'],
        [8, -14, -44, 'run'],
      ]),
      P('b1', 'B1', 'Aerial contester', 'defense', [
        [0, 1, -28, 'idle'],
        [1.8, 0.5, -25, 'run'],
        [2.6, 0.5, -23.5, 'header'],
        [5, 2, -27, 'run'],
        [8, 3, -32, 'run'],
      ]),
      P('b2', 'B2', 'Triangle — behind', 'defense', [
        [0, 3, -33, 'idle'],
        [2.4, 1, -31, 'run'],
        [4.4, -3, -30, 'press'],
        [8, -6, -36, 'run'],
      ]),
      P('b3', 'B3', 'Triangle — side', 'defense', [
        [0, 9, -24, 'idle'],
        [2.6, 6, -26, 'run'],
        [5, -6, -30, 'sprint'],
        [8, -10, -38, 'run'],
      ]),
      P('b4', 'B4', 'Cover', 'defense', [
        [0, 6, -38, 'idle'],
        [4, 2, -38, 'jog'],
        [8, -8, -42, 'run'],
      ]),
    ],
    ball: B([
      [0, 0, -5],
      [2.5, -1, -23.5, 2.9],
      [3.4, -5, -28, 0.6],
      [4.3, -6, -29],
      [4.4, -11, -30],
      [5.5, -12, -32],
      [5.8, -15, -40],
      [8, -14, -44],
    ]),
  },

  {
    id: 'pas-e3',
    category: 'Passing',
    group: 'E — Direct play and target play',
    code: 'E3',
    title: 'Set and Go Passing',
    style: 'Direct play, target play',
    area: '50m x 30m',
    playerCount: '6v4',
    durationLabel: '12 min',
    description:
      'Build short or go direct — the trigger is defined: if the target has separation from their marker, play direct, one-touch lay-off, forward pass. Three passes to the final third.',
    setup:
      'A target player at the top of the area. Attackers build from deep with the option of going direct at any moment.',
    keyPoints: [
      'The direct pass is firm, into the body or feet, along the ground or driven.',
      'The target signals with a raised arm and a call, and never turns.',
      'Two runners arrive: one past the target’s shoulder, one into the space beyond.',
      'Start the run as the direct pass is struck, not when the target receives.',
    ],
    view: 'half',
    duration: 8,
    zones: [{ x: 0, z: -26, w: 30, d: 50, label: '50m x 30m' }],
    players: [
      P('dp', 'DP', 'Deep player', 'attack', [
        [0, -4, -8, 'receive'],
        [1.2, -3, -10, 'scan'],
        [2, -2, -11, 'pass'],
        [5, -1, -18, 'run'],
        [8, 0, -26, 'run'],
      ]),
      P('tp', 'TP', 'Target player', 'attack', [
        [0, 0, -32, 'idle'],
        [2, 0, -31, 'hold'],
        [3.4, 0, -31.5, 'receive'],
        [4.2, -1, -32, 'layoff'],
        [6, 1, -35, 'jog'],
        [8, 2, -38, 'jog'],
      ]),
      P('r1', 'R1', 'Runner — past the shoulder', 'attack', [
        [0, -8, -20, 'idle'],
        [2.2, -7, -25, 'sprint'],
        [4.4, -4, -33, 'receive'],
        [5.6, -3, -38, 'dribble'],
        [6.6, -2, -41, 'pass'],
        [8, -2, -43, 'jog'],
      ]),
      P('r2', 'R2', 'Runner — space beyond', 'attack', [
        [0, 7, -20, 'idle'],
        [2.4, 8, -26, 'sprint'],
        [5.4, 8, -36, 'sprint'],
        [6.8, 4, -42, 'receive'],
        [7.6, 2, -44, 'shoot'],
        [8, 1, -45, 'jog'],
      ]),
      P('sp', 'SP', 'Support', 'attack', [
        [0, 4, -12, 'idle'],
        [4, 4, -18, 'jog'],
        [8, 3, -28, 'run'],
      ]),
      P('d1', 'D1', 'Marker', 'defense', [
        [0, 0.5, -34, 'idle'],
        [2.4, 0.4, -33, 'press'],
        [4.2, -0.4, -33.5, 'tackle'],
        [6, -2, -37, 'run'],
        [8, -2, -41, 'run'],
      ]),
      P('d2', 'D2', 'Cover', 'defense', [
        [0, -6, -30, 'idle'],
        [3, -6, -31, 'jockey'],
        [5.4, -4, -37, 'run'],
        [8, 0, -44, 'block'],
      ]),
      P('d3', 'D3', 'Cover', 'defense', [
        [0, 8, -30, 'idle'],
        [3.4, 8, -32, 'jockey'],
        [6, 7, -40, 'run'],
        [8, 4, -45, 'run'],
      ]),
      P('d4', 'D4', 'Deep cover', 'defense', [
        [0, 0, -42, 'idle'],
        [5, 2, -43, 'jog'],
        [8, 1, -46, 'block'],
      ]),
    ],
    ball: B([
      [0, -4, -8],
      [1.2, -3, -10],
      [3.3, 0, -31.4],
      [4.3, -4, -33],
      [5.6, -3, -38],
      [6.7, -2, -41],
      [6.9, 4, -42],
      [7.7, 2, -44],
      [8, -3.0, -52.7, 0.5],
    ]),
  },

  /* ---------------- Section F: Total football ---------------- */
  {
    id: 'pas-f1',
    category: 'Passing',
    group: 'F — Total football and rotation',
    code: 'F1',
    title: 'Rotating Positions Passing Circuit',
    style: 'Total football, rotation',
    area: '40m x 40m',
    playerCount: '8 in a positional shape',
    durationLabel: '12 min',
    description:
      'Run the team’s build-up pattern, then every player rotates one position clockwise so each learns the passing responsibility of every position.',
    setup:
      'Set up a passing pattern replicating your build-up shape. After every completed pattern, everyone rotates one position clockwise.',
    keyPoints: [
      'Each position verbalises its responsibility before receiving: "I switch", "I play forward", "I set back".',
      'Centre back: split, pass forward or switch, never square across the middle.',
      'DM: receive on the half turn, always face across.',
      'Players who only ever play one position develop one passing habit.',
    ],
    view: 'grid',
    duration: 10,
    zones: [{ x: 0, z: -24, w: 40, d: 40, label: '40m x 40m' }],
    players: [
      P('cb1', 'CB', 'Centre back', 'attack', [
        [0, -12, -8, 'pass'],
        [3, -11, -10, 'jog'],
        [7, -10, -14, 'jog'],
        [10, -9, -18, 'jog'],
      ]),
      P('cb2', 'CB', 'Centre back', 'attack', [
        [0, 12, -8, 'idle'],
        [4, 11, -10, 'jog'],
        [10, 10, -14, 'jog'],
      ]),
      P('dm', 'DM', 'Defensive midfielder', 'attack', [
        [0, 0, -16, 'scan'],
        [1.4, 0.5, -16.5, 'receive'],
        [2.4, 1, -17, 'pass'],
        [6, 2, -20, 'jog'],
        [10, 3, -24, 'jog'],
      ]),
      P('rb', 'RB', 'Fullback', 'attack', [
        [0, 17, -18, 'idle'],
        [2.9, 17, -19, 'receive'],
        [3.8, 16, -20, 'pass'],
        [7, 16, -26, 'run'],
        [10, 15, -30, 'jog'],
      ]),
      P('rw', 'RW', 'Winger', 'attack', [
        [0, 18, -30, 'idle'],
        [4.4, 18, -30, 'receive'],
        [5.2, 17, -31, 'pass'],
        [8, 16, -34, 'jog'],
        [10, 15, -36, 'jog'],
      ]),
      P('if', 'IF', 'Inside forward', 'attack', [
        [0, 7, -32, 'scan'],
        [5.8, 7, -33, 'receive'],
        [6.6, 6, -34, 'pass'],
        [9, 5, -38, 'run'],
        [10, 4, -40, 'jog'],
      ]),
      P('st', 'ST', 'Striker', 'attack', [
        [0, 0, -38, 'idle'],
        [6.6, 0, -38, 'hold'],
        [7.4, -0.5, -38.5, 'receive'],
        [8.2, -1, -39, 'layoff'],
        [10, -2, -41, 'jog'],
      ]),
      P('lw', 'LW', 'Far winger', 'attack', [
        [0, -18, -30, 'idle'],
        [8.4, -17, -31, 'jog'],
        [9.2, -16, -32, 'receive'],
        [10, -15, -33, 'jog'],
      ]),
    ],
    ball: B([
      [0, -12, -8],
      [1.4, 0.5, -16.5],
      [2.4, 1, -17],
      [2.9, 17, -19],
      [3.8, 16, -20],
      [4.4, 18, -30],
      [5.2, 17, -31],
      [5.8, 7, -33],
      [6.6, 6, -34],
      [7.4, -0.5, -38.5],
      [8.2, -1, -39],
      [9.2, -16, -32],
      [10, -15, -33],
    ]),
  },

  {
    id: 'pas-f2',
    category: 'Passing',
    group: 'F — Total football and rotation',
    code: 'F2',
    title: 'Free Rotation Possession with Zone Rules',
    style: 'Total football, rotation',
    area: '40m x 35m with 5 marked zones',
    playerCount: '8v8',
    durationLabel: '15 min',
    description:
      'If a teammate enters your zone you must leave it. The ball carrier stays; everyone else rotates. A point for a completed pass to a player who has just rotated in.',
    setup:
      'Five zones marked. No more than two players from the same team per zone, and each zone must hold at least one possession player.',
    keyPoints: [
      'Pass to the zone, not to the name — the player in the space is the option, whoever they are.',
      'Scan for the rotation before receiving; the picture changes every 2 seconds.',
      'Call loudly as you enter a new zone, and enter facing the ball with an open body.',
      'Two players entering the same zone is the standard failure of rotation systems.',
    ],
    view: 'grid',
    duration: 10,
    zones: [
      { x: -14, z: -14, w: 12, d: 18, color: '#7fd1ff' },
      { x: 0, z: -14, w: 12, d: 18, color: '#ffd84d' },
      { x: 14, z: -14, w: 12, d: 18, color: '#7fd1ff' },
      { x: -7, z: -33, w: 18, d: 18, color: '#ffd84d' },
      { x: 11, z: -33, w: 18, d: 18, color: '#7fd1ff' },
    ],
    players: [
      P('r1', 'R1', 'Rotating player', 'attack', [
        [0, -14, -14, 'receive'],
        [1.2, -13, -15, 'pass'],
        [4, -6, -18, 'run'],
        [7, 0, -14, 'run'],
        [10, 4, -12, 'jog'],
      ]),
      P('r2', 'R2', 'Rotating player', 'attack', [
        [0, 0, -12, 'idle'],
        [1.4, 0, -13, 'receive'],
        [2.4, 1, -14, 'pass'],
        [5, 8, -20, 'run'],
        [8, 12, -30, 'run'],
        [10, 13, -34, 'idle'],
      ]),
      P('r3', 'R3', 'Rotating player', 'attack', [
        [0, 14, -16, 'idle'],
        [2.6, 14, -16, 'receive'],
        [3.6, 13, -17, 'pass'],
        [6, 4, -24, 'run'],
        [10, -4, -30, 'run'],
      ]),
      P('r4', 'R4', 'Rotating player', 'attack', [
        [0, -8, -32, 'idle'],
        [3.8, -7, -31, 'receive'],
        [4.8, -6, -32, 'pass'],
        [8, -12, -22, 'run'],
        [10, -14, -16, 'jog'],
      ]),
      P('r5', 'R5', 'Rotating player', 'attack', [
        [0, 12, -34, 'idle'],
        [5, 11, -33, 'receive'],
        [6, 10, -34, 'pass'],
        [9, 2, -34, 'run'],
        [10, 0, -32, 'jog'],
      ]),
      P('r6', 'R6', 'Rotating into space', 'attack', [
        [0, 4, -26, 'idle'],
        [4, -2, -22, 'run'],
        [6.4, -8, -18, 'receive'],
        [7.4, -9, -19, 'pass'],
        [10, -12, -26, 'run'],
      ]),
      P('x1', 'X1', 'Defender', 'defense', [
        [0, -10, -16, 'press'],
        [3, 4, -16, 'sprint'],
        [6, -2, -26, 'press'],
        [10, -8, -22, 'run'],
      ]),
      P('x2', 'X2', 'Defender', 'defense', [
        [0, 6, -18, 'idle'],
        [3.4, 12, -20, 'press'],
        [6.4, 8, -30, 'sprint'],
        [10, 2, -32, 'run'],
      ]),
      P('x3', 'X3', 'Defender', 'defense', [
        [0, -4, -30, 'idle'],
        [4, -8, -30, 'press'],
        [7, -2, -20, 'sprint'],
        [10, -6, -18, 'press'],
      ]),
      P('x4', 'X4', 'Defender', 'defense', [
        [0, 10, -28, 'idle'],
        [4.4, 6, -26, 'jog'],
        [8, 12, -32, 'press'],
        [10, 8, -30, 'run'],
      ]),
    ],
    ball: B([
      [0, -14, -14],
      [1.3, 0, -13],
      [2.5, 1, -14],
      [2.6, 14, -16],
      [3.7, 13, -17],
      [3.8, -7, -31],
      [4.9, -6, -32],
      [5, 11, -33],
      [6.1, 10, -34],
      [6.4, -8, -18],
      [7.5, -9, -19],
      [10, -12, -26],
    ]),
  },

  {
    id: 'pas-f3',
    category: 'Passing',
    group: 'F — Total football and rotation',
    code: 'F3',
    title: 'Blind Side Passing',
    style: 'Total football, rotation',
    area: '35m x 30m into a goal',
    playerCount: '6 attackers, 4 defenders, 1 GK',
    durationLabel: '12 min',
    description:
      'A decoy moves the defender’s eyes while a late diagonal run arrives from behind their shoulder; the passer looks at one option and plays the other.',
    setup:
      'Attackers build in front of a defensive line. Runners are instructed to arrive from behind the defenders’ shoulders.',
    keyPoints: [
      'Look at one option, pass to another — disguise is the technical requirement.',
      'The blind side run appears late; you must have seen it during your scan.',
      'Runners move when the defender’s head turns toward the ball.',
      'The run is diagonal, crossing the defender’s path so they must turn their whole body.',
    ],
    view: 'half',
    duration: 8,
    players: [
      P('ps', 'PS', 'Passer', 'attack', [
        [0, 0, -20, 'receive'],
        [1.4, -1, -22, 'scan'],
        [2.6, -2, -23, 'pass'],
        [5, -2, -28, 'run'],
        [8, -3, -34, 'run'],
      ]),
      P('dc', 'DC', 'Decoy runner', 'attack', [
        [0, -10, -26, 'idle'],
        [1.6, -13, -30, 'sprint'],
        [3.4, -16, -36, 'sprint'],
        [8, -14, -42, 'run'],
      ]),
      P('bs', 'BS', 'Blind side runner', 'attack', [
        [0, 12, -28, 'idle'],
        [1.8, 12, -29, 'idle'],
        [2.4, 11, -31, 'sprint'],
        [4, 4, -38, 'receive'],
        [5.4, 1, -42, 'shoot'],
        [8, 0, -44, 'jog'],
      ]),
      P('sp1', 'S1', 'Support', 'attack', [
        [0, 6, -20, 'idle'],
        [4, 6, -26, 'jog'],
        [8, 5, -34, 'run'],
      ]),
      P('sp2', 'S2', 'Support', 'attack', [
        [0, -6, -18, 'idle'],
        [4, -6, -22, 'jog'],
        [8, -6, -30, 'run'],
      ]),
      P('d1', 'D1', 'Defensive line', 'defense', [
        [0, 8, -33, 'idle'],
        [2, 6, -33, 'jockey'],
        [3.6, 2, -34, 'run'],
        [5.4, 2, -40, 'run'],
        [8, 2, -43, 'jog'],
      ]),
      P('d2', 'D2', 'Defensive line', 'defense', [
        [0, -2, -33, 'idle'],
        [2.2, -5, -33, 'jockey'],
        [4, -9, -34, 'sprint'],
        [8, -10, -40, 'run'],
      ]),
      P('d3', 'D3', 'Defensive line', 'defense', [
        [0, -12, -33, 'idle'],
        [3, -14, -34, 'jockey'],
        [8, -15, -40, 'run'],
      ]),
      P('d4', 'D4', 'Defensive line', 'defense', [
        [0, 15, -33, 'idle'],
        [3.4, 13, -34, 'jockey'],
        [6, 7, -40, 'sprint'],
        [8, 5, -43, 'run'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [4, 1, -49.5, 'jog'],
        [5.6, 1.6, -48.5, 'block'],
        [8, 1.9, -49, 'idle'],
      ]),
    ],
    ball: B([
      [0, 0, -20],
      [1.4, -1, -22],
      [2.7, -2, -23],
      [4, 4, -38],
      [5.5, 1, -42],
      [8, -3.0, -52.7, 0.7],
    ]),
  },

  /* ---------------- Section G: Combined understanding ---------------- */
  {
    id: 'pas-g1',
    category: 'Passing',
    group: 'G — Combined understanding drills',
    code: 'G1',
    title: 'Scanning Score Game',
    style: 'Perception, game understanding',
    area: '40m x 35m',
    playerCount: '8v8',
    durationLabel: '10 min',
    description:
      'Normal two-touch possession. At random moments the coach shouts a player’s name and that player must immediately call the current board colour or number.',
    setup:
      'A coach stands outside the area holding numbered or coloured boards, changing them every few seconds.',
    keyPoints: [
      'Correct answer scores for their team; incorrect scores for the opposition.',
      'Target roughly 4 to 6 scans in the 10 seconds before receiving.',
      'The valuable scan is over the shoulder away from the ball — the ball side is already visible.',
      'Makes the habit conscious before it becomes automatic.',
    ],
    view: 'grid',
    duration: 9,
    zones: [{ x: 0, z: -24, w: 35, d: 40, label: '40m x 35m' }],
    players: [
      P('coach', 'C', 'Coach with boards', 'neutral', [
        [0, 20, -24, 'idle'],
        [4, 20, -22, 'jog'],
        [9, 20, -26, 'idle'],
      ]),
      P('a1', 'A1', 'Possession', 'attack', [
        [0, -8, -12, 'receive'],
        [1.2, -7, -14, 'pass'],
        [4, -4, -18, 'run'],
        [9, 0, -24, 'run'],
      ]),
      P('a2', 'A2', 'Possession (scanning)', 'attack', [
        [0, 4, -18, 'scan'],
        [1.4, 4, -19, 'receive'],
        [2.4, 5, -20, 'pass'],
        [5, 2, -26, 'run'],
        [9, -2, -32, 'run'],
      ]),
      P('a3', 'A3', 'Possession', 'attack', [
        [0, -6, -28, 'idle'],
        [2.6, -5, -28, 'receive'],
        [3.6, -4, -29, 'pass'],
        [7, -6, -22, 'run'],
        [9, -8, -18, 'jog'],
      ]),
      P('a4', 'A4', 'Possession', 'attack', [
        [0, 8, -32, 'idle'],
        [3.8, 8, -31, 'receive'],
        [4.8, 7, -32, 'pass'],
        [9, 10, -36, 'run'],
      ]),
      P('a5', 'A5', 'Possession', 'attack', [
        [0, -12, -36, 'idle'],
        [5, -11, -34, 'receive'],
        [6, -10, -33, 'pass'],
        [9, -8, -30, 'run'],
      ]),
      P('b1', 'B1', 'Pressing', 'defense', [
        [0, -4, -14, 'press'],
        [2.4, 2, -18, 'sprint'],
        [5, -4, -28, 'press'],
        [9, -8, -34, 'run'],
      ]),
      P('b2', 'B2', 'Pressing', 'defense', [
        [0, 6, -24, 'idle'],
        [3, 6, -30, 'press'],
        [6, -2, -32, 'sprint'],
        [9, -6, -28, 'run'],
      ]),
      P('b3', 'B3', 'Pressing', 'defense', [
        [0, -10, -24, 'idle'],
        [4, -8, -30, 'press'],
        [7, -12, -34, 'press'],
        [9, -10, -30, 'run'],
      ]),
      P('b4', 'B4', 'Pressing', 'defense', [
        [0, 10, -20, 'idle'],
        [4.4, 9, -28, 'run'],
        [9, 6, -34, 'run'],
      ]),
    ],
    ball: B([
      [0, -8, -12],
      [1.3, 4, -19],
      [2.5, 5, -20],
      [2.6, -5, -28],
      [3.7, -4, -29],
      [3.8, 8, -31],
      [4.9, 7, -32],
      [5, -11, -34],
      [6.1, -10, -33],
      [9, -8, -30],
    ]),
  },

  {
    id: 'pas-g2',
    category: 'Passing',
    group: 'G — Combined understanding drills',
    code: 'G2',
    title: 'Restricted Vision Passing',
    style: 'Perception, game understanding',
    area: '30m x 25m',
    playerCount: '6v4',
    durationLabel: '10 min',
    description:
      'Players may scan freely before receiving, but must keep their eyes on the ball from first touch until the pass is played — forcing a mental map instead of a final look.',
    setup:
      'Normal possession. A rule prevents the player from looking up in the final moment before passing. One-touch passing is exempt.',
    keyPoints: [
      'Error rates rise. That is intended — the learning happens in the discomfort.',
      'Forces players to know where teammates are before the ball arrives.',
      'After each block, ask whether they scanned more. They will have.',
      'Remove the restriction and check whether the increased scanning persists.',
    ],
    view: 'grid',
    duration: 8,
    zones: [{ x: 0, z: -22, w: 25, d: 30, label: '30m x 25m' }],
    players: [
      P('a1', 'A1', 'Possession', 'attack', [
        [0, -8, -12, 'scan'],
        [1, -8, -13, 'receive'],
        [2, -7, -14, 'pass'],
        [5, -4, -18, 'run'],
        [8, -2, -24, 'run'],
      ]),
      P('a2', 'A2', 'Possession', 'attack', [
        [0, 5, -16, 'idle'],
        [2.2, 5, -17, 'receive'],
        [3, 6, -18, 'pass'],
        [6, 4, -24, 'run'],
        [8, 2, -28, 'jog'],
      ]),
      P('a3', 'A3', 'Possession', 'attack', [
        [0, -2, -26, 'scan'],
        [3.2, -2, -26, 'receive'],
        [4.2, -1, -27, 'pass'],
        [8, 2, -32, 'run'],
      ]),
      P('a4', 'A4', 'Possession', 'attack', [
        [0, 9, -28, 'idle'],
        [4.4, 8, -28, 'receive'],
        [5.4, 7, -29, 'pass'],
        [8, 6, -32, 'jog'],
      ]),
      P('a5', 'A5', 'Possession', 'attack', [
        [0, -10, -22, 'idle'],
        [5.6, -9, -22, 'receive'],
        [6.6, -8, -23, 'pass'],
        [8, -6, -26, 'jog'],
      ]),
      P('a6', 'A6', 'Possession', 'attack', [
        [0, 0, -18, 'idle'],
        [6.6, 0, -19, 'jog'],
        [7.4, 0, -20, 'receive'],
        [8, 0, -21, 'idle'],
      ]),
      P('b1', 'B1', 'Defender', 'defense', [
        [0, -5, -14, 'press'],
        [2.4, 2, -17, 'sprint'],
        [5, 6, -27, 'press'],
        [8, -2, -24, 'run'],
      ]),
      P('b2', 'B2', 'Defender', 'defense', [
        [0, 4, -22, 'idle'],
        [3.4, -1, -24, 'press'],
        [6, -7, -24, 'press'],
        [8, -4, -22, 'run'],
      ]),
      P('b3', 'B3', 'Defender', 'defense', [
        [0, -6, -28, 'idle'],
        [4, -4, -26, 'jog'],
        [7, 0, -22, 'press'],
        [8, 1, -21, 'press'],
      ]),
      P('b4', 'B4', 'Defender', 'defense', [
        [0, 8, -18, 'idle'],
        [4, 9, -24, 'jog'],
        [8, 5, -26, 'run'],
      ]),
    ],
    ball: B([
      [0, -8, -12],
      [1, -8, -13],
      [2.1, -7, -14],
      [2.2, 5, -17],
      [3.1, 6, -18],
      [3.2, -2, -26],
      [4.3, -1, -27],
      [4.4, 8, -28],
      [5.5, 7, -29],
      [5.6, -9, -22],
      [6.7, -8, -23],
      [7.4, 0, -20],
      [8, 0, -21],
    ]),
  },

  {
    id: 'pas-g3',
    category: 'Passing',
    group: 'G — Combined understanding drills',
    code: 'G3',
    title: 'Decision Constraint Game',
    style: 'Perception, game understanding',
    area: 'Half pitch',
    playerCount: '9v9',
    durationLabel: '15 min · constraint changes every 3 min',
    description:
      'A normal game where the coach changes the constraint every three minutes without warning — every possession must include a switch, two touches, first-time assists, backward-then-forward — then free play.',
    setup: 'Normal game on half a pitch. Constraints rotate through five blocks.',
    keyPoints: [
      'Block 1: every possession must include a switch of play.',
      'Block 2: two touches maximum for everyone.',
      'Block 3: a goal only counts if the assist was a first-time pass.',
      'Block 5 (free play) is the most important — observe whether the behaviours persist.',
    ],
    view: 'half',
    duration: 12,
    players: [
      P('a1', 'A1', 'Team A', 'attack', [
        [0, -20, -12, 'receive'],
        [1.4, -19, -14, 'pass'],
        [5, -14, -20, 'run'],
        [9, -8, -28, 'run'],
        [12, -6, -34, 'jog'],
      ]),
      P('a2', 'A2', 'Team A (switch)', 'attack', [
        [0, -4, -18, 'scan'],
        [1.8, -4, -19, 'receive'],
        [2.8, -3, -20, 'pass'],
        [6, 2, -26, 'run'],
        [12, 6, -36, 'run'],
      ]),
      P('a3', 'A3', 'Team A', 'attack', [
        [0, 22, -20, 'idle'],
        [4, 22, -22, 'receive'],
        [5.2, 21, -26, 'dribble'],
        [6.4, 20, -28, 'pass'],
        [12, 16, -38, 'run'],
      ]),
      P('a4', 'A4', 'Team A (first-time assist)', 'attack', [
        [0, 10, -26, 'idle'],
        [5.6, 11, -28, 'jog'],
        [6.6, 11, -29, 'receive'],
        [7.4, 10, -30, 'pass'],
        [12, 8, -38, 'run'],
      ]),
      P('a5', 'A5', 'Team A (finisher)', 'attack', [
        [0, 2, -32, 'idle'],
        [6, 3, -34, 'jog'],
        [8, 5, -40, 'sprint'],
        [9, 3, -43, 'shoot'],
        [12, 2, -45, 'jog'],
      ]),
      P('b1', 'B1', 'Team B', 'defense', [
        [0, -14, -16, 'press'],
        [3, -6, -20, 'sprint'],
        [6, 10, -24, 'sprint'],
        [9, 6, -36, 'run'],
        [12, 4, -42, 'jog'],
      ]),
      P('b2', 'B2', 'Team B', 'defense', [
        [0, 4, -24, 'idle'],
        [4, 14, -24, 'press'],
        [7, 18, -30, 'press'],
        [10, 12, -38, 'run'],
        [12, 10, -42, 'jog'],
      ]),
      P('b3', 'B3', 'Team B', 'defense', [
        [0, -8, -28, 'idle'],
        [4, -2, -28, 'jog'],
        [8, 6, -34, 'run'],
        [9.4, 4, -42, 'block'],
        [12, 3, -44, 'jog'],
      ]),
      P('b4', 'B4', 'Team B', 'defense', [
        [0, 14, -32, 'idle'],
        [5, 12, -32, 'jog'],
        [8.4, 8, -38, 'run'],
        [12, 6, -44, 'run'],
      ]),
      P('b5', 'B5', 'Team B', 'defense', [
        [0, -2, -38, 'idle'],
        [6, 0, -38, 'jog'],
        [10, 1, -42, 'run'],
        [12, 0, -45, 'jog'],
      ]),
      P('gk', 'GK', 'Goalkeeper', 'gk', [
        [0, 0, -50.5, 'idle'],
        [7, 1, -49.5, 'jog'],
        [9.2, 3, -48.5, 'block'],
        [12, 2, -49, 'idle'],
      ]),
    ],
    ball: B([
      [0, -20, -12],
      [1.5, -4, -19],
      [2.9, -3, -20],
      [4, 22, -22, 1.8],
      [5.2, 21, -26],
      [6.5, 11, -29],
      [7.5, 10, -30],
      [8, 5, -40],
      [9.1, 3, -43],
      [12, -3.0, -52.7, 0.7],
    ]),
  },
]
