import type { Phase } from '../types'

/**
 * Coaching phases for the attacking manual. Each phase names what the drill
 * is teaching at that moment; `cues` are the one-line instruction a player
 * gets when you hover them, taken from that drill's role instructions.
 */
export const ATTACKING_PHASES: Record<string, Phase[]> = {
  'atk-1': [
    {
      t0: 0,
      t1: 2.9,
      title: 'Carry to commit',
      text: 'Two touches at pace toward the space between the defenders — slow dribbling lets both hold shape and the overload disappears.',
      focus: ['cm', 'cb1', 'cb2'],
      cues: {
        cm: 'Carry at the gap between them, not at a body. Force one to step out.',
        rw: 'Hold maximum width. Coming inside early lets one defender cover two.',
        st: 'Stay on the shoulder. Start the run late — timing beats speed.',
        cb1: 'Press and delay. Do not dive in.',
        cb2: 'Drop and cover the deepest runner. Never both press.',
      },
    },
    {
      t0: 2.9,
      t1: 5.3,
      title: 'Release on the front foot',
      text: 'The trigger is the defender’s weight going forward, not the distance. After passing, the carrier keeps running into the box.',
      focus: ['cm', 'rw', 'st'],
      cues: {
        cm: 'Released. Now continue into the box — a three-man attack must stay three.',
        rw: 'Run started before the pass. Receive on the back foot, first touch into the channel.',
        st: 'Blindside run across the far centre back, into the space behind.',
        cb1: 'Beaten by the release. Recover goal side.',
        cb2: 'Cover the runner, stay on the diagonal.',
      },
    },
    {
      t0: 5.3,
      t1: 7.2,
      title: 'Into the channel',
      text: 'First touch forward into the channel, never square. The striker curves so the last stride faces goal.',
      focus: ['rw', 'st', 'cm'],
      cues: {
        rw: 'Take it forward, get to the byline area rather than the corner.',
        st: 'Curve the run — arrive facing goal, not facing the touchline.',
        cm: 'Arrive late at the edge for the cutback or the rebound.',
      },
    },
    {
      t0: 7.2,
      t1: 8,
      title: 'Finish inside 8 seconds',
      text: 'Target is 70% of repetitions ending with a shot inside eight seconds. The finish goes away from the goalkeeper.',
      focus: ['st', 'gk'],
      cues: {
        st: 'Across the keeper into the far side. Do not shoot at the body.',
        gk: 'Committed near post — the far corner is open.',
      },
    },
  ],

  'atk-2': [
    {
      t0: 0,
      t1: 1.9,
      title: 'Pass to the back foot',
      text: 'Firm, along the ground, into the foot away from the defender. A soft pass gives the defender time to step around and intercept.',
      focus: ['dp', 'st', 'd1'],
      cues: {
        dp: 'Weight it so the striker only has to control, not chase. Call before you play it.',
        st: 'Show half open so the defender cannot see both the ball and the runner.',
        am: 'Ball is travelling — this is when your run starts, not after the lay-off.',
        d1: 'Mark tight from behind, try to nick it in front.',
      },
    },
    {
      t0: 1.9,
      t1: 3.1,
      title: 'Hold, do not turn',
      text: 'The whole drill fails if the striker tries to beat the defender. Hold him off with arm and hips until the lay-off is made.',
      focus: ['st', 'am', 'd1'],
      cues: {
        st: 'Do not turn. Contact with the arm and hips, one touch only.',
        am: 'Curved run so you receive already facing goal.',
        d1: 'Real pressure from behind — the drill has no value passive.',
      },
    },
    {
      t0: 3.1,
      t1: 5,
      title: 'Third man arrives facing goal',
      text: 'One-touch lay-off into the path of the runner, never to his feet. Two touches gives the defence a full second to recover.',
      focus: ['am', 'st'],
      cues: {
        st: 'Into his path, one touch, along the ground.',
        am: 'Receiving on the run and already square to goal.',
      },
    },
    {
      t0: 5,
      t1: 6,
      title: 'Set and strike',
      text: 'One touch to set, second to shoot — unless a clear through ball is available.',
      focus: ['am', 'gk'],
      cues: {
        am: 'Set, then strike across the keeper.',
        gk: 'Beaten to the far side.',
      },
    },
  ],

  'atk-3': [
    {
      t0: 0,
      t1: 2.5,
      title: 'Drag the fullback inside',
      text: 'The winger receives square on, then cuts inside to turn the defender’s hips. That turn is the trigger — not the fullback’s shout.',
      focus: ['rw', 'dfb', 'rb'],
      cues: {
        rw: 'Receive facing him, cut inside, watch his hips.',
        rb: 'Do not overlap yet — too early lets him pass the marking on.',
        dfb: 'Show the winger outside, defend the 1v1 honestly.',
        st: 'Hold central, ready to attack the near post.',
      },
    },
    {
      t0: 2.5,
      t1: 6.2,
      title: 'Release the overlap',
      text: 'Hips turned inside, so the ball goes outside into the run. The winger now becomes a finisher, not a passer.',
      focus: ['rb', 'rw', 'dfb'],
      cues: {
        rb: 'Outside his touchline shoulder, target the byline not the corner flag.',
        rw: 'Released — now run into the box toward the penalty spot.',
        st: 'Attack the near post in front of the centre back.',
        lw: 'Sprint the diagonal — arrive at the back post, not the six-yard box.',
      },
    },
    {
      t0: 6.2,
      t1: 7.2,
      title: 'Byline and cutback',
      text: 'Low and firm with the inside of the foot to the penalty spot area. Never chip — cutbacks convert because the ball moves away from the keeper.',
      focus: ['rb', 'st', 'rw'],
      cues: {
        rb: 'Low, firm, inside of the foot to the penalty spot. Do not chip.',
        st: 'Near post run has dragged the centre back — the cutback lane is open.',
        rw: 'Arriving at the penalty spot as the ball comes back.',
      },
    },
    {
      t0: 7.2,
      t1: 9,
      title: 'Three arrivals',
      text: 'Count the arrivals: near post, penalty spot, back post. Three is the target on every delivery.',
      focus: ['rw', 'st', 'lw', 'gk'],
      cues: {
        rw: 'First-time finish into the open side.',
        lw: 'Back post, in case it runs through.',
        gk: 'Dragged toward the near post by the cutback.',
      },
    },
  ],

  'atk-4': [
    {
      t0: 0,
      t1: 1.4,
      title: 'First pass forward',
      text: 'Never square or backwards in the first three seconds. This single rule is what makes it a counter rather than a possession exercise.',
      focus: ['fr', 'st'],
      cues: {
        fr: 'Scan while the ball travels. One or two touches, forward or diagonally forward.',
        st: 'Possession is won — sprint in behind now, do not check to the ball.',
        lw: 'Wide and forward at the same time.',
        rw: 'Run as hard as the ball-side winger. The far post is the highest value arrival.',
      },
    },
    {
      t0: 1.4,
      t1: 4.5,
      title: 'Stretch the pitch',
      text: 'Width in transition pulls three defenders across. Attackers who slow down when the pass does not come are the most common fault.',
      focus: ['st', 'lw', 'rw'],
      cues: {
        st: 'Even without the ball your run pushes the line back and makes the space.',
        lw: 'Do not check back — that shortens the pitch.',
        rw: 'Far post is your arrival point.',
        cm2: 'Trail 10 to 15m behind. You are the cutback and the second ball.',
      },
    },
    {
      t0: 4.5,
      t1: 8,
      title: 'Carry into the final third',
      text: 'Elite counters reach the final third within six to eight seconds. Maximum four passes before the shot.',
      focus: ['st', 'd1', 'd2'],
      cues: {
        st: 'Drive at the retreating line.',
        d1: 'Delay and drop — force it wide, buy time for recovering players.',
        cm2: 'Stay behind the ball for rest defence.',
      },
    },
    {
      t0: 8,
      t1: 10,
      title: 'Finish inside 10 seconds',
      text: 'Sequence dies at ten seconds. If the defenders win it they counter the other way, which trains the attackers to keep rest defence.',
      focus: ['st', 'gk'],
      cues: {
        st: 'Open side of the net, away from the keeper’s near-post cover.',
        gk: 'Narrowed the near post — the far corner is the target.',
      },
    },
  ],

  'atk-5': [
    {
      t0: 0,
      t1: 3.4,
      title: 'Move the block',
      text: 'The first phase is not about progressing. Split the centre backs and draw the block forward and central so the half-space opens.',
      focus: ['cb1', 'dm', 'dm1'],
      cues: {
        cb1: 'Split wide and pass into the DM. Be patient — move them first.',
        dm: 'Receive on the half turn, always. Facing your own goal wastes it.',
        rw: 'Stay on the touchline. Pin the fullback so the half-space opens.',
        lw: 'Hold the wide lane. Do not come inside yet.',
        ifr: 'Position between their fullback and centre back, between the lines.',
        st: 'Pin both centre backs on the last shoulder.',
        dm1: 'Screen the lane into the inside forward.',
      },
    },
    {
      t0: 3.4,
      t1: 5.6,
      title: 'Receive in the half-space',
      text: 'One pass to switch — two gives the block time to slide. The inside forward receives on the half turn and opens his body toward goal.',
      focus: ['ifr', 'dm', 'st'],
      cues: {
        ifr: 'Back foot, first touch opens you toward goal.',
        dm: 'Single pass across. Two passes and the block resets.',
        st: 'His body is opening — start the spin now, before the ball is played.',
        rw: 'Still wide. If you drift inside the half-space closes.',
      },
    },
    {
      t0: 5.6,
      t1: 7.6,
      title: 'Spin in behind',
      text: 'Options in order: through ball to the striker, pass to the winger for a 1v1, drive at the line. The striker is already moving.',
      focus: ['st', 'ifr', 'dcb1'],
      cues: {
        ifr: 'Facing forward — play the through ball first, before the safe option.',
        st: 'Running onto it, not standing waiting. Alternate the spin direction each rep.',
        dcb1: 'Caught square by the run behind.',
        rw: 'Now attack the box — the wide lane has done its job.',
      },
    },
    {
      t0: 7.6,
      t1: 11,
      title: 'Finish',
      text: 'Reward possession that produces a reception between the lines, even when no goal follows.',
      focus: ['st', 'gk'],
      cues: {
        st: 'Across goal into the open side.',
        gk: 'Committed to the near post.',
      },
    },
  ],

  'atk-6': [
    {
      t0: 0,
      t1: 2.5,
      title: 'Two touches, look once',
      text: 'One touch to set, one to deliver. Look up once, then commit — hesitation lets the defence set.',
      focus: ['cr'],
      cues: {
        cr: 'Two touches maximum. Never into the keeper’s zone within 5m of the line.',
        np: 'Start slow. The explosion comes later.',
        ps: 'Delay half a second — arriving early means the defender is goal side.',
        bp: 'Start wide of the line, outside the far post.',
        ed: 'Hold at the D. Do not enter the box.',
      },
    },
    {
      t0: 2.5,
      t1: 3.9,
      title: 'Three zones, three times',
      text: 'Three arrival points and three arrival times. If two runners arrive at the same place, one defender covers both.',
      focus: ['np', 'ps', 'bp'],
      cues: {
        np: 'In front of the defender, arrive before the ball.',
        ps: 'Curve from the far side so the defender turns his head away from the ball.',
        bp: 'Diagonal inward — a straight run from behind is easy to track.',
        d1: 'Marking the near post zone only.',
        d2: 'Penalty spot is yours. Do not follow the ball with your eyes.',
      },
    },
    {
      t0: 3.9,
      t1: 4.7,
      title: 'Attack the ball',
      text: 'Runs into the box change pace — slow, then explosive. The near post finish is a redirection, not a strike.',
      focus: ['ps', 'np', 'gk'],
      cues: {
        ps: 'Forehead or laces, downward.',
        np: 'Any body part, just change the direction.',
        gk: 'Cannot commit — the delivery sits outside the six-yard box.',
      },
    },
    {
      t0: 4.7,
      t1: 6,
      title: 'Second contact',
      text: 'If it goes past, spin immediately for the rebound. The edge player strikes any clearance first time, low, for a deflection.',
      focus: ['ed', 'np'],
      cues: {
        ed: 'First time, low and on target.',
        np: 'Spin toward the penalty spot for the rebound.',
      },
    },
  ],

  'atk-7': [
    {
      t0: 0,
      t1: 5.6,
      title: 'Circulate',
      text: 'Two touches maximum, bodies open. This is the warm-up phase — the forwards must stay alive and scan the shape.',
      focus: ['p1', 'p2', 'p3', 'p4', 'r1', 'r2', 'r3'],
      cues: {
        p1: 'Two touches, keep it moving, body open.',
        p5: 'Watch for the trigger — you will have to go forward in one touch.',
        f1: 'Do not switch off. Scan the defensive shape while the rondo runs.',
        f2: 'Stay alive. When the trigger comes you go in behind immediately.',
        r1: 'Press honestly, try to win it.',
      },
    },
    {
      t0: 5.6,
      t1: 7.4,
      title: 'Trigger: go forward',
      text: 'The skill being trained is the mental switch from circulating to penetrating. Watch for players who need a full second to change mode.',
      focus: ['p5', 'f1', 'f2'],
      cues: {
        p5: 'Trigger called — forward within one touch.',
        f1: 'Come short. You create the space for the man going in behind.',
        f2: 'Already moving in behind — the pair must not both go short.',
        r1: 'Sprint to recover and defend the attack from behind.',
      },
    },
    {
      t0: 7.4,
      t1: 8.6,
      title: 'One short, one in behind',
      text: 'Their runs must be coordinated, not simultaneous into the same lane. Three join the attack, three hold as rest defence.',
      focus: ['f1', 'f2'],
      cues: {
        f1: 'One-touch lay-off into the run.',
        f2: 'Behind the line, receiving on the move.',
        p6: 'Hold as rest defence. Do not join.',
      },
    },
    {
      t0: 8.6,
      t1: 12,
      title: 'Finish within 8 seconds',
      text: 'Attack must finish within eight seconds of the trigger, otherwise the rep is dead.',
      focus: ['f2', 'gk'],
      cues: {
        f2: 'Open side of the net.',
        gk: 'Committed near — the far corner is free.',
      },
    },
  ],

  'atk-8': [
    {
      t0: 0,
      t1: 4.6,
      title: 'First switch moves the block',
      text: 'Against a low block the aim is not to pass through the middle — it is to make the block move and then attack the gap it leaves.',
      focus: ['dm', 'lw', 'b3'],
      cues: {
        dm: 'Two touches. Slow circulation lets the block reset.',
        lw: 'Stay wide and high. Non-negotiable — width is the only thing that stretches them.',
        rw: 'Hold the far touchline. Both wingers inside at once kills the drill.',
        st: 'Pin both centre backs, occupy the space between them.',
        rd1: 'Rest defence. Never past the halfway line.',
        b3: 'Press the wide man, keep the block compact.',
      },
    },
    {
      t0: 4.6,
      t1: 8.8,
      title: 'Second switch makes the gap',
      text: 'Aim for two switches before attempting penetration. The first moves the block, the second creates the gap.',
      focus: ['cm', 'dm', 'rw', 'rb'],
      cues: {
        cm: 'Look for the reception between the lines before circulating sideways.',
        dm: 'Switch again — lateral movement breaks a low block, not vertical passing.',
        rw: 'Now isolated. Receive facing him and attack 1v1.',
        rb: 'Start the underlap now, before the pass — not after it.',
        b4: 'Pulled across by the second switch.',
      },
    },
    {
      t0: 8.8,
      t1: 10.7,
      title: 'Underlap, not overlap',
      text: 'Against a low block the outside space is already covered — the inside pocket is the valuable one.',
      focus: ['rb', 'rw', 'st'],
      cues: {
        rb: 'Inside him into the half-space. Arrive late into the box.',
        rw: 'Hold the width so the underlap has somewhere to go.',
        st: 'Only drop when a midfielder is running beyond you.',
      },
    },
    {
      t0: 10.7,
      t1: 12,
      title: 'Cutback',
      text: 'A goal from a cutback is worth double, as is a goal within five seconds of a switch.',
      focus: ['rb', 'st', 'gk'],
      cues: {
        rb: 'Low cutback to the penalty spot.',
        st: 'Arriving for the cutback, finish into the open side.',
        gk: 'Pulled to the near post by the cutback angle.',
      },
    },
  ],

  'atk-9': [
    {
      t0: 0,
      t1: 1.9,
      title: 'Signal and deliver',
      text: 'One consistent delivery zone per routine — consistency matters more than variety. Use a visual signal, not a shout.',
      focus: ['tk', 'mt', 'sc'],
      cues: {
        tk: 'Inswinger to the near post or outswinger to the spot. Decide before the run-up.',
        mt: 'Start deep, around the penalty spot or further back.',
        bl: 'Not yet — you move at the moment of delivery, not before.',
        sc: 'Short option, 5m away. If they load the box, change the angle.',
        cc: 'Stay on the halfway line. Never join the box.',
      },
    },
    {
      t0: 1.9,
      t1: 3.3,
      title: 'Block at delivery',
      text: 'The blocker moves into the marker’s path at the moment of delivery. Do not hold, do not touch the ball.',
      focus: ['bl', 'mt', 'd2'],
      cues: {
        bl: 'Into his path now. No holding.',
        mt: 'Curved run, attack at pace — a stationary header rarely beats a defender.',
        d2: 'Man marking, blocked off the runner.',
      },
    },
    {
      t0: 3.3,
      t1: 4.1,
      title: 'Attack the front of the ball',
      text: 'Aim downward toward the far post. Track first contact rate before you track conversion — if you are not winning first contact, the zone is wrong.',
      focus: ['mt', 'd1'],
      cues: {
        mt: 'Front of the ball, headed down and across.',
        d1: 'Zonal — attack anything in your zone.',
      },
    },
    {
      t0: 4.1,
      t1: 6,
      title: 'Second wave',
      text: 'Around a third of set-piece goals come from second contact, so this is not a secondary role.',
      focus: ['sw1', 'sw2', 'ed'],
      cues: {
        sw1: 'Knockdowns and rebounds. Do not jump for the first ball.',
        sw2: 'Cover the six-yard box edge.',
        ed: 'Hold at the D for the clearance, first time and low.',
      },
    },
  ],

  'atk-10': [
    {
      t0: 0,
      t1: 2.6,
      title: 'Receive square on',
      text: 'Facing the defender, not with your back to him. The first touch either goes into space or sets the ball outside your body.',
      focus: ['rw', 'd1'],
      cues: {
        rw: 'Square on. A touch into your feet lets him close you down.',
        d1: 'Delay first, then engage. Show him toward the touchline.',
        rb: 'Run the overlap on every repetition, even when the ball is not coming.',
        st: 'Ready to attack the near post on any successful beat.',
      },
    },
    {
      t0: 2.6,
      t1: 4.6,
      title: 'Slow at 3m',
      text: 'Attacking at full speed makes the change of direction impossible. Slow slightly to force him to plant his feet — that is the moment of decision.',
      focus: ['rw', 'd1', 'rb'],
      cues: {
        rw: 'Slow, watch his feet, one feint only then commit.',
        d1: 'Do not dive in. The drill is designed to be beaten but honest defending makes it useful.',
        rb: 'Call loudly. Your run occupies his peripheral vision.',
      },
    },
    {
      t0: 4.6,
      t1: 7.1,
      title: 'Outside shoulder',
      text: 'Attacking the outside shoulder puts the defender behind you and opens the byline.',
      focus: ['rw', 'rb', 'st'],
      cues: {
        rw: 'Past the outside shoulder, drive to the byline.',
        st: 'Attack the near post now.',
        rb: 'Keep running — the overlap still holds him.',
      },
    },
    {
      t0: 7.1,
      t1: 8,
      title: 'Deliver',
      text: 'Alternate outcomes across reps: beat outside and cross, cut inside and shoot, use the overlap. Always the same one and defenders read it.',
      focus: ['rw', 'st'],
      cues: {
        rw: 'Low cutback rather than a high cross.',
        st: 'Arriving in front of the defender.',
      },
    },
  ],

  'atk-11': [
    {
      t0: 0,
      t1: 2.2,
      title: 'Overload the flank',
      text: 'Crowd one side deliberately. Your job on the ball-side is to be marked, not to receive — the defence shifting across is the point.',
      focus: ['pm', 'rw', 'cm1', 'cm2'],
      cues: {
        pm: 'Receive facing forward. Facing your own goal kills the switch.',
        rw: 'Be marked. Pull the block across.',
        cm1: 'Crowd the flank, occupy a defender.',
        lw: 'Stay behind the nearest defender’s shoulder — hidden, and still.',
        d1: 'Shift toward the ball. This is correct defending, and it makes the space.',
      },
    },
    {
      t0: 2.2,
      t1: 4.4,
      title: 'One-pass diagonal',
      text: 'A block shifts across slower than a ball travels across. Driven and flat at head height beats a high floated ball, which gives them two seconds.',
      focus: ['pm', 'lw'],
      cues: {
        pm: 'One touch to set outside the body, second to hit it. No relay.',
        lw: 'Head is up — start now, so you meet it in stride.',
        d4: 'Caught on the far side, recovering across.',
      },
    },
    {
      t0: 4.4,
      t1: 7.6,
      title: 'Meet it in stride',
      text: 'Aim into the space roughly 10m ahead of the far winger, not at his feet. First touch forward, then attack the fullback or deliver early.',
      focus: ['lw', 'st', 'rw'],
      cues: {
        lw: 'First touch forward into the space, then take him on.',
        st: 'Drift to the far post as the ball travels across.',
        rw: 'Sprint infield — you are now the far post arrival.',
      },
    },
    {
      t0: 7.6,
      t1: 10,
      title: 'Finish within 8 seconds',
      text: 'The delivery usually comes within three seconds of the switch, so be in the box before the winger looks up.',
      focus: ['st', 'gk'],
      cues: {
        st: 'Into the open side.',
        gk: 'Beaten across goal.',
      },
    },
  ],

  'atk-12': [
    {
      t0: 0,
      t1: 1.9,
      title: 'Establish contact first',
      text: 'Feel where the defender is with your arm and back before the ball arrives. Wide base, knees bent — a narrow stance is easily pushed off.',
      focus: ['sv', 'ts', 'd1'],
      cues: {
        sv: 'Vary it: to feet, firm to the chest, lofted to the head. Communicate first.',
        ts: 'Contact made before the ball arrives. Wide base, knees bent.',
        nr: 'Time it so you arrive as he makes contact — not before.',
        fr: 'Attack the space beyond, in behind the defence.',
        d1: 'Push, contest, try to get in front. This drill is worthless passive.',
      },
    },
    {
      t0: 1.9,
      t1: 4.3,
      title: 'Hold for two seconds',
      text: 'The core requirement. Holding the ball for two seconds is what buys the team time to advance.',
      focus: ['ts', 'd1', 'nr'],
      cues: {
        ts: 'Arm across for separation, no pushing. Do not turn.',
        nr: 'Run past his shoulder, on the side away from the defender.',
        d1: 'Real pressure from behind.',
      },
    },
    {
      t0: 4.3,
      t1: 6,
      title: 'Lay off into the path',
      text: 'Outside or sole of the foot, along the ground, into the runner’s path. A lay-off to the feet stops the momentum.',
      focus: ['ts', 'nr', 'fr'],
      cues: {
        ts: 'Along the ground, into space, not to his feet.',
        nr: 'First touch forward, second to shoot or release.',
        fr: 'Become the box arrival if the lay-off goes near.',
      },
    },
    {
      t0: 6,
      t1: 8,
      title: 'Strike',
      text: 'Hold-up play is a physical skill before a technical one. Body position and base width matter more than first touch quality.',
      focus: ['nr', 'gk'],
      cues: {
        nr: 'Low and across into the open corner.',
        gk: 'Narrowed the near side.',
      },
    },
  ],

  'atk-13': [
    {
      t0: 0,
      t1: 1.6,
      title: 'Close within two seconds',
      text: 'Sprint, do not jog. Approach at an angle that shows him toward the touchline or a covered teammate.',
      focus: ['a1', 'b1'],
      cues: {
        a1: 'Close him inside two seconds. Do not tackle yet — force a rushed decision.',
        a2: 'Close the nearest forward passing lane.',
        a3: 'Close the second lane. Do not both press the ball.',
        b1: 'You have just won it — try to break the press.',
      },
    },
    {
      t0: 1.6,
      t1: 3.3,
      title: 'Lanes, not men',
      text: 'In counter-pressing the aim is to remove options, not to shadow bodies. Stand in the cover shadow so your body blocks a pass and you can still press.',
      focus: ['a2', 'a3', 'b1'],
      cues: {
        a2: 'Mark the lane. Body blocks the pass, feet ready to press the receiver.',
        a3: 'Second lane covered.',
        a4: 'Push the line up 10m — compressing space is what makes it work.',
        b1: 'Options disappearing. Forced backward.',
      },
    },
    {
      t0: 3.3,
      t1: 6,
      title: 'Push the line up',
      text: 'The furthest player from the ball becomes the spare defender, and the keeper pushes high to sweep behind a high line.',
      focus: ['a4', 'a5', 'a6', 'gk'],
      cues: {
        a4: 'Line pushed up. Space compressed.',
        a6: 'You are the spare man.',
        gk: 'Push high and sweep — a high line requires it.',
        b3: 'Long ball is their way out. Watch it.',
      },
    },
    {
      t0: 6,
      t1: 8,
      title: 'Six seconds, then drop',
      text: 'If it is not won back in roughly six seconds the correct action is to drop into shape. An unsuccessful press that never stops is how teams concede.',
      focus: ['a1', 'a2', 'a3'],
      cues: {
        a1: 'Window closed — call the reset and drop.',
        a2: 'Stop chasing individually, recover shape.',
      },
    },
  ],

  'atk-14': [
    {
      t0: 0,
      t1: 2.5,
      title: 'Whoever has it, stays',
      text: 'The core rule: the player on the ball holds his zone, the other two rotate. No two attackers in the same zone at any time.',
      focus: ['rw', 'rb', 'im'],
      cues: {
        rw: 'You have it — hold the width and let the others rotate around you.',
        rb: 'Wait for the winger to tuck inside, then take the wide lane.',
        im: 'Read what the other two do and take the empty zone.',
        d1: 'Man or zonal — pick one and stick to it for the whole block.',
      },
    },
    {
      t0: 2.5,
      t1: 5.7,
      title: 'Overlap at full speed',
      text: 'A slow rotation is just a positional swap and creates no advantage. Every rotation must create a free receiver or a mismatch.',
      focus: ['rb', 'rw', 'd1'],
      cues: {
        rb: 'Full speed into the wide lane. Slow is worthless.',
        rw: 'Into the half-space, receive between the lines on the half turn.',
        d1: 'Head turning between two attackers — the rotation is working.',
      },
    },
    {
      t0: 5.7,
      t1: 8.6,
      title: 'Take the empty zone',
      text: 'The inside midfielder is the balancing player: drop into the vacated fullback position, or make the third-man run beyond both.',
      focus: ['im', 'rb', 'rw'],
      cues: {
        im: 'Third-man run beyond both, into the box.',
        rb: 'Drive to the byline.',
        rw: 'Body open, first touch toward goal.',
      },
    },
    {
      t0: 8.6,
      t1: 10,
      title: 'Arrive in the box',
      text: 'Man marking is broken by rotation; zonal marking is broken by overload. Rotate the personnel so every player learns all three roles.',
      focus: ['im', 'rb', 'gk'],
      cues: {
        rb: 'Cutback rather than a high cross.',
        im: 'Arriving late, finish into the open side.',
        gk: 'Committed to the near post.',
      },
    },
  ],

  'atk-15': [
    {
      t0: 0,
      t1: 3.8,
      title: 'Establish as a striker',
      text: 'Start on the last shoulder. The drop only works if the defence first believes you will stay.',
      focus: ['f9', 'cb1', 'cb2'],
      cues: {
        f9: 'On the last shoulder. Make them believe you are staying.',
        rwf: 'Hold the wide lane for now.',
        lwf: 'Back post is your responsibility throughout.',
        cm: 'Support behind and to the side, roughly 8m away.',
        cb1: 'Decide as a pair: follow him or hold the line. Both are legitimate.',
      },
    },
    {
      t0: 3.8,
      t1: 5.2,
      title: 'Drop and scan',
      text: 'Drop into the pocket 25 to 30m from goal. Scan before receiving — you must know whether a centre back has followed you.',
      focus: ['f9', 'cb1', 'cm'],
      cues: {
        f9: 'Scan first. If he is tight, one touch lay-off and spin instead.',
        cb1: 'Following him — which means you are leaving space behind.',
        cm: 'Offer the lay-off if he is pressed from behind.',
        rwf: 'He has followed. Your run into that space starts now, not later.',
      },
    },
    {
      t0: 5.2,
      t1: 6.5,
      title: 'Attack the vacated space',
      text: 'The key run in the drill: inside-diagonal from the wide lane into the gap between centre back and fullback, started as the nine receives.',
      focus: ['rwf', 'f9', 'cb1'],
      cues: {
        f9: 'Facing forward — now look immediately at the space you vacated.',
        rwf: 'Inside-diagonal into the gap. Waiting until the pass is on means the line has adjusted.',
        lwf: 'Hold the back post. Two runners into the same gap cancel out.',
        cb2: 'Covering across, but the gap is already open.',
      },
    },
    {
      t0: 6.5,
      t1: 10,
      title: 'Finish',
      text: 'The false nine creates a dilemma rather than a solution. Teach players to read which dilemma the defence chose.',
      focus: ['rwf', 'gk'],
      cues: {
        rwf: 'Into the open side of the net.',
        gk: 'Beaten across goal.',
        f9: 'Receive, lay off, turn and attack the space you made — often the best sequence.',
      },
    },
  ],
}
